-*-eval: (set-input-method "czech-qwerty");-*-
https://github.com/Oscar-Rosenwald/Monte-Karlos
* Nejvyšší vůdce všeho učitelstva
** Kabinety
*** Přízemí
- Mlčoch, Jonasová
- +Lenka Poláková+, ~Jana Horáková~, ~Ludmila Malá~
- Jíří Lysák, +Jiří Horký+, +Jana Menšíková+
- Josef Král (školník)
*** 1. Patro
- ~Taťána Pálkovská~, Marta Křenková
- ~Jiří Šeiner~, ~Dušan Rychnovský~
- Sekretát: +Monika Vlčková, Naděžda Prášilová+
- Ivo Macháček (mrkev)
"Lépe nepojmenovat"
- ~Radovan Langer~
- Fyzika: ~Taťána Jakešová~, ~Dagmar Kolářová~, +Dana Kubešová+, +Zdeněk Jemelík+
- Čeština: Hana Mužíková
- Anglický jazyk: _Martina Rotreklová_, ~Pavla Záchelová~, Lenka Vývodová
- Německý jazyk: +Marie Vávrová+, Zdenka Lajdová, Věra Zemánková
klepat: 1x, 3x a pak 5x; "Kabinet zla"
*** 2. Patro
- Zeměpis: +Martina Hapalová, Nikola Stodůlková+
** KUSy
*** Velká pětka:
1. Horáková
2. Rotreklová
3. Mužíková
4. Malá
5. ~Záchelová~
*** Větší pětka:
1. Horáková
2. Malá
3. Křenková
4. Rychnovský
5. Rotreklová
6. Mužíková
7. Stodůlková
8. Kolářová
9. Zemánková
10. Havell
*** Pálkovská squad:
1. ~Pálkovská~
2. Macháček
3. Jakešová
4. Lysák
5. Král
6. Vávrová
7. Poláková
8. Šeiner
9. Ebbe
10. Hapalová
11. Horký
12. Menšíková
13. Kubešová
** KBSy
* Fáze
** Horáková X Pálkovská
High Fantasy
** Malá X Kult + Rotreklová
Krimi
*** Zmizelí
**** Langer
Hned na začátku.
**** Horáková
U bitvy u Nového Dilhi.
**** Macháček
Tři měsíce po bitvě u Nového Dilhí.

Unesen někde v Dilhí Waldu. Jeho pravá ruka, Komisař Pedro, byl jediný, kdo se dostavil do DWF a řekl o tom lidem.
**** Mužíková
Unesena během bálu, kam byl pozván Šeiner, kde přitahoval pozornost.
**** Vávrová
Na procházce kolem Der Weiderhohlle Flüsemschliessem před Tlačenkou.
**** Šeiner
Zmizel z Tlačenky
**** Jakešová
Zmizela tunelem z bunrku.
**** Zemánková
Zmizela tunelem z bunrku.
**** Ebbe
Zmizela tunelem z bunrku.
**** Vývodová
Zmizela tunelem z bunrku.
**** Král
Zmizel tunelem z bunrku.
**** Lysák
Odjel zkontrolovat tělocvičnu a už se nevrátil.
A pak se vrátil. Nikdy nezmizel.
**** Kolářová
Zmizela po svém rozhovoru.
*** Čísla
**** [[file:materialy/faze%202/1%20-%201.4./Op%C4%9Bt%20zde%20a%20v%20pln%C3%A9%20s%C3%ADle.org][1.4.2020 - Opět zde a v plné síle]]
- Natočeno <2020-02-22 Sat>
- *Host:* Jakešová
- Vyšetřování není
- *Zmizelí*
  Horáková
**** [[file:materialy/faze%202/2%20-%2019.4./%C4%8Ceho%20je%20moc...org][19.4.2020 - Čeho je moc]]
- Natočeno <2020-03-14 Sat>
- *Host:* Šeiner
- *Vyšetřování*
  Část první: [[Nepřítel za branami]]
- *Zmizelí*
  - /Mezi:/ Macháček
  - /Po:/   Mužíková
**** [[file:materialy/faze%202/3%20-%203.5./Pot%C3%AD%C5%BEe%20neMal%C3%A9.org][3.5.2020 - Potíže neMalé]]
- Natočeno <2020-04-11 Sat>
- *Host:* Malá
- *Vyšetřování*
  Část druhá: [[file:materialy/faze%202/3%20-%203.5./Pot%C3%AD%C5%BEe%20neMal%C3%A9.org::*_%C4%8C%C3%A1st%20druh%C3%A1:%20Ne%C4%8Dekan%C3%A1%20spojenectv%C3%AD_][Nečekaná spojenectví]]
- *Zmizelí*
  - /Mezi:/ Vávrová
  - /Po:/   Šeiner
**** [[file:materialy/faze%202/4%20-%2017.5/Host%C3%A9%20zvan%C3%AD%20a%20nezvan%C3%AD.org][17.5.2020 - Hosté zvaní a nezvaní]]
- Natočeno <2020-04-25 Sat>
- *Host* Rotreklová
- *Vyšetřování*
  Část třetí: [[file:materialy/faze%202/4%20-%2017.5/Host%C3%A9%20zvan%C3%AD%20a%20nezvan%C3%AD.org::*_%C4%8C%C3%A1st%20t%C5%99et%C3%AD:%20Tajemn%C3%A1%20rozcest%C3%AD_][Tajemná rozcestí]]
- *Zmizelí*
  - /Mezi:/ Lysák
  - /Po:/   Jakešová, Zemánková, Král, Ebbe, Vývodová
**** [[file:materialy/faze%202/5%20-%2031.5/L%C5%BEi%20pod%20hradbami.org][31.5.2020 - Lži pod hradbami]]
- Natočeno <2020-05-09 Sat>
- *Host* Kolářová, Rychnovský
- *Vyšetřování*
  Část čtvrtá: [[file:materialy/faze%202/5%20-%2031.5/L%C5%BEi%20pod%20hradbami.org::*_%C4%8C%C3%A1st%20%C4%8Dtvrt%C3%A1:%20%C5%A0peh_][Špeh]]
- *Zmizelí*
  - /Mezi:/ --------
  - /Po:/   Kolářová
**** [[file:materialisticke%20centrum/faze%202/6%20-%202.6/Op%C4%9Bt%20zde,%20o%20n%C4%9Bco%20slab%C5%A1%C3%AD.org][2.6.2020 - Opět zde, o něco slabší]]
- Natočeno <2020-05-23 Sat>
- *Host:* Malá (znovu)
- *Vyšetřování*
  Část pátá: [[file:materialisticke%20centrum/faze%202/6%20-%202.6/Op%C4%9Bt%20zde,%20o%20n%C4%9Bco%20slab%C5%A1%C3%AD.org::*Vy%C5%A1et%C5%99ov%C3%A1n%C3%AD%20-%20_%C4%8C%C3%A1st%20p%C3%A1t%C3%A1:%20Dopisy_][Dopisy]]
  Část šestá: [[file:materialisticke%20centrum/faze%202/6%20-%202.6/Op%C4%9Bt%20zde,%20o%20n%C4%9Bco%20slab%C5%A1%C3%AD.org::*Vy%C5%A1et%C5%99ov%C3%A1n%C3%AD%20-%20_%C4%8C%C3%A1st%20%C5%A1est%C3%A1:%20Bedna%20dynamitu_][Bedna dynamitu]]
- Zmizelí nejsou, lidi se najdou.
** Šeiner X ???????
Thriller
** Zemánková X ????????
Hist
** Kolářová/Horáková X Lysák
Hunger Games/Endgame?
* M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S.
** Ředitel
** Odnože
*** KKL
- Vylučuje učitele ze závody, pokud zjistí, že mají armády (2. fáze)
- Zajišťuje dodržování pravidel závodu
*** OPF
- Goliáš Oberprußer: vedoucí
- Stará se o finance Úřadu
*** QXM
- Má na starost veřejné mínění o Úradu
*** OPQ
- Vojenská síla
- vlatní Omma Céb a la Sviña costa
* Spolková bankovní federace
* Věštba
Ač bude mít cíle v dlani,
počíhá si kdosi na ni,
kteřáž zalže za úsvitu,
sám, jen s bednou dynamitu.
V amoku a vlně vzteku
přinese tak zkázu věku
a až v šoku po tom skutku
nerozeznáš slzy smutku
od slz padajících z mraku,
slabým hlasem za soumraku
tehdy mrtví hrdinové
vyvolají věky nové.

Avšak koncem toho roku
přijdou vhodné náhlé střety,
podměte té druhé věty,
ne vám, ale pravdy soku.

Dáma hrozeb posedává
mimo dosah ruky práva.
Přetne naši víru v půli,
avšak proti její vůli
budou širé davy ctíti
muže světla v temné síti,
věcoudího, co se stane
z knihy dosud nenapsané.
Ze světa, kde jednoduše
válčí každá druhá duše
nad kantory moci o pel,
zbyde jenom prach a popel.

Dáma byť je sama v cele,
ti, co stojí v temném koutě,
šeptají a k sobě zvou tě;
Našeptávač v jejich čele.

Z prachu ruky prstů pěti
uvržený v nepaměti
krutý fénix zapomnění
branou, která ještě není,
získá zbraně nepřítele.
Přísně, krutě, podezřele
nebezkého silou koně
bude držet nezákonně
vzpomínku na staré časy.
Žena Země slíbila si:
nenechá ho vládnout času.
Ve hvězdách pak najde spásu.

Skrze všechna naše muka,
přetvářka a čiré lhaní
neboť zafunguje na ní,
profituje trýzně ruka.

Na stráních u Dilí Waldu,
školník kde chtěl jídla haldu,
čekající rána jasu
uslyšíme slova času.
Pak u hrobu soupeřova,
vyřknou-li ta správná slova,
uzří pravdu historie,
život když je nezabije.
Nebudou mít precedenty,
střetnou kde se elementy,
První vzdor a jeho chrti,
až zaznějí tóny smrti.

Překvapen, ve stavu nouze
svalí kledbu nevídanou
na ty, kteří kolem stanou,
on, jejž můžeš přežít pouze.
