# -*-eval: (setq-local org-footnote-section "Poznámky"); eval: (setq-local ispell-personal-dictionary "/home/oscar/Documents/Monte-Karlos/.spelling.cs.pws"); eval: (set-input-method "czech-qwerty"); eval: (set-register ? "M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S."); eval: (set-register ? "■"); eval: (set-register ?I "I-ii-II-i-i-IIIII"); eval: (set-register ?i "I-ii"); eval: (ispell-change-dictionary "czech"); eval: (flyspell-mode 1); eval: (typopunct-mode 1); eval: (typopunct-change-language "czech"); eval: (hide-lines-matching "# *-\*-.*"); eval: (hide-lines-matching " *# *LocalWords:.*")-*-
                         #+title: MONTE KARLOS NĚKDENÍK
                             #+subtitle: Staré časy
                             
* 1/2022
Ročník XXXIX_{VIII}

*Adresa redakce:* Karlosova 77, 000 03 Monte Carlo 4

*E-mail:* EmailNoReply@server.mok

*Zákaznická linka:* 0004 892 223 03E

*Šéfredaktor:* Alžběta Ašelová

*Manažer redakce:* Jiří b'Ačkora

*Zástupce šéfredaktora:* Hobbo Habán

*Fotograf:* Alexandra Dimitrij von Dieseldorf

*Grafická úprava:* Tara Kočí

*Obrazová redakce:* Honza Kůň

*Editoři:* 

*Rozhovor:* Karlos Žebatý

*Muž v poli:* Lubomír Lečko

*Móda:* Šlapeboso Elle'Gante

*Trpasličí průvodce:* Glopřezub Pátý

*Kaňonskop:* Magistr Celestius

*Martinismus:* Mslg. Vašek Lebéčný

*Jak to vidí Pidilidi:* Bufur, syn Goldrena, syna Ondřeje Nováčka a Marie rozené Babřínové

*Vydavatel:* Monte Karlos Inc. a. s.r.o. a spol©

*Brand manager:* Karlos Žebatý

*Sociální poradce:* Lightningh Danger

*Sociální podpora:* Anna Oleš

*Inzerce:* Many Hrabal

*E-shop:* nakupsisam.cz

*Tiskne:* individuálně

*Korespondent:* 

*Zitorak imperátor:* Psáno automatickým deníkovým systémem Temné Říše

*Rytíři Vědy:* I-ii-II-i-i-IIIII

*Dynamické tisíciletí:* Derdemelè d'Erdemellaisse

*Karlosova Svatá válka:* Lubomír Lečko

*Rozšiřují:* google.com
* Jak to vidí Pidilidi                                      :700:
** Moderní trpaslík                                         :700:
Z důvodů ne zcela zřejmých našim čtenářům přinášíme náhled do každodenního života těch nejníže postavených tvorů naší dimenze. Jsou malí. Jsou hrabaví. Jsou tvrdohlaví. Jsou to...

Ano, já vím, přečetli jste si nadpis. Víte, o kom mluvím. Ale mývalové nejsou tak jednodušší, jak si... Co? Jo, to je o trpaslících. Pardon.

Ano, v dnešním světě má člověk i dinosaurus spoustu vlastních problémů, žongluje nevyspalý a v sociální depresi trojici hořících míčů nájmu, dětí a závislosti na pohonných hmotách[fn:1], a snadno mu uniknou malé detaily života, jako včelka poletující kolem orchideje na okenici nebo vůně oregana na slabém letním větru nebo fakt, že jeho planeta je podkopána rostoucí populací všech pěti trpasličích klanů, a to tak mohutně, že je prakticky dutá. A finančně založení a naložení trpaslíci z více než dvanácti strašlivých nehod vytřískali prvotřídní reklamní kampaní a vlastní vynalézavostí notné turistické atrakce, na kterých malé děti skočí do neznáma a vynoří se na opačném konci zeměkoule k naprosté úlevě rodičů, kteří v tu chvíli musí řešit jenom ten nájem a pohonné hmoty.

Monte Karlos Někdeník si stanovil za úkol přiblížit trpasličí svět tomu našemu, a to širokopásovou informační vlnou, jejíž jste nyní nechtěnými svědky.

Začněme již zmíněnými klany. Jedná se o Dutokopce, Permoníky, Gimlijovce (přistěhovalce z jiné dimenze), skupinu Lopata a Zprodrhelpřetřženčichopolovce (někdy zvané „Oni“). Kdysi dávno začaly klany na různých úrovních podzemní hloubky, ale s objevením internetu, valící se globalizací a subsekventním šetřením na stavebních materiálech se postupně smísili do jednoho celku, až na Permoníky, kteří zůstávají z vlastní vůle autonomní, Gimlijovce, kteří svým původem automaticky nezapadají, a Dutokopce, kteří patří mezi tu skupinu bytostí, jenž si večer promne oči a ptá se, jestli už je ráno, nebo zase všechno zaspali, a nevšimne si přitom, že slunce vyhaslo a kamaše už se nenosí. A je nutné poznamenat, že skupina Lopata hlasitě mluví o odtržení od tohoto celku již od jeho vzniku.

Trpasličím duchovním i pracovním životem se budeme zabývat jindy a největší výtvory jejich civilizace si rovněž ponecháme na později, dovolte nám tedy zaměřit vaši pozornost na možná nejpodstatnější aspekt trpasličího života - vztah s ostatními obyvateli planety.

Je lidskou přirozeností vidět svět osově centralizovaný kolem očí, které ho pozorují. Člověk má pocit, že je pánem všeho a všude, a pokud ne on, tak členové jeho biologického druhu. Myslí si proto, že většina Země přirozeně patří jemu.

Trpaslíci naopak vidí život neochvějnou faktuální čočkou zrozenou z vědomí přirozené selekce, že /někdo/ na planetě by měl mít rozum, a je tudíž zarážející až překvapivé, pro někoho dokonce neskousnutelně urážející až amorální, že došli k tomu samému závěru. Většina planety totiž připadá jim.

Převážné procento Země je pod zemí, a tam jsou i trpaslíci. Jejich znalost „světa pod světem“, jak tomu říkají, staví naše chápání hřbetu vlastní ruky do ostudné nicoty[fn:2]. Obecně držené trpasličí názory na naši civilizaci se asi nejlépe uzří na výroku jednoho slavného Gimlijovského básníka: „Ležím si tak na dně propasti, prohlížím si oblohu a najednou uvidím nějakého idiota, jak se dívá dolů a klepe se strachy, že se dívám zpátky.“

Lidské vztahy s touto subpovrchní skutečností, které říkáme Trpaslíci, jsou přesto vesměs pozitivní. Sem a tam dochází k odporu poháněnému desinformací, ale to jsou maličkosti. Platí pravidlo, že pokud za to zaplatíme, nebo na to nesaháme, můžeme si s čím chceme dělat co chceme a trpaslíkům to vadit nebude. A lidé mnohdy ani neví, že trpaslíci existují, takže vše je vyřešeno. K větším spojení dochází v pronajímání si jeden druhého - trpaslíků na stavbu a lidí na zábavu a přístup k internetu - a samozřejmě v politických sférách, zejména v těch týkajících se M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S., ale o nich později.

V čem se lišíme asi nejvíce, jsou rodinné vztahy, které tito malí tvorové[fn:3] stavějí mnohem výše než lidé. Nesmíme ale zapomenout, že v trpasličí lingvistice má slovo „stoupat“ stejný význam jako pro nás „klesat“. Vyvoďte si z toho, co uznáte za vhodné.

To by bylo pro dnešek vše. Pokud vás zajímají podobné rozbory, nenechte si ujít naše příští číslo, a ptáte-li se, proč vám o nich vyprávíme, kdo ví... Možná se to dočtete. Když budete mít štěstí.
* Zprávy                                                   :1000:
** Čas od času                                             :1000:
Inu, vítr vane, voda teče a časy se mění. Vše je dynamické a neustále transformující. Dalo by se říct, že věci se měnit /musí/. A někdy se prostě změní do podoby, ze které se nedávno vyhrabaly.

Po nečekaném odvetném úderu proti M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S., Monte Karlos, jejímu neštěstí, jejím schopnostem a světu vůbec, podařilo se paní Záchelové obsadit ty nejvyšší pozice naší planety.

Navzdory jejímu snažení o krutou cenzuru, kterou zavedla již ve svém prvním dni vlády, nepostavila paní Záchelová Nebeského koně svýma holýma rukama a nevyzdvihla ho na oběžnou dráhu silou vůle. Prostě využila dvou náhodně sešlých skutečností - téměř zapomenutá paní Pálkovská postavila do svého ohromného projektu Trojského koně, kterého se rozhodla zhotovit ve tvaru kovové koule obíhající naši planetu, přístup do dimenze Internetu; a pan Šeiner odemkl brány Dark Webu ve svém chválihodném boji o svobodu lidstva nad krutovládou nejen Lajdové, nýbrž /závodu/ samotného. Bylo jen otázkou dobře zvoleného průvodce a Záchelová se zmocnila Koňského vojenského kolosu, který pouze dostavěla. Jak se dozvěděla o obou těchto skutečnostech zůstává záhadou a žádný novinář se neodváží vznést potřebné otázky. Včetně mě.

Přes jednoznačný soulad názorů všech společenských tříd na Šeinerovu nabídku mírnějšího /závodění/ a snížení finančních prostředků kantorům k dispozici došlo pouze ke třem velkým demonstracím, a to v ruinách Der Weiderhohlle Flüsemschliessem, které Záchelová pro jistotu odpálila ještě jednou a dav se rozutekl a následně roztekl, u vstupu do Babylonu, kde Šeiner držel svůj již slavný projev a kde už žádný Dimenzionální portál nenajdete, a v malé chatě zednáře Koučera, kde se podařilo v naprosté tajnosti nashromáždit pětadvacet tisíc lidí a stejně tajně je odtamtud dostat. Nikdo se o té poslední nikdy nedozvěděl.

Pod hrozbou Koně drží Záchelová celý svět. Vlády se přetahují o to, kdo zůstane méně nápadný, a raději platí nově zavedenou daň z existence, a velké korporace jedna po druhé ohýbají kolena a klanějí se v poslušnosti buď Záchelové, nebo její pravé ruce, proslule záhubné ~[to je slovo, že jo?]~ Křenkové. Dokonce i Mezinárodní Úřad nevydržel nátlak a jeho protesty se rozutekly v ruinách jejich dřívějšího sídla, které paní Záchelová zničila jako první coby pomstu za své dlouho držené a spravedlivě nízké místo na žebříčku v /závodě/. Monte Karlos přišel jako druhý.

Paní Záchelová, rozzuřená do nepříčetnosti že už o tom nevíme, i když nám to nikdy dřív nesdělila, se nechala slyšet: „Závod o nejvyššího vůdce všeho učitelstva se tímto nenávratně ruší.“ Představte si to smutné povzdechnutí davu, který si teprve nedávno troufl představit, že /závod/ může nakonec vyhrát i někdo normální. „Místo toho,“ pokračovala, „bude Mezinárodní Úřad pro Úplnou a Asertivní Spolupráci Spojených Států Místních i Zahraničních za Účelem Světového Míru, Obchodu a Výměny Služeb[fn:4] pokračovat ve svém snažení, pod blízkým dohledem Křenkové, vybrat mi pobočníka. Vše v /závodě/ pokračuje, jak to šlo doteď, akorát vítěz nedostane nejvyšší pozici.“

Ostatní učitelé nebyli příliš spokojeni, obzvláště pak ti, kteří se v dobu Dusavých kopyt, jak se útoku na Monte Karlos říká, nacházeli ve svých veřejně známých sídlech. Ti skončili v politickém zajetí paní Křenkové a jsou nuceni nejprve dostavět střídmější verzi Der Weiderhohlle Flüsemschliessem a poté /závodit/ o druhé místo. Jistí jedinci se dopustili hříchu hlasitého nesouhlasu a od té doby jsou nezvykle tiší.

Po kantorech, kteří šli bojovat s Lajdovou do Babylonu, se Zem i jiné planety slehly. Tehdy nashromážděný dav je měl v plánu odvézt do Bavorska, kde je čekalo mírumilovné a sportovní pokračování /závodu/, ale po Dusavých kopytech je tentýž dav pomohl schovat na tajná místa, odkud řídí marný odpor.

Nepokoj se šíří i mezi Spolkovou bankovní federací. Jejich největší sázka - Lajdová - padla společným úsilím a každá spolková banka by ráda viděla návrat do starých kolejí, která Šeiner tak zevrubně vyrval z pražců. Nejprve se zdálo, že Záchelovou uvítají s rozpřaženými trezory, ale ona měla jiné nápady. Bez okolků a takových nesmyslů jako odůvodnění zkonfiskovala veškerý majetek původně patřící Dvaceti statečným[fn:5] a pod ostražitým okem Nebeského koně spokojeně odkráčela středem.

Většina těchto financí však nešla na utlačování lidu. Kůň jí na to vystačí bohatě. Místo toho věnuje Záchelová velkou pozornost nově rostoucí hrozbě. Svět se ocitl v naprostém zmatku díky Šeinerovu odemknutí Dark Webu, respektive ochranných zámků na všech známých branách umístěných tam Staršími Internetu. Jak jistě víte, ~[Nemáme jméno pro naši Říši, sakra]* sousedí s Temnou Říší přímo. Kontakty mezi dimenzemi těchto Říší jsou řídké a většinou sestávají z občasného vyvolání démona, ale z Internetu se do Dark Webu lze dostat jednoduše, a jelikož Internet je takzvanou poddimenzí *[Furt to méno nemáme]~, představují otevřené brány problémy pro všechny naše dimenze[fn:6].

Prostě a jednoduše, všechny možné příšery a zrůdy Temné Říše se nekontrolovatelně valí z Dark Webu do Internetu a odtamtud i na Zem. Záchelová převzala svrchované velení nad Odnoží SQL Mezinárodního Úřadu, která historicky chrání Zemi před útoky z Dark Webu. Dokonce byli nejednou najati obyvateli Internetu jako žoldáci. Vedoucí této Odnože, Francesco di Řím řečený Starý, má přímé rozkazy od Záchelové setrvávat v Internetu a odrážet ustavičné nátlaky temnoty. Co ho drží v jejím velení přes očividné osobní neshody není známo.

Záchelová má volnou ruku udržovat pořádek, jak ho sama definuje. Nebeský kůň poletuje nad našimi hlavami, vyplněn po okraj její osobní armádou - kantory nespokojenými s Šeinerovým systémem /závodění/ - a hrozí a hrozí a hrozí. Odpor pomalu odumírá, lidé si zvykají na dalšího tyrana, mnohé dimenze, dříve zdroje bohatého obchodu, nám zavírají hranice a Dimenzionální portály a po Monte Karlos ani vidu, ani slechu.

Někteří dobrodruzi se pokusili lokalizovat paní Pálkovskou, která jediná může znát slabiny svého vlastního stroje na smrt, ale marně. Zcela marně. Všechno je marné...
* Rytíři Vědy                                              :1200:
** Krátká historie Řádu                                     :200:
Prastarý Řád Rytířů Vědy má dlouhou historii, která sahá přinejmenším k devadesátým létům dvacátého století, a nálezy zkamenělin značí, že možná i mnohem dál. Neleží v živé ani mrtvé paměti, kdo ho založil, za jakým účelem, kdy, kde, jak a za kolik.

Mezi svými současníky z nám zcela zahalené doby svého počátku vynikl zaměřením na korektní učení jazyků a velmi prestižním členstvím. V každém momentu má Řád pouze jednoho člena tvořícího Radu Vědájů, který nese Řádní znalosti a ideály, leč se nedá vypátrat, co za ideály to má být.

Slovo Vědy v názvu Řádu nepochází od slova „věda“, nýbrž z pralatinského pojmu „věda“, který znamená něco zcela jiného.

Jeho protějšek - krutý a zvrácený řád Žit - s ním vede věčnou, tajnou válku více než o myšlenkové postoje o to, který Řád bude divnější[fn:7]. Jejich konflikt je nejen odvěký, nýbrž rovněž velmi starý. Členství v obou je přísně střežené tajemství, nejspíš proto, aby druhá strana nepoužila osobní život členů té druhé proti nim. Zemánková to považuje za velmi inteligentní opatření, sama ho svědomitě dodržuje (i když sama uspěla, kde jiní doteď selhali) a já kráčím v jejích stínech. Stopě. Tohleto.

Proto se vynasnažím nijak nezveřejnit své jméno, ani jiné osobní údaje.
** Co v tom dělám já[fn:8]                                  :200:
Mé jméno je I-ii-II-i-i-IIIII[fn:9], zkráceně I-ii. Jak jsem se sem dostal? Dlouhý příběh. Kdo jsem? Nedůležité (říká Zemánková). Co o mně máte vědět? Krom toho, co sem píšu, nic moc. Čím budu? To je to podstatné.

Jsem učedník Řádu Vědy. Vždy to tak bylo - jeden člen, jeden učedník. Až Zemánková odejde do Říše Duší, povýším na plnohodnotného Mistra Vědáje. Do té doby se mám, co učit. Říká Zemánková. Kývám hlavou a zapisuji si, jak správně vysvětlit psaní čárků a háček a doufám, že při závěrečné kontrole mého sešitu nenajde můj Mistr hodně chyp. Chtěl bych začít něco dělat. Sedět takhle zavřený, to není pro mě. Ale co? Nejdřív se musím učit.

Říká Zemánková.
** Nedávné roky                                             :250:
Poslední léta přinesla nové prospekty pro vztah Rytířů Vědy a Žitů, jmenovitě možnou zkázu těch druhých. Jejich nekonečný boj se několikrát přiblížil zdárnému konci. Nebýt jistých záhadných událostí. Když Mistr Zemánková poprvé vyrazila do boje s Nárt Vědrem[fn:10], před dvaceti lety, vypadalo to nadějně.

Představte si - noc, listí padá, nad vámi se zlověstně tyčí zasněžená hora jejíž špici nedohlédnete, a dva Řády se připravují na utkání Mistr proti Mistrovi, neboť i Žitové mají vždy jen jednoho člena. A pro případ nehody, připravil si váš šampion lavinu, která smete z povrchu zemského všechen odpor.

Bojují. Perou se. V kompletní tmě se střetne vůle s vůlí a, nevidění, Mistrové bojují o přežití svého Řádu. A náhle - Zemánková vítězí. Však zradou její nepřítel zvládne utéct, ne ale před lavinou. Tuny sněhu ženou se po srázu a pak... nic. Blesk uhodí do skály a vše je zahaleno párou.

A tak to pokračovalo boj za bojem. Vždy nepochopitelným štěstím dostal se nepřítel z našich spárů. Na jednom takovém souboji jsem byl. To bylo poté, co Zemánková historicky první vypátrala protivníkovu totožnost. Pamatuji si skály tvaru písečných dun a šumění moře a neprostupnou horu štěrku, kterou Zemánková použila jako vězení, ale... Ze dna pouště vytryskla voda a odnesla nás i s kamením.

A tak jsme se přestěhovali. Blíž a blíž jsme se vetřeli do protivníkova života, až jsme, ujištěni ve své pozici, chtěli zasáhnout. Kdyby jen nebylo toho Koně. Ačkoli už ne v jeho kolegiální přízni, navěky budeme opakovat jeho jméno - Záchelová.
** Podivín                                                  :550:
„A výjimky?“ ptá se Zemánková.

„Výjimky...“ zamýšlím se. „Existují.“

„Já ti dám, existují! To po tobě asi nechci, ne?“

„Ahhh... Ne.“

„Správně.“

„Vážně?“ raduji se a už si balím učebnice, radosten, že jsem odpověděl správně. Než mi stihne vynadat, přeruší Mistra hlasité klepání na dveře. Pronajali jsme si malou chajdu na Tahiti, kde se schováváme před patrolami Záchelové křižující ulice světových metropolí. Alarmovaní sledujeme dveře, dokud se klepaní neopakuje. Zaujímám svou obrannou pozici dle našeho tréninku, většinou prováděného v obýváku, zatímco Zemánková nakukuje škvírou ve dveřích. Dveře to nejsou ideální - mají v sobě škvíru - ale lepší si nemůžeme dovolit, teď, když Záchelová ukradla naše peníze.

Zemánková otevírá. Na skromném chodníku, který plánujeme zhotovit někdy příští týden, to jest na trávě, vyplňuje trám stylově oděná štíhlá postava. Jsou to úzké dveře. „Smím dál?“ zeptá se již vkráčivší host.

A znovu to zaklepání. Venku nikdo není. Zemánková je obezřetná.

„Pardon,“ řekl příchozí. Do kapsy si schoval telefon, kde zřím internetové video se zvuky klepání na dveře. Sedá si na vrzající stůl. „To byl omyl. Tak, kde jsme to přestali?“

„Pojdtě dál,“ říká Zemánková.

„Jak milé od vás,“ odpoví on a přelétne očima mé učebnice. Musím se napomenout, že jsem je nechal takhle vystavené. „Mé jméno je Lečko. Lubomír Lečko.“

„Těší mne.“

„Mne rovněž.“

Zemánková drží dveře otevřené, pro případ úprku. „Jak jste mě našel? Monte Karlos je pryč.“

„No to jsem rád, že mě poznáváte. Opravdu nadšený. Ne, že bych do toho přestrojení dal půl dne.“

„Představil jste se mi.“

„... Aha. No nic. Jsem tu pracovně.“

„Pro koho pracujete teď? Jsem překvapená, že vůbec žijete.“

Lubomír mává rukou. „Za to vděčím pustému ostrovu.“ Neměl potřebu se dál vysvětlovat. „Mám pro vás zprávu.“ Napřímil se. „Karlos Žebatý žije.“

„Tak to jsem vám neskonale vděčná. Děkuji. Nashledanou.“

„Máme pro vás práci, ze které můžete příjemně těžit.“

Ah! Nabídka. Je to jedna z těch proslulých, které nelze odmítnout. Vždycky jsem takovou chtěl dostat.

„Týká se to vás,“ ukázal na učebnice, „vašeho učedníka a Řádu, jehož jméno si netroufnu vyslovit takto na veřejnosti[fn:11].“

Bez okolků skáču ven z vědra s vodou a chytám Lečka za límec. Zemánková už zabouchla dveře. Lečko na mě překvapeně mrká. „Odchován delfíny. To jsem měl čekat.“

„Jak jste nás našel,“ ptám se, „a jak víte o Rytířích Vědy?“

„Ve svém volném čase,“ vytlačí ze sebe, „se věnuji vyšetřování. Nebojte, kromě Karlose a všech dvanácti tisíc zaměstnanců Monte Karlos a jen těch nejnezbytnějších bohů Olympu nikdo neví, že do Řádu patříte.“ Obrátí oči na Zemánkovou. „Ani Záchelová.“

Mistr se opírá o dveře, aby zakryla škvíru. „Pokračujte.“ I mě je jasné, že jeho „práce“ pro nás může být přínosná. Povoluji stisk na límci.

Lečko se ošívá. „Pan Žebatý vyhlásil Karlosovu Svatou válku. Stavíme tým. Odvetnou skupinu elitních vojáků, kteří proniknou až k Záchelové a pomstí naše Studio. Ale pro případ, že selžou, chtěli jsme požádat vás.“

„Myslíte spolupráci?“ Lečko přikyvuje. „I-ii, pusť ho.“ Pouštím ho.

Následuje dlouhá debata mezi dospělými, během které suším nad sporákem mokré učebnice. Znovu. Když skončí, je už tma. Ona byla tma už když začali, ale je tam pořád. Dlouho sedí.

„Nelíbí se mi to,“ Zemánková přesvědčuje sama sebe. „Líbí se mi to, I-ii?“

„Ne, Mistře.“

„Ne, nelíbí. Jak se mi to nelíbí?“

„Vůbec, Mistře.“

„/Vůbec/ se mi to nelíbí.“ Kroutí hlavou. „A vy se mi nelíbíte,“ ukazuje na Lečka.

„Vůbec, Mis–“

„Ticho, I-ii.“ Nějakou dobu to probírají. Pak řekne: „Nestačí to.“

Lečko krčí rameny. „Stále se to vyvíjí. Nějaké návrhy?“

Zemánková si povzdechne a já vím, co se blíží. Vypnu radši sporák. Říká: „Potřebujete Zitoraka.“

„Koho?“ diví se Lečko.

„Zitoraka.“ A pak se mluvilo o dost déle.
* Rozhovor
* Korespondent
* Karlosova Svatá válka                                    :1200:
~[Na cestě za Zitorakem, tj. skrz Internet (kde je Francesco s Odnoží SQL) nejdřív do Dark Webu, pak do dimenze Amales Rhkalhan, kde Zitorak vládne]~
** 
* Martinismus                                               :700:
** Martinismus                                              :500:
Takže Martinismus. Založený dvojicí Zakladatelů[fn:12] manifestem /48 Pravd Martinismu aneb vše o Martinismu, Lysacizmu a duších/, jeho zaměření spočívá především ve vzájemném plácání si po ramenou a gratulacích, že jeho členi dokázali něco takového vymyslet. Podle své vlastní definice se jedná o „... nezávislou studentskou iniciativu založenou za účelem přežití Lysacizmu.“ Kdo definuje Lysacizmus? Taky Martinismus. Takové kolečko z toho je. Kam se hrabe had požírající vlastní ocas? Tohle je romanopisec píšící kniho o tom, jak píše tu knihu a neví, co do ní napsat.

Přídavné jméno od Martinismu je „klvanistický“. Samozřejmě. Proč ne? Martinisté si kladou tři životní cíle. Jsem zvědavý, jaké jsou. Něco zajímavého? Užitečného? Hodnotného? 2. Klvanistická Pravda praví:

1. Informovat o Lysacizmu. Už teď z toho nemůžu.
2. Přežít Lysacizmus. /Vážně?/
3. Propagovat Martinismus. No to mě– Já– Já nemůžu.

Představte si publikovaného, uznávaného filosofa, pracujícího na nejvyšší úrovni akademických kruhů. Představte si nabídku psát pro prestižní časopis pod slavným Magistrem Celestiem. Představte si to nadšení, že vaše Teorie Hyperskulární Existence se dostane k mladým a nadějným budoucím filosofům. A představte si, že místo toho mluvíte o Martinismu. Tady je filosofická rada: Čtěte celou pracovní smlouvu, děti. Čtěte ji celou.

Zakladatelé si dali záležet, aby ze sebe shodili zodpovědnost. Jejich ideologie je platná po celém světě, ale může se měnit podle morálních hodnot regionu. Co to je jako za ideologii? Shodili ze sebe i obvinění z opomenutí: Krom Pravd jsou tu ještě Postpravdy, které si Pravdodárný Orgán (ani se proboha neptejte) vymýšlí za pochodu. A to jsme se ještě nepohnuli z 2. Pravdy! Co to je, tohleto?! Proč to není 1. Pravda? Prostě proto. Co je první pravda? Nic. Věřte mi, není to nic.

Prý o tom mám psát, protože jejich vliv roste v odpověď na vzestup Záchelové. Martinismus má nějaký nepochopitelný problém s učiteli a současný politický stav jeho stoupence dovádí k nepříčetnosti a zbytek lidstva ke ztrátě inteligence, protože klvanistické řady rostou.

Dále, /3./ Pravda popisuje klvanistické státní znaky. /Státní/ znaky. Státní znaky /Studentské iniciativy/. To snad není pravda. A protože Zakladatelé si nemohli pomoct, je tu Velký státní znak (3D, pro jistotu, s mraky a karikaturami a blesky a takovými blbostmi), Malý státní znak (výřez z toho Velkého), Mikroznak (ještě menší výřez, pro Boha živého), Pečeť (které mají dvě), Vlajka v neviditelných barvách[fn:13] a Hymna, jak jinak než napsaná v klvanistickém hudebním žánru. Někdo si tu přeje mojí smrt. Asi Celestius.

A kdyby vám nestačilo tohle všechno, pojďme se pro ilustraci mentálního rozpoložení Zakladatelů a všech ostatních Martinistů podívat na jejich poslední, 48. Pravdu: „Všechny pravdy Martinismu jsou nedotknutelné, absolutní a stoprocentně pravdivé.“

Já padám. Je se mnou konec. Proč nemůžu někdy dělat něco pořádného? A ještě těchhle věcí musím napsat pět!
** Lysacizmus                                               :200:
Lysacizmu, přirozenému oponentovi Martinismu, se Martinisté věnují se zájmem kočky honící laserové světlo na úkor lovení myší. Pochází patrně z jistého kantora, který Zakladatele sužoval na střední škole.

Lysacizmus[fn:14] je definován 4. Klvanistickou Pravdou, která ho popisuje jako: „Závislou iniciativu, která si klade za cíl mučení a týrání studentů středních škol, a to všemi možnými legálními fyzickými i psychickými postupy takovým způsobem, že je nelze rozeznat od běžného vyučování, založenou a v praxi uplatňovanou (i po jeho smrti) Jiřím Lysákem, který však není jediným vyznavačem této iniciativy.“

Všimněte si směšně amatérského nutkání opisovat jednoduché koncepty co nejdelšími větami. Ona přeskočená 1. Pravda sestává z téměř sedmi seti slov uspořádaných do nepřehledného sledu umělecko-filosofické nadávky, které Martinismus říká „věta“, a týká se neúměrně složitého obřadu, který je nutné provést v případě, že „kolem vás Lysák projde s černou čepicí“, za účelem odvrácení takto vysloužených deseti let smůly.

Proč? Řekněte mi někdo /proč/. Proč já?

Boj s Lysákem a jeho příznivci staví Martinismus na vrchol svého krátkého listu podstatných věcí. Z nějakého důvodu se jim to zdá důležité. Poslední týdny se Pravdodárný Orgán a Rada Martinismu (já vám ani nevím, co má tohle zase být) nechávají slyšet, že Lysákovo nebezpečí roste, ale jejich jediným argumentem je nadvláda Záchelové, která, ráčíte-li si všimnout, není Lysák.
* Kaňonskop
* Zitorak imperátor                                        :1200:
~[§...§ a @...@ a &...& jsou typy přímé řeči, která patří démonovi. Každý démon má vlastní znak. Ten hlavní démon, Zitorak imperátor, má §...§. Je to tu, protože normální uvozovky na démony nestačej, a v ideálním případě to při exportu nastavim tak, aby se to exportovalo v konkrétnim stylu nebo fontu, kterej ty uvozovky narhradí. Ty symboly tam ve finále nebudou.]~

Zitorak vzpomíná.

Vzpomíná na dobu dalekou. Hlad, chudoba. On a jeho sestra se toulali pustou plání. O myšlenky se jim otíraly lahodné duše smrtelníků. Cítili je. Poslouchali je. Ale hlad utišit nemohli.

Sto let už putovali, daleko od domova, skrz tenké závoje mezi realitami, až Zitorak zvažoval konec. Ale Zitorak, jeho sestra, naléhala. Prosila. Ještě chvíli. Někdo zavolá. Zitorak slevil.

Kde hořely knoty, kde křída kreslila kruh, tam byli a čekali. Když tu náhle...

Malá holčička stála v zapadlé chalupě. Zitorak sledoval. Zitorak sledovala. Oba se smáli.

Holčička nakreslila kruh. Holčička zapálila svíce. Holčička zavřela oči a myslela na tmu. Zitorak jásal.

„Volám tě, démone. Volám tě, bytosti Temné Říše.“ Zitorak cítil blízké i daleké démonní druhy poslouchat ta slova, ale nepatřily jim. Patřili jemu a jeho sestře. „Volám tě, s nabídkou, ó vládce Štěstěny. Volám tě s výměnou na dlani. Ne zadarmo. Ne lacino. Ne–“

/„Né, pětku né, já jsem v tom nevině!“/ Holčička se mračila. Opustila kruh. Zitorak stiskla bratrovo rameno.

„Můžeš to rádio vypnout!“ volala holčička do chodby. „Tady se pracuje!“ Nelibý hluk utichl. Vrátila se do kruhu. Zitorak pohladil její duši. Taková dobrá bude...

„Kde jsem to byla?“ Holčička podupává. „Jo. Ne tohle, ne támhleto, ty to chápeš. /Volám tě/,“ řekla a Zitorakův svět se zachvěl. „Přijď ke mně! Znám tvé jméno, z knihy vyčtené! Zitorak! Zitorak! Zitorak!“

Podlaha zaskřípala. Bum, bum, bum, kroky se blížily. Klika se otočila. V holčičce vyvolala chutný děs. Dveře zavrzaly. „Co tu děláš? Dole je večeře.“

„Ale mamiiiii!“

„Večeře, řekla jsem. Co to má být? Co je tohle zase za výmysl? Okamžitě to sfoukni, ještě vyhoříme. Podívej, ruce máš celé od křídy. Říkala jsem /nekreslit/ na podlahu v domě. Umyj si je. A pojď na večeři.“

„Hned to bude.“

„Teď!“

„No dobře, no.“

Matka odešla. Holčička potichu zavřela dveře. „Jak to, že to nefunguje?“ Listovala knihou, starou, zašlou, plnou vědění. Praštila se do čela. „Čtyřikrát.“ Rychle doběhla zpět do křídového kruhu. „Zitorak.“

Realita praskla. Její slova, její vůle, její činy prostrčily škvírou pařáty a protrhli v ní díru mezi Říšemi. Zitorak ji viděl jako díru ve tmě, sahající po okraje magického kruhu, kudy náhle proniklo pálivé, mučivé světlo. On a jeho sestra spěchali skrz.

Octli se, poprvé za svou existenci, v Ineptu, své sousední Říši. Slyšeli o tom zážitku mnoho, od bohatých překupníků přání. Suché místo. Moc světla na těla pěstované v Temné Říši. Ale hlad přemohl.

§Zitorak tě zdraví, malý příteli.§

@Zitorak také,@ řekla jeho sestra. Ineptus z ní vysával Temnotu a krmil jí plameny svící, barvící se do temně zelené.

„Co?“ vyskočila holčička. „Dva?“

§Vždy dva. Nikdy sám. Zitorak přišel. Tři přání nabízíme. Znáš cenu?§

Holčička ustoupila k oknu. „Moje duše?“

@Ano.@

„Ale to je nefér.“ Další krok. Zitorak tápal. Uvnitř kruhu sourozencům chyběly schopnosti. Nemohl číst její myšlenky. Nemohl ji utišit. Uchlácholit. Nabídnout tisíce blahostí a víc. Další krok od nich. „Jste dva,“ řekla holčička. „Já mám jednu duši.“

§Zitorak se podělí.§

@Zitorak hladoví,@ vysvětlila Zitorakova sestra.

Další krok.

§Stůj, člověče. Dva démony jsi přivolala, dvakrát tři přání ti nabízí.§

„Jedna vám bude stačit?“

@Lepší jedna než nic.@

Holčička stála u okna. Měsíční světlo pálilo Zitorakovu kůži. Holčička se usmála. Vymrštila ruku ven z okna. V ruce držela křídu. Jednou čarou dokreslila připravené vězení a známé světlo magické runy prozářilo stěnou. Okraje místnosti se zamlžily Zitorakovu zraku. Ledové prsty se rozlezly od holčičiny ruky.

„Řekla jsem večeře!“ zavolala ta starší a otevřela dveře, které narazily do neviditelné stěny kouzla.

Zitorak se vymrštil. To vězení rušilo jeho kouzla, ale stejně tak magický kruh. Doletěl do rohu a bušil pěstí z černé mlhy, ale mihotavá bariéra před ním neustoupila. Ta ledová už pokrývala půl místnosti a Zitorak věděl, že z skrz ni se nedostane.

„Co to sakra–“ Ta starší zkusila vejít znovu, marně.

&První vrstva sváže tělo,& Zitorak, jeho matka, říkala před tisícem let, když ještě měli, kde žít, &druhá vrstva chytí mysl.& Nemohl se dostat ven. Nemohl se dostat zpět do dimenze Amales Rhkalhan v Temné Říši. Leda, že by podstoupil nejvyšší oběť.

Zitorak neváhal. Jedinou myšlenkou, mihotavou jako půlnoční záchvěv naděje ztracené duše, přetrhal svazky mezi svou myslí a svým tělem. Jak mysl škrábala na stěny vězení a drala se ven, tělo padlo k zemi a rozplynulo se v oblak černého prachu. Zitorak pohlédl na svou sestru. Její mysl se vznášela na vlnách reality vedle jeho.

§Zitorak lituje. Měl zkontrolovat obydlí.§

@Ne,@ řekla jeho sestra a kroutila by hlavou, kdyby nějakou měla. @Zitorak neviní. Zitorak nabízí.@ A její duše o tón zesvětlila.

Zitorak vyjekl. Její tělo nebylo odevzdáno nicotě jako jeho. Obořil se na vězení a vší silou do něj narazil. Ledová pokrývka ho obalila vrstvou viditelnou jen bytostem z Temné Říše. Už nemohl projít. Ale viděl. Zitorak viděl, jak holčička schovává tělo jeho sestry, násilím odebrané, do truhly. Přísahal pomstu.

@Musíš se vrátit domů, bratře.@

Zitorak věděl, že ona nemůže s ním. Démonova mysl násilím odebraná se rozplyne v momentech. Tělo, nebo mysl, jedno musí zmizet.

Holčička se zarazila ve své práci. Chuchvalec hmotné tmy visel z truhly, kam schovala sestřino tělo. Zavřela oči, a nebýt bariéry mezi nimi, viděl by Zitorak jak otevírá svou mysl. „Pojď ke mně a dej mi své štěstí,“ zašeptala. „Zitorak. Zitorak. Zitorak.“ Zakroutila hlavou. „/Čtyřikrát!/ Zitorak.“

Proužek černi z truhly se odvinul a pronikl do její duše. Jen malé, nepatrné množství. Ta starší zaječela o patro níž. „Sakra! Polévka se mi připálila! Děti, jestli chcete večeři, musíte si vzít perník ze špajzu!“ Holčička se radovala a zaklapla magicky chráněné víko.

@Musíš domů,@ naléhala mizející mysl Zitorakovi sestry. @Vem si mé štěstí. Zitorak stejně zanedlouho zmizí.@

A tak, s ohnivě bolestným pocitem, Zitorak pozřel mysl své sestry. Celou naráz ji vstřebal, a co její tělo tomu dítěti, její mysl dala i jemu - neskonalé štěstí, ale vše naráz.

Když se pak otevřel náhodný portál, Zitorak vešel, nepřekvapen. Když síly z té proklaté dimenze Země v Říši zvané Ineptus vtrhly do jeho domovské dimenze Amales Rhkalhan a vedly válku proti králi Nomizkatovi, nebyl překvapen. Když krále armáda Odnože SQL svrhla a popravila s nepochopitelnou vervou a když čirou náhodou démoni jmenovali Zitoraka svrchovaným vládcem celé dimenze, měl svou sestru, komu za to obrovské štěstí vděčit.

Ale rychle vyprchalo a Zitorak se nikdy nedozvěděl jméno té holčičky, co ho připravila o tělo a sourozence. A roky plynuly, Země se měnila a Zitorak nevěřil, že jí někdy najde.

Teď ve svých komnatách Zitorak imperátor sedí a poslouchá, ale jen zpola. Jeho neforemná existence pluje časem sem a tam, tu soustředěná na nezvaného hosta z Ineptu, tu dekády v minulosti. Zitorak vzpomíná a Zitorak zuří.

§A co mi dáte za pomoc?§

„Karlos Žebatý má mnohé zdroje.“

§Zitorak tu vládne.§

Ten člověk sedí zpříma. Zástupy Zitorakových démonů ho navenek neděsí, ale Zitorak vidí do jeho duše. Za posledních čtyřicet let jich měl dostatek, ale tahle je labužná. Chytrá. Sebevědomá.

„Pomstu, tedy.“

Zitorak vyletí do vzduchu. §Pomstu!§ Doletí před člověčí obličej. §Zitorak poslouchá.§

„Jméno a možnost odplaty. Za tři přání.“

§Zitorak ztratil tělo. Přání budou pouze v myšlenkách a jiný démon s vámi nepůjde.§

„To je v pořádku. Přijímáte?“

Zitorak nechá přinést náramek se třemi oranžovými kuličkami. §Tři přání.§ Člověk po nich natáhne pařát, ale sluha ucukne. §Jméno. První jméno.§

„Záchelová.“
* Karlos Čepice
* Dynamické tisíciletí                                     :2000:
/Pro Antona/
** Chyby mládí                                              :700:
Mnoho bylo řečeno o mládí Francesca di Řím, většina z toho vymyšlená lidmi se slabší představivostí, než jakou má osud. Jím podané datum narození ho datuje do konce šestnáctého století. Víme jen o jednom bratrovi - Antonio, zesnulý roku 1611.

Bylo nad ránem, zima roku 1613, dva a půl roku po rýmové ráně, která vyhladila dvacet procent záhybů a jednoho Antonia. Slunce pomalu vlévalo své ostré světlo do kaňonu mezi skalnatým povrchem Francescovi rodné Itálie, které popisuje jako hranici pro šestnáctiletého chlapce mezi smrtí v horách a nekonečnou slastí světa. Později, dodává, viděl mnohé divy zakrývající ono ráno v mohutném stínu, ale nic se od té doby nevyrovnalo pohledu ze skalního převisu na vlnící se údolí pod ním[fn:15].

Dva roky pátral, až našel, ve staré knihovně nedalekého Říma. Nakreslil kruh. Křída se mu drolila pod rukama - neměl na lepší. Stoupl si do něj a se zavřenýma očima myslel na temnotu a prázdno. Opatrný, aby neotevřel svou mysl a nepozval tak démona dovnitř, začal odříkávat zaklínadlo.

Na konci zvolal: „Nomizkat. Nomizkat. Nomizkat.“ Se svraštěným čelem otevřel oko a pohlédl na skalnatou plošinu. Na moment se zalekl, že mu kniha lhala, ale vzpomněl si. „Jo čtyřikrát. Nomizkat.“

Kdesi nad ním obloha jakoby praskla, puklina se rozšířila co po skleněné tabuli a před ním stanula díra do Temné Říše.

Francesco se klepal námahou z tak složitého kouzla, ale nespouštěl oči z toho úžasu nad sebou. Překvapilo ho proto, když ho oslovil hlas zcela cizí jeho uším, hlasivkám i zvukovým vlnám. Slyšel ho ve své hlavě.

%Voláš Nomizkata, člověče?%

Francesco polkl. „Volám.“

%Čemu vděčí Nomizkat za takovou poctu.%

Mladý Francesco nedokázal odhadnout, zda si z něj démon dělá legraci. Později na ten moment vzpomíná jako na poslední chvíli, kdy pomyslel na vtipy. „Nabízím svou duši k vaší konzumaci, ó vládce Štěstěny, za trojici přání.“

Démon se hluboce nadechl nově zformovanými nozdrami, jako by čichal Francescovu duší. %Aaaaaaaaa,% řekl. %Ah-ah-ah. U-hu-hu-hu-hu,% rozkašlal se. %To je vzduch!%

„Kvalitní, horský... ó vládce–“

%Jó, jó. Štěstěna. Jasně. Nomizkat chápe.% Další záchvat kašle. %Jak to vy smrtelníci vydržíte? Dýchání je pro slabochy.%

„Nic lepšího nemáme.“

%Slaboši.%

„... Ano. Ó vládce. Eeee. Duši? Chcete?“

Jakmile se zbavil svých nozder, sáhl Nomizkat do záhybů svého nehmotného pláště, odkud vylovil náramek s třemi oranžovými korálky. %Tvá duše bude pozřena v průběhu dvaceti let. Do té doby... tři přání. Nomizkat přijímá. Až budeš připraven, člověče, zavolej Nomizkatovo jméno čtyřikrát zopakované–%

„To nebude třeba. Zaprvé, chci žít se svým nejlepším přítelem až do své smrti.“ Po ztrátě Antonia, říká Francesco di Řím, se nejvíce děsil osamění. Radoval se, jak Nomizkat odtrhl jednu perlu z náramku a rozdrtil ji mezi prsty.

Pak se ukázalo, naposledy v jeho životě, že Francescovi bylo šestnáct. „Chci být přitažlivý.“ Druhá perla zmizela.

„Zatřetí...“ Jak naivně, jak amatérsky a hloupě se Francesco šklebil. „Chci žít tisíc let.“ Nomizkat se zarazil. „Copak? Nepřijímáte? Ó vládce?“ škádlil ho s vědomím, že vyzrál. Jeho dřívější přání už byla splněna. Kdyby démon odmítl, zrušil by jejich transakci a Francesco by dostal dvě přání zdarma. Kdyby přijal, nemohl by čerpat z jeho duše ještě devět set čtyřicet čtyři let. Poté se ale usmál Nomizkat. %Zitorak souhlasí.% Třetí perla zmizela. A s ní i Francescova radost ze života, jeho empatie a silné emoce. Jeho život se stal prázdným, jeho dny mělké a nezáživné. Horské ráno mu zšedlo před očima.

Nomizkat s hlasitým řehotem opustil Říši Ineptus a nechal Francesca s duší roztaženou mezi tisíc roků, příliš řídkou na uspokojivý život, jen stěží postačující na ten biologický.

Francescův nejlepší přítel zemřel následující týden při pádu ze střechy a znecitlivělý Francesco dostal akvárium s dva centimetry dlouhou medúzou a znakem tří perel vyrytým do skla. Byl to Turritopsis, nesmrtelný živočich z moře, a do dneška jediný smrtelný tvor, o kterém Francesco ví s jistotou, že je starší než on. Sto let a řada mrtvých příbuzných a už ne tak mladému hochovi nezbyl nikdo jiný než on, jediný a nejlepší přítel, Anton.

Jen v prvním dni po setkání s Nomizkatem přitáhl k sobě Francesco až dvě stě komárů a dva hladové vlky. Cena za zahrávání s démony je nemalá.
** Odnož SQL aneb do Temné Říše                             :200:
Prvních čtyři sta let Francescova života je dokumentováno podrobně v jiných spisech. Pro shrnutí nejdůležitějších životních událostí vystačí toto:

Přelstěný a rozzlobený Francesco pátral tři stovky roků po adekvátním způsobu pomsty. Jeho nesmrtelnost mu vysloužila hojné úspěchy v armádě a kamkoli šel, Anton šel s ním. Jeho medúza se mu stala neodlučitelnou. Zbytky duše se k ní upínaly jako kdysi k jeho bratru. A Francesco di Řím pátral.

Průběhem jeho čtvrtého století se naskytla příležitost. Francesco se přidal do nově formujícího Mezinárodního Úřadu, konkrétně k Odnoži SQL, zaměřující se na ochranu Země před Temnou Říší.

Během následujících dekád stoupal v jejích řadách, až jeho proslovy o obraně útokem nashromáždily příznivce, a ke konci sedmdesátých let jako nově jmenovaný vůdce SQL vytáhl skrz Internet do Dark Webu a přímo do dimenze Amales Rhkalhan, kde mocnou válečnou kampaní porazil krále Nomizkata a nařídil jeho popravu, když tento odmítl nulovat vyřčená přání, a přivedl tak nechtěně vládu proslulého Zitoraka imperátora.

Francesco di Řím se pevně usadil na pozici generála, kde setrvává dodnes. Antona deponoval do bezpečí M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S., který slíbil nejvyšší ochranu. Dnešním čtenářům dojde historický význam faktu, že podle Mezinárodního Úřadu bylo nejbezpečnějším místem Der Weiderhohlle Flüsemschliessem.
** Nomádní ~[nebo kočovný, vyber si]~ časopis              :1100:

* COMMENT Blbosti
:export:
# ' Toggle smart quotes
# \n		newline = new paragraph
# f			Enable footnotes
# date		Doesn't include date
# timestamp Doesn't include any time/date active/inactive stamps
# |			Includes tables.
# <			Toggle inclusion of the creation time in the exported file
# H:3		Exports 3 leavels of headings. 4th and on are treated as lists.
# toc		Doesn't include table of contents.
# num:1		Includes numbers of headings only, if they are or the 1st order.
# d			Doesn't include drawers.
# ^			Toggle TeX-like syntax for sub- and superscripts. If you write ‘^:{}’, ‘a_{b}’ is interpreted, but the simple ‘a_b’ is left as it is.
# todo      Self-evident
#+OPTIONS: ':t \n:nil f:t date:nil <:nil |:t timestamp:nil H:nil toc:nil num:nil d:nil ^:t tags:nil todo:nil
---------------------------------------------------------------------------------------------------------------------------------------
#+STARTUP: fnadjust
# Sort and renumber footnotes as they are being made.
---------------------------------------------------------------------------------------------------------------------------------------
#+OPTIONS: author:nil creator:nil
# Doesn't include author's name
# Doesn't include creator (= firm)
:END:
:uvozovky:
(while (re-search-forward "\"" nil t)
	(backward-delete-char 1)
	(insert "„")
	(re-search-forward "\"")
	(backward-delete-char 1)
	(insert "“"))
:END:

* Poznámky

[fn:1] Které pravděpodobně požívá orálně, ale slyšel od kamaráda, že taková nitrožilní nafta stojí za to, a chtěl by ji zkusit.

[fn:2] Ostudná nicota je čirou náhodou jméno druhého nejslavnějšího alba kamenné (rockové) trpasličí skupiny Pebbles. Drželo se na žebříčku hit-no-dobře,-no (hitparáda je pro trpaslíky příliš optimistická) celých dvanáct let. Jejich nejúspěšnějším albem je dodnes prostě pojmenovaná Hloubka se světoznámým singlem /Dnes ráno přišla, lopatááá lopatááá./

[fn:3] Pozor! V trpasličí kultuře nejsou oni malí a my normální, ale my velcí a oni, podle filosofa Gorkina Kovaliny ze skupiny Lopata, bezejmennou, beztvarovou, velikost postrádající a čistě abstraktní kupou adimenzionálních lívanců.

[fn:4] Paní Záchelová si zřejmě potrpí na ironické tituly.

[fn:5] Dvaceti nejvýše postavenými kantory v /závodě/.

[fn:6] Poddimenze, pokud nevíte, je speciální dimenze, která působí jako velké moře ve kterém plavou ostatní, standardní dimenze v Říši. V našem případě se tedy jedná o poddimenzi Internetu obklopující dimenze jako Země a Středozem a Šrekovu bažinu. Toto je důležité, neboť z Internetu se lze dostat do všech ostatních dimenzí v Říši. Případná nebezpečí přicházející do Internetu tak ohrožují nás všechny.

[fn:7] Zemánková mi po shlédnutí zápisků nakázala připsat sem, že jde o nějakou svatou povinnost zbavit svět bla bla bla, neposlouchal jsem. Sotva jsem s tím začal, už mě to nudí. A Zemánková na mě křičí, že už sem si měl dávno přečíst naši Řádovou knihu kodexů.

[fn:8] Pisatel těchto poznámek nám laskavě poskytl přístup ke svému sešitu pro lepší ilustraci dění následujících týdnů. Zdraví své adoptivní rodiče v Pacifiku (byl odchován delfíny).

[fn:9] Vyslovuj I-ii-II-i-i-IIIII.

[fn:10] Kódové jméno.

[fn:11] Pro zajímavost, žijeme padesát kilometrů od nejbližšího lidského osídlení.

[fn:12] Kým asi jiným? I když Monte Karlos Někdeník založili nějací nosorožci, takže co já vím?

[fn:13] Světle a tmavě ultrafialová. No děkuji vám mnohokrát. To jste nám to ujasnili.

[fn:14] Mimochodem, tak se to píše. Martinismus uznává nepsané pravidlo, že co je „dobré“, to je se S, co je „zlé“ píšeme se Z. MartiniSmus, minimaliSmus (o tom mi proboha ani nemluvte), ale LysaciZmus a totiZmus.

[fn:15] Ačkoli, dodává autor, dle vědeckých zkoumání lze předpokládat, že to není nostalgií, ale neblahým efektem Francescových následných činů.
