# -*-eval: (setq-local org-footnote-section "Poznámky"); eval: (set-input-method "czech-qwerty"); eval: (set-register ?\' "“"); eval: (set-register ?\" "„");eval: (set-register ? "M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S."); eval: (set-register ? "■"); eval: (ispell-change-dictionary "czech"); eval: (flyspell-mode 1);-*-
:stuff:
<style:style style:name="InterviewSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="3" fo:column-gap="0.497cm">
<style:column style:rel-width="21845*" fo:start-indent="0cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style style:name="NormalSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="2" fo:column-gap="0.998cm">
<style:column style:rel-width="32767*" fo:start-indent="0cm" fo:end-indent="0.499cm"/>
<style:column style:rel-width="32768*" fo:start-indent="0.499cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style          style:name="EditorialSect"         style:family="section">
<style:section-properties                  text:dont-balance-text-columns="true"
style:editable="false">   <style:columns    fo:column-count="2">   <style:column
style:rel-width="3401*"      fo:start-indent="0cm"     fo:end-indent="0.499cm"/>
<style:column          style:rel-width="6237*"         fo:start-indent="0.499cm"
fo:end-indent="0cm"/>        </style:columns>        </style:section-properties><
/style:style>

# ' Toggle smart quotes
# \n		newline = new paragraph
# f			Enable footnotes
# date		Doesn't include date
# timestamp Doesn't include any time/date active/inactive stamps
# |			Includes tables.
# <			Toggle inclusion of the creation time in the exported file
# H:3		Exports 3 leavels of headings. 4th and on are treated as lists.
# toc		Doesn't include table of contents.
# num:1		Includes numbers of headings only, if they are or the 1st order.
# d			Doesn't include drawers.
# ^			Toggle TeX-like syntax for sub- and superscripts. If you write ‘^:{}’, ‘a_{b}’ is interpreted, but the simple ‘a_b’ is left as it is.
#+OPTIONS: ':t \n:t f:t date:nil <:nil |:t timestamp:nil H:nil toc:nil num:nil d:nil ^:t tags:nil
---------------------------------------------------------------------------------------------------------------------------------------
#+STARTUP: fnadjust
# Sort and renumber footnotes as they are being made.
---------------------------------------------------------------------------------------------------------------------------------------
#+OPTIONS: author:nil creator:nil
# Doesn't include author's name
# Doesn't include creator (= firm)
:END:
#+TITLE: MONTE KARLOS NĚKDENÍK
#+SUBTITLE: Hluboko podzemí

* 7/2020
Ročník XXVV

*Adresa redakce:* Karlosova 77, 000 03 Monte Carlo 4

*E-mail:* EmailNoReply@server.mok

*Zákaznická linka:* 0004 892 223 03E

*Šéfredaktor:* Alžběta Ašelová

*Manažer redakce:* Jiří b'Ačkora

*Zástupce šéfredaktora:* Hobbo Habán

*Fotograf:* Alexandra Dimitrij von Dieseldorf

*Grafická úprava:* Tara Kočí

*Obrazová redakce:* Honza Kůň

*Rozhovor:* Karlos Žebatý, Lubomír Lečko

*Móda:* Šlapeboso Elle'Gante

*Závodní ekonomie:* Financier Kovva-Lečný

*Kaňonskop:* 

*Celofán:* Ždibopych Blecháč

*Vydavatel:* Monte Karlos Inc. a. s.r.o. a spol©

*Brand manager:* Karlos Žebatý

*Sociální poradce:* Lightningh Danger

*Sociální podpora:* Anna Oleš

*Inzerce:* Many Hrabal

*E-shop:* nakupsisam.cz

*Tiskne:* individuálně

*Korespondent:* Knutt Überhochmann

*Špeh:* nevíme

*Seniorní bankomat:* Evžena Kulibrko

*Cestopis:* Áron Ponurý a Emanuel Bebeš

*Rozšiřují:* google.com
* Editorial                                                             :250:
Jako malá jsem si zapsala do deníčku „Bez ohledu na to, jak to bolí, nezoufej; život jde dál,“ když jsem přišla o svou první lásku. Byl to starší, zkušenější (někdo by řekl vyzrálejší), zahraniční, plísňový kus sýra. Snědla nám ho kočka.

Říkám vám o tom ze dvou důvodů. Jednak vám chci ukázat, jak chytré jsem byla dítě, a jednak vás nabádám k tomu, co jsem jako mladá žurnalistka v Etiopii měla potřebu sdělit sama sobě - nezoufejte, mí drazí přátelé.

Někdeník stále lituje ztrátu naší recenzentky Olšany Kupé. Bohužel, když nás opustila, vzala si s sebou i kus našeho studia, které muselo být pečlivě přestavěno. Náš protiradarový nátěr ještě není hotový v levém křídle studia - a nebude po nějakou dobu - ale události posledních dní nás nutí začít se zprávami ne zcela chráněni před zásahem nepřátelských, satelitem naváděných útoků.

Při slavnostním znovuotevření našeho studia, znovuzahájení tisku našeho časopisu a znovupřehodnocení našich zásad jsem se rozhodla učinit následujících pět kroků:

Zaprvé - zřídila jsem novou pravidelnou rubriku popisující ekonomii závodu o /nejvyššího vůdce všeho učitelstva/.

Zadruhé - najala jsem slavné cestovatelské duo Árona Ponurého a Emanuela Bebeše, aby pro Někdeník vytvořili speciální cestopisný seriál, ve kterém čtenářům ukážeme zajímavé turistické destinace Internetu.

Zatřetí - Čtenářům velmi vyhovoval dosavadní cyklus Kalos-čepice a nyní se mohou těšit i z nového fenoménu - Kaňonskopu, který přinese lidem do života trochu pořádku a jistoty.

Začtvrté - Spolková bankovní federace (viz Závodní ekonomika) požádala Někdeník o pomoc. Jejich nejzkušenější recenzent a italský plantážník Evžena Kulibrko poskytne lekce budoucím recenzentům, a to formou dopisů. Banky doufají, že tím zájem o tuto profesi zvýší.

Zároveň Monte Kalos odchytil záhadné zprávy plující vzduchem a po důkladné dešifraci jsem se rozhodla - sami zjistíte proč - je zde rovněž uvézt.

A zapáté - všem jsem se rozhodla říct, že bez ohledu na to, jak to bolí, jak zmatení jsme ze současných... zmatků, jak moc nám chybí naše milovaná recenzentka, kterou z očividných důvodů nemůžeme nahradit, bez ohledu na to všechno, život jde dál.

Nezoufejte.

Alžběta Ašelová, šéfredaktor
* Závodní ekonomie
** Hráči
 Ekonomie tohoto závodu je velmi zajímavá věc. Přesto jsem zaznamenal u svých kolegů v kanceláři, že kdykoli se snažím něco na ní vysvětlit, všichni - hlavě Bob - se jí straní. Proto, když paní šéfredaktorka přišla s návrhem obeznámit naše čtenáře, byl jsem přinejmenším překvapen. Přes protesty mých kolegů - hlavně Boba - jsem dostal za úkol „Popsat způsob, jakým Mezinárodní Úřad funguje srozumitelným a jednoduše stravitelným způsobem, ale hlavně proboha ne zdlouhavě, nikdo to po tobě nechce číst a zabíráš moc místa na stránce, zkrať to, zkrať to, /zkrať to/.“

 A to také udělám.

 Dnes se budeme zabývat hráči v tomto světovém kolotoči. Je jich jen šest a nejsou nijak složití na pochopení. Jejich vztahy, Obratnou finanční šipku, Mezinárodní symbiózu, Obchvat a podobné termíny probereme jindy. Sabina - i když hlavě Bob - mi říká, že často házím moc informací najednou.

*** Učitelé
 Očividná skupina. Jsou to kantoři přihlášení do /závodu/. Jejich cílem je dostat se do Arény a poté se dostat z ní. Patnáct jich vstoupí, podle počtu hlasů, které dostanou, jeden vystoupí a ten se stane vítězem. Velmi prosté, /Tomáši/! Víte, Tomáš v kanceláři to pořád nechápe.

*** M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S.
 Tato instituce by vám měla být dobře známá. Mezinárodní Úřad pro Úplnou a Asertivní Spolupráci Spojených Států Místních i Zahraničních za Účelem Světového Míru, Obchodu a Výměny Služeb je pořadatel /závodu o nejvyššího vůdce všeho učitelstva/. Jedná se o mezinárodní organizaci, jak je patrno z názvu, s mocí ustanovit tento post. Jejich životní sílou jsou daně vybírané z našeho dalšího hráče.

*** Spolková bankovní federace
 Toto je interkontinentální, intermorální, interdimenzionální sdružení banek, které jsou pod přímou legální kontrolou Úřadu. Jejich úlohou v /závodě/ podle Dohody o poskytnutém prostoru je uschovávat hlasy voličů získané při pravidelných volbách.

*** Voliči
 Voliči jsou početná skupina lidí kvalifikovaných k rozhodnutí, kdo bude a kdo nebude velet všemu učitelstvu světa. Jedná se o osoby z různorodých společenských tříd a chodeb, s různými příjmy a výdaji, věkem, temperamentem a rosným bodem. Jejich hlasy se sčítají v každém kole voleb a uchovávají se v jedné ze spolkových banek pod účtem jednoho z učitelů.

*** Sponzoři
 Sponzoři jsou poněkud odlišní od zbytku našich hráčů. Mí přátelé - hlavně Bob - si je stále pletou s Bankomaty, ke kterým se krátce dostanu. Sponzor je nezávislá movitá osoba bez práva volit v /závodě/, která má přímý zájem (ze všech možných důvodů, včetně hygienických) na vítězném učiteli. Poskytují finance slibným kantorům, které jsou pak použity jako fandy pro jejich kampaně a splátky bankám, ke kterým se vyjádřím jindy. Jeden sponzor může podporovat více učitelů, avšak v nejvyšších kruzích a čtvercích se touto praktikou opovrhuje. A jak ví sponzor, který kantor je slibný? Jsem rád, že se ptáte, na rozdíl od Boženy, kterou to nikdy nezajímalo.

*** Bankomati
 Bankomati jsou zaměstnanci spolkových banek, vystudovaní na Univerzitě v Luthadelu. Program recenzentů byl zahájen několik let před vyhlášením /závodu/, kdy pravděpodobně v souladu s Dohodou o poskytnutém prostoru Spolková bankovní federace dostala informace o jeho průběhu předem. Skoupila akcie Univerzity a začala trénovat novou vlnu politických recenzentů, kteří pracují jako „nezávislí“ pozorovatelé a hodnotitelé učitelů a přidělují jim skóre podle jejich schopností a slibnosti. Sponzoři jednají podle tohoto skóre a bankomati jsou tak nesmírně důležitou součástí fungování /závodu/.

 Proč platí spolkové banky za bankomaty? Inu, to je komplikovanější, než se může zdát.[fn:1] Banky poskytují prostor pro úschovu hlasů, ale vyžadují si za něj samozřejmě poplatky. Tyto poplatky jsou vyšší, čím větší je počet hlasů. M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. získává většinu svých financí (asi 67%) z daní z banek. Je proto v zájmu Federace, aby celý systém šlapal, protože to přináší hlasy, což jim přináší poplatky, a stejně tak je v zájmu Úřadu, aby hlasy přicházely do banek, protože z toho dostávají peníze. Tudíž jsou bankomati součástí Dohody a banky si za ně rády zaplatí.

 To je, k vaší nevýslovné radosti, pro dnešek vše. Já jdu na pivo se svými kolegy. Oni rádi chodí na pivo - hlavně Bob.
* Na vlnách Internetu
~Connection established~
** Google
_Já jsem Áron Ponurý._

*A já Emanuel Bebeš.*

_*A toto je /Na vlnách Internetu/.*_

_Vítejte u prvního dílu našeho cestopisu, kde já a Emanuel cestujeme po známých i neznámých končinách, hledáme, kde je nejlepší jídlo a obecně máme legraci._

*Dnes vás zavedeme do nedaleké země google.com, kam přijíždí lidé ze všech světů, aby si osvěžili paměť, našli nějaké ty informace, nebo se podívali na krásný obrázek dne.*

_Kdy sis naposledy osvěžil paměť, Emanueli?_

*No, Árone, víš, že nevím? Nějak si to nepamatuji.*

_*Ha ha ha ha ha.*_

_Takže google.com. Přijeli jsme teprve před hodinou a už mi někdo hlásí, že jsem si ještě nezařídil účet._

*Vidíme lidi u informačního okénka, kde se dožadují map vedoucí na jiná místa. Tam se zrovna někdo ptá na cestu do csfd.cz. Za námi slyším zmatené volání po mapě do seznam.cz. Jeden křičí přes druhého.*

_Nejvíc mi vadí tamta stará paní, co se ptá na cestu do google.com. To jsou dnes lidi, co, Emanueli?_

*To jsou, Árone. To jsou. Jak to funguje?*

_Přijdeš k jednomu okénku a zeptáš se na místo. Paní za přepážkou chvíli přehrabuje v indexu a pak před tebe hodí dva tisíce devět set osmdesát čtyři výsledků._

*Tolik?*

_Tolik. Ale většinou stejně hledáš hned ten první?_

*Proč se ta paní namáhá?*

_Těžko říct. Možná jí to baví._

*Nesmíme zapomenou, že google.com je vlastně taková křižovatka. Přijdete sem, rozhlédnete se a jste zase na cestě.*

_Je to tak. Z velkého náměstí vedou statisíce, možná miliony cest někam jinam a do modra oblečení policisté dirigují směr, kterým se cestující vydávají podél těchto tratí._

*Co kdybych se ale chtěl zdržet?*

_Máš štěstí, Emanueli. Vidíš tu kavárnu v rohu?_

*Ano. Zajímavé místo, založené před dvaceti devíti lety. Je tam nějak pusto.*

_To víš, google.com je dobrá věc, ale nikdo tu nechce trčet věčně._

*A co doprava? Jak se zdejší obyvatelé přepravují na takové vzdálenosti ze svých domovů?*

_Používají moderní dopravní systém Google Drive._

*Ano. Google Drive poskytuje rychlou a spolehlivou přepravu osob i zavazadel. Má rovněž dlouhodobou úschovnu pro důležité dokumenty.*

_Když mluvíš o dokumentech, zajdeme se podívat na zdejší poštu?_

*Proč ne, Árone?*

_Pošta gmail je velké místo - možná nejzaneprázděnější poštovní služba ve vesmíru._

*O miliony dopisů se starají cvičené opice v zelených stejnokrojích, posazené do kabin po vnitřní straně válcovité budovy. Spíš mrakodrapu. Potrubím jim přijede dopis od uživatele a vypadne na stůl před nimi. Opice si přečte adresu - jestli je jich víc, okopíruje dopis do patřičného množství - a sleze po kovových lanech do středu budovy.*

_Musí lézt pět set metrů, protože prostor, do kterého jsme s Emanuelem právě vešli, je skutečně obrovský._

*Ano. Opice pak lokalizuje příjemce a strčí dopis do příslušné přihrádky.*

_Zajímavé místo._

*Velmi. A dobré pracoviště. Opice dostávají banán za každých dvanáct tisíc dopisů, které roztřídí.*

_Tomu říkám zaměstnanecká prémie._

*A představ si, mají i placenou dovolenou. Musí na ní pracovat, protože dopisy nikdy nepřestanou chodit, ale mají volno.*

_Vskutku, kdo by nechtěl pracovat na takovém místě? Teď se s Emanuelem přesuneme k Archivu._

*Google.com má archiv?*

_Ano. Jedná se o největší shromaždiště informací na každého žijícího člověka na všech planetách. Mladí, staří, vysocí, nízcí, chytří, hloupí. Všichni jsou tady a mají své složky. Každá návštěva google.com se zaznamená do Velké knihy vyhledávání a malí Pidižvíci támhle nahoře v osmapadesátém patře postupně sestavují profily každého z nás._

*A když se jeden takový profil postaví, prodá ho vedení google.com kočovným překupníkům, kteří cestují po vodách internetu jako my dva, a donesou ho do vzdálených krajů.*

_Archiv je vysoká budova čtvercového tvaru a připomíná skříň. Vchod je v podzemí a nikdo neautorizovaný k němu nemá přístup._

*Je to nutné, Árone? Takto chránit Archiv?*

_Je, Emanueli. Čas od času navštíví google.com skupina nájezdníků z podsvětí. Síly Temného Webu, známého jako Dark Web, vždy číhají, kde je nejméně čekáme. Google.com může vypadat mírumilovně a blaze, ale kdyby se Starším Internetu nepodařilo udržet síly Temna od civilizovaného světa slušných občanů, chce google.com zajistit obranu svého Archivu vlastními prostředky._

*Platí proto po zuby ozbrojeným skřetům, kteří stojí v několika soustředných kruzích kolem budovy Archivu a nenechají nikoho projít. I tak k úspěšným nájezdům dochází.*

_Ano. Čas od času se prostě podaří prorazit všechny obranné linie a nájezdníci si odnesou velké množství dat._

*Je to vždy smutná záležitost. Ale někdo podezřívá už zmíněné kočovníky, že mají v daleké zemi Craigslist.org kontakty na Dark Web a informace jim prodané skončí v Temnotě také.*

_Bohužel._

*Bohužel. No ale my se s vámi pro dnešek loučíme.*

_Těšíme se na další setkání._

*Koupili jsme si mapu do facebook.com, odkud vám zase napíšeme, až se tam dostaneme.*

_Může to chvíli trvat. Cesta do facebook.com je přeplněná k prasknutí. Každopádně, rádi jsme s vámi mluvili._

*Byla to legrace.*

_*A Bytu zdar!*_

~Connection terminated~
* Závod
** Vývoj                                                                :400:
Začátkem podzimu přišla do M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. petice podepsaná všemi spolkovými bankami Spolkové bankovní federace. Přistála na stole Goliáše Oberprußera, vedoucího odnože OPF, starající se o finanční záležitosti Úřadu. Federace předložila neformální ultimátum v podobě zkažené zubní pasty, ve kterém jednoznačně vyjádřila nespokojenost se současným stavem /závodu/.

Od dopadení paní Rotreklové, která byla shledána vinnou a vyřazena ze závodu pro porušení jeho pravidel[fn:2], celý /závod/ stagnuje. Učitelé byli přechováváni ve svých komnatách v Der Weiderhohlle Flüsemschliessem a všechny volby, veřejné proslovy či kampaně byly pozastaveny na dobu neurčitou.

Federace není spokojená s nedostatkem příjmů z hlasů voličů, protože /závod/ byl Úřadem nuceně pozastaven, než jeho velké mozky vyřeší malý problém mizejících učitelů. Vzhledem k nutnosti Spolkové bankovní federace pro chod M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. apelovala odnož OPF na odnož QXM, která má za úkol starat se o veřejné mínění o Úřadu.

Se zastavenými volbami nepřichází nové hlasy do trezorů spolkových bank, učitelům tak nezvyšují poplatky za jejich přechovávání a Federace je velmi, velmi znepokojena.

Odnož QXM vydala prohlášení, že chce-li Úřad nadále zůstat aktivní, bude nutné opět zahájit koloběh politikaření mezi učiteli, začít opět vysílat pravidelné televizní pořady o jejich činnostech a všeobecně zvýšit popularitu závodu mezi diváky, kterých do té doby postupně ubývalo.

Úřad v rychlosti identifikoval původ svých dosavadních problémů - zákaz používání armád při získávání bodů vedl paní Rotreklovou, drženou v tajné podzemní vojenské základně /Omma Céb a la Sviña costa/, k adoptování agresivnějších postupů - a rozhodl se ignorovat četné hlasy zbytků sekty Nesplněné pomsty, že to pochopili úplně špatně.

Vznikl tak nový výkonný orgán /závodu/ - Rada odvážných. Rada odvážných se skládá z následujících členů:

- Dvacet statečných
- prvních 7 učitelů z pozic 21-1.000
- prvních 6 učitelů z pozic 1.001-2.000
- prvních 5 učitelů z pozic 2.001-3.000
- ...
- 0 učitelů z pozic 7.001-7.500

Rada odvážných má za úkol rozhodovat, zda jednání kantorů má podle nich být v souladu s pravidly /závodu/. Rozhodnou-li se, že ano, postoupí své rozhodnutí Úřadu, který pak rozhodne podle své vlastní vůle. Rozhodnou-li se, že ne, postoupí své rozhodnutí Úřadu, který se pak rozhodne dle své nevlastní vůle. Úřad neslibuje, že se bude řídit rozhodnutím Rady, ale zároveň neslibuje, že se jím řídit nebude.

S Radou takto zformovanou odnož QXM schválila rozjet závod znovu naplno.

Mezitím se paní Lajdové záhadným způsobem podařilo zvýšit své hlasy víc než dvakrát. Nikdo neví, jak to udělala, a není možné se jí zeptat, protože jakmile byla propuštěna ze svých komnat, zmizela z tváře světa a objevuje se jen jako hologram.

#+begin_example
1. Zdenka Lajdová
2. Dagmar Kolářová
3. Dana Kubešová
4. Ludmila Malá
5. Marta Křenková
6. Dušan Rychnovský
7. Věra Zemánková
8. Lenka Vývodová
9. Gustav Havell
10. Jiří Šeiner
11. Taťána Jakešová
12. Marie Vávrová
13. Hana Mužíková
14. Jana Horáková
15. Ivo Macháček
16. Jiří Lysák
17. Martina Hapalová
18. Elisie G’uaun Ebbe
19. Radovan Langer
20. Jan Menšíková
#+end_example
** Rozhovor
Pan Radovan Langer. První z unesených zlotřilou sektou Nesplněné pomsty. Původní vedoucí v žebříčku. Nyní se vrací, aby dohnal své zmeškané kampaně a ujal se vedení.

* Korespondent
* Lifestyle
** Karlos-čepice
Módní sekce Monte Karlos Někdeníku vám přináší výběrový sortiment na dlouhé horské treky.

Klasický styl Pod širákem přináší pohodlné spaní a bezbolestnou noc. Kdo vytáhne Pod širákem u ohýnku, značí stylistické vzdělání a čestné vyznání ke spravedlnosti.

Styl Žízeň se hodí pro mnohadenní cesty pralesy či vysokohorskými průsmyky. Poskytuje obranu proti větru na vrcholu hlavy a nádobu pro chytání deště v případě, že dojde pitná voda. Vhodný pro milovníky kabaretu.

Na druhou stranu Dešťovka nalezne zalíbení u těch, kteří mají vody dost, až možná příliš. Chytré zařízení dostupné na našem webu umožňuje naklonění čepice proti padajícím kapkám. Lze použít i jako ochranu před sluncem, ačkoli v tom případě doporučujeme sundat bundu.

A nakonec je tu Zimouš. Jednoduše pro ty, kteří nejsou spokojení jen s jednou pokrývkou hlavy. Jedná se o hlasitý módní postoj, avšak nikdo neví, co vlastně znamená. Doporučujeme nenosit.
* Šeiner
** Lekce bankomata
*** Lekce I.
Bankomati nejsou součástí /závodu/. To je důležité vědět, pokud uvažujete o připojení se do našich řad. První věc, kterou vás naučí v Luthadelské universitě, je jak nezasahovat do /závodu/. Fotografové divoké přírody mají zakázáno s ní interagovat. Když si tučňáci na Sibiři nebo kde to žijí všimnou fotografa a přiblíží se k němu, musí si hrát na kámen a nechat se oblézat, dokud neodejdou. My bankomati můžeme o takových opatřeních snít. V naší profesi musíme být nenápadnější než ninjové a tišší než list papíru spadnuvší na zem dvaadvacet kilometrů daleko ve snu mrtvého Indiána. Kdo není schopný dopracovat se do tohoto stupně poloviční neexistence zvané Neutrino, nedostane titul bankomata.

Ale zkuste to někomu vysvětlit.

"Nemám čas se o vás starat," řekl Šeiner. Stáli jsme v jeho sídle λl = ¾σf³, v laboratoři zdobené loveckými trofejemi a vycpanými hlavami slavných fyziků. Můj zaměstnavatel, Trojský Triumvirát - spojení tří banek se starořeckými motivy třech velkých filosofů - mě poslal, abych Šeinera sledovala na jeho cestách /závodem/, zaznamenala své poznatky shrnuté do několika lekcí a ty poté poslala do Monte Karlos Někdeníku, kde je vytisknou. Víte, v poslední době je nás bankomatů málo.

"Nechci žádnou ochranu," vysvětlovala jsem. "Ani pozornost, když jsme u toho. Budu jenom stát v pozadí a dělat si poznámky a ani o mně neuslyšíte."

"Budete stát v pozadí a dělat si poznámky? A co bude s těmi poznámkami?"

"Nechám je vytisknout v Monte Karlos Někdeníku," řekla jsem klidně. My bankomati jsem nabádání k věčnému a naprostému klidu, takže jsem si svého rostoucího rozhořčení ani nevšimla.

Šeiner zavrtěl hlavou. "To nemůžu dovolit. Můj život, moje poznámky, moje pozadí." Zamračil se. "Mám rozdělané nějaké projekty."

"Tím lépe. Budu mít, z čeho si ty poznámky dělat." Když začal znovu vrtět hlavou, dodala jsem: "Mezinárodní Úřad vám nařizuje, abyste mě nechal vás pozorovat." Předložila jsem příslušné dokumenty.

A tak se dostanete, kam chcete.
*** Lekce II.
Bankomati mají přidělených několik učitelů najednou. To je z několika důvodů. Je nás málo, to především. Studium na bankomata je těžké a mnoho uchazečů je posláno na manuální práci do nedalekých dolů Atia, protože nedokázali mentálně přestát celodenní pochodování po sutí zašpiněných chodnících[fn:3] a recitovat u toho pravidla našeho Kodexu. Mnoho dalších o této praktice slyší a odradí je to, než se k nám přidají.

Další důvod je ale ten, že když si nás naši svěřenci začnou všímat, máme se vzdálit do pozadí a nechat je na nás zase hezky pěkně zapomenout. Mezitím pracujeme na sledování dalšího našeho učitele.

Trojský Triumvirát mi přidělil jen Šeinera, abych měla čas sepisovat tyto lekce. Šeiner je velmi všímavý člověk. Má přítomnost byla konstantní. On si mě všiml. Já jsem byla v pytli.

"Budou hlasovat o používání armád," řekl Šeiner a navlékl si bílý chemický plášť. Já zabručela na souhlas. "Za dva týdny se máme sejít v Der Weiderhohlle Flüsemschliessem."

Bankomati mají být neviditelní, takže když na mě mluvil, znervózňoval mě.

"A dnes zapínají ten nový satelit," pokračoval Šeiner s rukou po loket v baňce s kyselinou. "To není dobrý nápad. Víte, jak jednoduché je nabourat se do něj?"

"Ne," řekla jsem jednoduše.

Šeiner smíchal jednu tekutinu s druhou a celá směs zčernala, zezelenala, zadýmala a začala zpívat /We Are the Champions/ od Queenů. "Strašně. Podržíte mi to?" Podržela jsem mu to. "V Der Weiderhohlle Flüsemschliessem si hacku hned všimnou, ale to už bude pozdě," pokračoval na cestě do temné kanceláře. Zapnul tam velmi slabé žluté světlo s luminesencí odpadního koše, které z jemných stínů udělalo stíny temné, a Šeinerovi se tak podařilo ztemnit místnost tím, že v ní rozsvítil.

Šeiner sáhl po kleštích a vytáhl z vody plastovou kartičku s jeho obličejem v rohu, která se marinovala v jakési chemické kaši. Vedle ní se marinovala druhá s mojí podobiznou.

Nezasahovat. Někdy je to těžší, než se zdá, když po vás váš učitel něco chce a nečeká na svolení.
*** Lekce III.
Další den jsme šli za trpaslíky.

Šeiner měl domluvenou schůzku s místním velitelem podzemní přepravy, aby spolu domluvili případné svobody v cestování poskytnuté jeho kampani. Poslouchat podobné rozhovory je denním chlebem, mlékem, sušenými datlemi, ovesnou kaší, zapečeným makarónem i španělským ptáčkem života bankomata. Věděla jsem, že je celou dobu plánuje oklamat a vloupat se do jejich interjaderního výtahu, ale nepřísluší mi - je mi /zakázáno/ - ovlivňovat plány učitelů. Má práce spočívá v hodnocená, jak jim ty plány vyšly.

Zalezli jsme spolu na záchod - trpaslíci mají jen jeden pro všech dvaadvacet pohlaví, protože všichni trpaslíci vypadají stejně - Šeiner vypálil připraveným elixírem díru do podlahy. Pod ním se objevila kontrolní místnost výtahu.

Tajná podzemní vojenská základna /Omma Céb a la Sviña costa/, pronajatá odnoží OPQ byla pod zemí na neznámém místě střežená trpasličími hlídkami a přístupná jen interjaderním výtahem. Šeiner použil zfalšované průkazy pro mě a pro sebe a naprogramoval jízdu.

"Proč s ní chcete smluvit?" zeptala jsem se někdy uprostřed jízdy. V kabině jsme byli sami, kolem ticho až na občasné dolní písně znějící zvenčí, jak jsme míjeli oblasti těžby. Ty ale ustaly před deseti minutami.

Musela jsem se zeptat - to proti Kodexu není. Musím přece vědět, co učitel dělá, abych ho mohla hodnotit.

"Úřad není, co by měl být," řekl zamyšleně. "Něco se děje. /Závod/ nefunguje, jak má. Musím se dozvědět, jak to doopravdy bylo, abych ho mohl změnit."

"Proč změnit? Se /závodem/ není nic špatně. Jestli vám nejde vyhrávat, je to vaše chyba. Nevidím důvod se šťourat v Úřadě."

"Problémy?" vysmíval se mi. "Ještě jsem se nesnížil pod dvacáté místo a chvíli jsem byl i úplně nahoře."

Dál jsme jeli mlčky. Nikdy se nehádejte se svým učitele.
*** Lekce IV.
S pomocí falešných dokladů nás Šeiner dostal do žaláře. Teprve tehdy jsme viděli první okno od chvíle, co jsme vstoupili do výtahu. /Omma Céb a la Sviña costa/ byla tak hluboko pod zemí, že stála na druhé straně planety, někde pod Indickým oceánem.

Není ale povinností bankomata stát a zírat na krásný, pestrý a barvitý podmořský život, takže jsem se šinula za Šeinerem až do neonem osvětleného vězení. Stráže nás opustili a kromě mé maličkosti, která se nikdy nepočítá, zůstal Šeiner sám s pouhou železnou mříží oddělující ho od Martiny Rotreklové.

"Co tu děláš, Jiří?" zeptala se skrz náhubek, který by vadil i doktoru Hannibalovi.

"Chci vědět, co se děje s Úřadem."

"Co by se dělo? A proč myslíš, že o tom něco vím?"

"Protože se to stalo tobě. Něco se děje se spolkovými bankami a ty víš co. Kam zmizely všechny tvoje hlasy, když tě vyřadili ze /závodu/, a proč se o ně nikdo nezajímá? Co měl být Čas pomsty a kde jsou jeho vojska teď?"

Čas pomsty měla být nějaká akce naplánovaná přítomnou ex-závodkyní a zesnulou paní Oslovou, hlavou Sekty nesplněné pomsty. Ale nakonec na nic nedošlo a většina členů sekty zmizela kdoví kam.

"Ty vůbec nevíš, o co tu jde."

"Vím, o /koho/. Před pár dny dostal tvůj přítel Daniel Pace dopis od politické recenzentky Monte Karlos Někdeníku. Ukázala mu tam, že Lajdová dostává hlasy z jiných účtů v bankách. Od jiných učitelů."

Rotreklová se zasmála. "To je na dlouho."
*** Lekce V.
Nic v životě netrvá dlouho, když vám někdo řekne, že to bude trvat dlouho. Tohle bylo ale zatraceně dlouhé.

Rotreklová řekla Šeinerovi o tom, co se stalo na začátku roku mezi ní a Lajdovou. Prý z kolegiality. Podle mě to někomu chtěla říct už dávno a byla ráda za tu výmluvu.

Lajdová prý od začátku /závodu/ chodila za určitými kantory a vyhrožovala jim. Používala psychologické taktiky zastrašování a ponižování, až jí slíbili část svých hlasů za to, že je nechá na pokoji. Ona ale přišla znovu. A znovu. A znovu.

Pálkovská se jí bála napadnout v Oranžové okupaci. Velká pětka se jí bála. A Lajdová se držela nad vodou i bez pořádné kampaně.

Když zmizela Vávrová z Der Weiderhohlle Flüsemschliessem, šla Lajdová jeden po druhém vyhrožovat učitelům v komplexu, dokud nedorazila na toho, kdo byl zodpovědný - na Rotreklovou. Zajistila si u ní stálý příjem hlasů za své mlčení.

Rotreklová následně vyhledala Daniela Pace a snažila se ze všech sil ho přesvědčit, že Lajdová je pachatel. Tak by se zbavila obou. Ale nepovedlo se a když ji vyřadili ze /závodu/, dorazily postupně všechny její hlasy k Lajdové do trezoru. Proto najednou získala tak velkou popularitu a sedí teď na vrcholu žebříčku. Šeiner zuřil.

Kdybych mohla něco říct, připomněla bych mu, že tohle je /závod/. Lajdová nedělal nic proti pravidlům. Ale úkol bankomata je sledovat, ne připomínat. Mlčela jsem. Mlčela jsem i ve chvíli, kdy jsem si všimla spěšných kroků v jedné z chodeb.

"A ta bomba?" zeptal se Šeiner. "V Monte Karlos?"

"Nevím," přiznala Rotreklová. "Buďto šla po Kupé, která přicházela na její zdroj hlasů, nebo po Oslové, která připravovala Čas pomsty - vojenský zásah proti ní."

Šeiner sklopil hlavu a přemýšlel. Když ji znovu zvedl, chtěl se ptát dál, ale rozezněl se alarm.
*** Lekde VI.
Když falšujete dokumenty, radši to udělejte pořádně. Žádné polovičaté, odbyté práce, které by prokoukl i dělník s nedokončeným základním vzděláním za svitu měsíce po hmatu.

Šeiner měl velmi dobré padělky.

Dovolte mi tedy se poopravit. Když falšujete dokumenty pro trpaslíky, nechte toho.

Šli po nás.

Já se nebála - mám imunitu v celém /závodě/, ale Šeiner byl v maléru. Vběhli jsme do čistírny s oknem vyhlížejícím na oceánské dno a zabarikádovali dveře skříní s vypranými trpasličími kroužkovými brněními. A pak nebylo, kam dál utíkat. Šeiner se rozhlížel, ale jediné, co našel, byl velký hrnec pro zaváření zmíněných brnění (teflonový, pěkně nelepivý) na elektrickém sporáku a špachtli.

Z chodby se ozvala veliká rána. Trpaslíci si na nás přinesli iontový kanón.

Najednou se ochladilo.
** Špeh
~Zaznamenáno špehujícími satelitními talíři Monte Karlos~

Cíl lokalizován 8.10. Následoval na schůzi s trpaslíky pod Sicílií. Cíl se pohybuje s partnerem bankomatem.

Cíl zmizel na záchodě. Pokračuji v hledání.

Cíl nalezen na trpasličích bezpečnostních kamerách. Pronikl do /Omma Céb a la Sviña costa/. Mluví s R.

Cíl objeven. Pátrání po neznámém vetřelci.

Cíl nalezen. Utíká. Zavřel se do prádelny bez možnosti úniku. Cíl zmatkuje. Trpaslíci vyrážejí dveře iontovým kanónem. Žádost o povolení narušit kabelový systém základny.

Ruším poslední žádost. Cíl se mění. Narovnal se a je klidnější, vyrovnanější a sebejistější. Rozhlíží se.

Cíl: Tohle mě má zastavit?!
Trpasličí strážník: Vyrazte ty dveře!
Cíl: Poslužte si.

Dveře drží za skříní. Magické vlastnosti trpasličích brnění zadržují iontové střely. Cíl se rozhlíží. Bankomat se třese zimou. Nemožno určit původ snížené teploty.

Cíl: Vyndejte ta brnění!
Bankomat: Proč?
Cíl: Protože! Hned. Pro každého dvacet.

Cíl se zamýšlí.

Cíl: Dvacet celých osm dva devět čtyři pět pět tři.
Bankomat: Co?
Cíl: Jinak budeme stoupat moc pomalu.

Cíl ignoruje zmateného bankomata. Popadl špachtli a začal sdírat teflonový povrch z vnitřní strany hrnců. Bankomat začal vyndavat a odpočítávat brnění ze skříně. Skříň se zakymácela pod palbou kanónu.

Strážník: Otevřete, ve jménu Thorinova vousu!
Cíl: Otevřete si sami!

Bankomat naskládal dva krát dvacet brnění na hromadu.

Cíl: Řekl jsem dvacet celých dva devět--
Bankomat: Jak je mám asi roztrhat?

Cíl je naštvaný. Vzal jedno brnění z každé hromady a pečlivě ho vyválel v sedřených pilinách z hrnce.

Bankomat: Co to děláte?
Cíl: Musíme se dostat nahoru.

Chvíli ticho. Skříň se zakymácela.

Bankomat: A?

Cíl položil obě brnění stranou a začal si navlékat na trup, nohy i hlavu zbylé drátěné košile.

Cíl: A teflon odpuzuje vodu.

Bankomat viděl, co cíl dělá, a napodobuje.

Bankomat: Jsme na dně oceánu. Jak chcete doplavat až na hladinu.

Cíl: Jak to říkal Bilbo? "Mithril. Lehký jako peří, pevný jako dračí srst," nebo tak nějak? Co je lehčí - peří, nebo voda?
Bankomat: Co? Ne!
Cíl: Ano.

Cíl navlékl přes devatenáct vrstev poslední brnění obalené v teflonu. Bankomat napodobuje.

Strážník: Otevřete, řekl jsem! Poslední šance!
Cíl (bankomatovi): Pomozte mi.

Spolu odsunou skříň na stranu, ale potichu.

Cíl (nahlas): Nikdy!
Strážník: Kdo jsi, zločinče?!

Trpaslíci se připraví pálit.

Cíl: Já jsem Albert Bílý! Střeste se před mou mocí!

Bankomat se podíval na cíl jako na vola. Její soud schvaluji.

Trpaslíci vypálili. Rána proletěla uvolněnými dveřmi a narazila do stěny na opačné straně místnosti. Síla střely prorazila stěnu podmořské základny a do prádelny začala pronikat voda.

Bezpečnostní pojistky na dveřích detekovaly průnik v plášti. Protipotopní dveře se zavřely a oddělily trpaslíky od cíle v ohromné vrstvě Mithrilových brnění. Cíl se hluboce nadechl a proklouzl dírou ve stěně. Bankomat zakroutil hlavou, její brnění zacinkalo tímto pohybem, a následoval ho ven.

Cíl stoupá na hladinu závratnou rychlostí. Vztlaková síla oceánu působí na Mithril podle očekávání, teflon drží největší přívaly vody od těla. Venkovní kamery zachycují obě osoby, jak se ztrácí mezi rybami na hladině. Přepojuji se na dálkové sledování a odposlouchávání, znemožňuji přístup trpasličím činitelům a maži cílovu podobu z databáze.

Cíl a bankomat vypluli na povrch. Cíl je v dobré kondici a zadržel dech dostatečně dlouho. Bankomat leží v brnění a nehýbá se.

Cíl: Madam? Madam Kulibrko?

Cíl se chová jako předtím. Jeho hlas je opět Šeinerův. Doporučuji prozkoumat cílův duševní stav.

Cíl: Madam!!

Bankomat se probral a vykašlává vodu.

Bankomat: Co to bylo?
Cíl: Únik.
Bankomat: Teď nás najdou na hladině!
Cíl: Ne. Trpaslíci neplavou. Za okamžik pro mě přiletí helikoptéra.

Za okamžik přiletěla helikoptéra. Opouštím podzemní Sicílii. Další zprávy přijdou, až cíl znovu lokalizuji.
* Poznámky

[fn:1] Tato věta z mého pera se bude některým velmi líbit - hlavně Bobovi.

[fn:2] Pro více detailů viz první přílohu tohoto čísla.

[fn:3] Luthadel je zvláštní místo.
