# -*-eval: (set-input-method "czech-qwerty"); eval: (setq-local org-footnote-section "Poznámky");-*-
:stuff:
#+STARTUP: fnadjust
------------------------------------------------------------------
#+OPTIONS: ::t
# Toggle fixed-width sections
------------------------------------------------------------------
#+OPTIONS: ':t
# Toggle smart quotes
------------------------------------------------------------------
#+OPTIONS: \n:t
# newline = new paragraph
------------------------------------------------------------------
#+OPTIONS: creator:nil
# Doesn't include creator (= firm)
------------------------------------------------------------------
#+OPTIONS: f:t
# Enable footnotes
------------------------------------------------------------------
#+OPTIONS: date:nil
# Doesn't include date
------------------------------------------------------------------
#+OPTIONS: author:nil
# Doesn't include author's name
------------------------------------------------------------------
#+OPTIONS: <:nil
# Doesn't include any time/date active/inactive stamps
------------------------------------------------------------------
#+OPTIONS: |:t
# Includes tables.
------------------------------------------------------------------
#+OPTIONS: timestamp:nil
# Toggle inclusion of the creation time in the exported file
------------------------------------------------------------------
#+OPTIONS: H:3
# Exports 3 leavels of headings. 4th and on are treated as lists.
------------------------------------------------------------------
#+OPTIONS: toc:nil
# Doesn't include table of contents.
------------------------------------------------------------------
#+OPTIONS: num:nil
# Includes numbers of headings only, if they are or the 1st order.
------------------------------------------------------------------
#+OPTIONS: d:nil
# Doesn't include drawers.
------------------------------------------------------------------
#+OPTIONS: ^:t
# Toggle TeX-like syntax for sub- and superscripts. If you write ‘^:{}’, ‘a_{b}’ is interpreted, but the simple ‘a_b’ is left as it is.
:END:
#+TITLE: MONTE KARLOS NĚKDENÍK
#+SUBTITLE: Závod začíná

* 23/2019
Ročník XXVIIII

*Adresa redakce:*
Karlosova 77, 000 03 Monte Carlo 4

*E-mail:*
EmailNoReply@server.mok

*Zákaznická linka:*
0004 892 223 03E

*Šéfredakdot:*
Alžběta Ašelová

*Manažer redakce:*
Jiří b'Ačkora

*Zástupce šéfredaktora:*
Hobbo Habán

*Fotograf:*
Alexandra Dimitrij von Dieseldorf

*Grafická úprava:*
Tara Kočí

*Obrazová redakce:*
Honza Kůň

*Rozhovor:*
Karlos Žebatý, Lubomír Lečko

*Editoři:*
Šimon Balabán, Andrew McTallas, Aráb a'Ráb

*Catering:*
Blanka MccEkeelee

*Vydavatel:*
Monte Karlos Inc. a. s.r.o. a spol©

*Brand manager:*
Karlos Žebatý

*Sociální poradce:*
Lightningh Danger

*Sociální podpora:*
Anna Oleš

*Inzerce:*
Many Hrabal

*E-shop:*
nakupsisam.cz

*Tiskne:*
individuálně

*Korespondent:*
Aleks Chalexch

*Rozšiřují:*
google.com

/Monte Karlos Někdeník/ byl založen skupinou černých nosorožců afrických v létě roku 1989. Jeho stránky byly poznamenány takovími autory jako Alexandr Malinovský, Jack O'Clock a Veronika Oškalová a všeobecnému ohlasu se těší již třetím rokem pod brilantním vedením šéfredaktorky Alžběty Ašelové©. Stojí na železobetonových základech, neboť všichni zaměstnanci od grafiků přes ediroty po prachbídné korespondenty se řídí všestranými, nesmrtelnými pravidly slušného chování.
* Editorial
:Problém:
Neopraveno!!
:END:
V politických kruzích se praví: „Lepší pozdě, než dříve.” Alžírský premiér Marid Litim toto rčení dotáhl do dokonalosti, když dodal „Obzvlášť pokud jde o volby.” Pokud mi světové vlády kdy daly záminku o jeho slovech pochybovat, řádně ji odčinily ve věci celosvětových voleb. Roli /nejvyššího vůdce všeho učitelstva/ už nám slibují roky a roky a nikde nic. 

Jak se v dnešním čísle dočtete, konečně se pochlapily a závod začal - fakt, který mě naplňuje smíšenými pocity. Na jednu stranu není pochyb o nutnosti tohoto postulátu, na druhou budeme v příštích kdo ví kolika letech vystavování přerostlým egům, do očí bijícím kampaním, protáhlým debatám a populistickému rozdávámí sladkostí na chodnících, o které, buďme upřímní, nikdo nestojí. Ve světle těchto předpovědí jsem se dohodla se svým přítelem Karlosem na revolučním systému pokrytí tohoto fenoménu. Revoluční paradoxně v tom smylu, že se vrátí k pravým, nefalšovaným hodnotám žurnalistiky druhé poloviny dvacáteho století - nestrannosti, objetivitě a veřejnému blahu.

K samotnému závodu se prozatím nehodlám vyjadřovat. Mnoho věcí se ještě může změnit a změní, ponechám si proto své vlastní komentáře na dobu jim příhodnější. Slibuji však, že od našeho časopisu, jako vždy, můžete očekávat ten nejprofesionálnější přístup.

V rozšiřující se kooperaci s naší televizní divizí vám nyní bude /Monte Karlos Někdeník/ přinášet rozhovor s hosty z /Monte Karlos/. Tuto sezónu se můžete těšít na Holywoodské celebrity, slavné zpěváky a režiséry, najde se i osamocený dřevorubec. Především se však připravte na rozsáhlá /interview/ s kandidáty na post /nejvyššího vůdce všeho učitelstva/. Karlos mi slíbil, že to bude senzace, a jestli se na něco můžeme spolehnout, je to Karlosovo slovo.

Mimo to nás svým dopisem poctil dlouholetý korespondet ze všeho východu Aleks Chalexch. K Aleksovi mám osobní vztah - pro /Monte Karlos Někdeník/ pracoval ještě, než jsem zde před šesti lety začala psát zprávy o politice v Etiopii. A jako obvykle se vytáhl. Ostatně jako my všichny. Já si to užila.

Doufám, že vy také.

Alžběta Ašelová, šefredaktorka
* Zprávy
  :PROPERTIES:
  :VISIBILITY: content
  :END:
** Šampión spadl po neúspěšném pokusu o kampaň
Chlapci a děvčata, milí žáci a žačky, je to tady. Úřady si daly na čas, ale po pouhých devíti letech, pěti senátorech, dvanácti světových peticích, dvou nominacích na Oskara, potopě, olympijském zlatu ve vaření a úplném vyhlazení lichožroutů jsme se konečně dočkali. Ano, světové volby /Nejvyššího vůdce všeho učitelstva/ konečně přišly!

Zápis byl otevřen v úterý 20. srpna a ještě ten den bylo možné spatřit rekordní účast. Web-stránka /Leaks-Pedia.org/ hlásí, že během několika hodin se div dveře /Mezinárodních Úřadů pro Úplnou a Asertivní Spolupráci Spojených Států Místních i Zahraničních za Účelem Světového Míru, Obchodu a Výměny Služeb/ (M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S.) po celém světě netrhly. Mezi prvními lze nalézt dvě stě třicet kantorů z jihočeského kraje, dvanáct soukromých učitelů ze spojených států, pětatřicet doučovatelů na volných nohách, šamana, voo-doo médium, dvě filmové postavy a jezevce.

S novou vlivnou pozicí přichází jako obvykle i řada žertovníků. Není tudíž divu, že kontroloři měli v posledních dnech plné ruce práce. Již během prvního týdne z uchazečů vyloučili paní Magdalenu Kobášovou kvůli podezření z nelegálního dávkování a maďarskou rockovou skupinu /Kchochch/ vedenou kilogramem uhlí. /Twitter/ aktivistka /Zuial Xcho/ příslušného kontrolora obvinila z rasizmu a #CoalsArePeopleToo trenduje již třetím dnem.

Závod se uchytil zejména v Latinské Americe. Venezuelská vláda svolala tiskovou konferenci a oznámila, že při jeho příležitosti dočasně přeruší inflační křivku a jednou pro změnu někoho zaměstná. Tamější deníky hlásí možnou spolupráci s Chile za účelem vybudování vůdcova sídla. Ekonom Erik McCkelly říká: "Pokud by se Chile a Venezuele podařilo [sídlo] postavit, zvýšilo by se jejich DPH až trojnásobně." Dále však podotýká, že třikrát nula je stále nula[fn:1].

Ačkoli uběhlo jen něco málo přes týden, viděli odborníci neobvyklý pohyb v horních příčkách kandidátských žebříčků. Pan Radovan Langer, původně na prvním místě, se po rozhovoru s Karlosem Žebatým v /Monte Karlos/ propadl o čtrnáct příček. Dlouholetý ředitel maloměstského gymnázia v Hranicích (na Moravě, kdybyste nevěděli, kde to je) se těšil brzkému úspěchu. Již dva dny po přihlášení (ještě v úterý) se vyšplhal do první stovky, o den později až na /první/ místo. Politický nadšenec Franta Ošela připisuje jeho úspěch nezvyklé popularitě mezi mladými žáky českého jazyka a literatury, varuje však před Langerovým příkladem.

"@RadovanLanger měl našlápnuto velmi vysoko. Někdo se mohl domnívat, že výsledky voleb byly již rozhodnuty. Jak se ale ukázalo, jeho naprostý nedostatek charisma ho zradil. Musíme si uvědomit, že v dnešní době je talent před kamerou stejně důležitý jako za kamerou, kde jak víme, nikdo nesmí stát. A pan Langer bohužel nepochopil, v jaké době se o tuto pozici uchází..." píše Ošela a pokračuje: "...Mladí lidé se nechtějí dívat na někoho, kdo je nedokáže zaujmout, nejlépe během první půl minuty. Nemohu se vyjádřit k politickým ani učitelským schopnostem pana Langera (konec konců do arény máme ještě daleko), co ale mohu s čistým svědomím zhodnotit, je jeho veřejné vystupování..."
A dále: "...Je zřejmé, že se na interview dostatečně nepřipravil - zpochybňoval statistická data své vlastní kampaně, zpochybňoval statistiku jako takovou a nemohl jsem se ubránit pocitu, že @RadovanLanger neměl v úmyslu se nijak přiblížit divákům pana Žebatého, spíše si jen zaskočit na pokec. LOL. #PromrhanáŠance #Charisma #DobřeTiTak."[fn:2]

S panem Ošelem se shoduje většina sociálních médií. Langerův pád však dává naděj jiným. Mnozí uchazeči ohlásili, že lidé jako on nemají v dnešním světě co dělat a že vítězství není zaručeno až do chvíle, kdy z arény odejde jediný vítěz. Pana Langera zatím na prvním místě vystřídal Ivo Macháček, těsně následovaný o druhé místo se dělící dvojicí Dušana Rychnovského (Gymnázium Hranice) a Elisie G'uaun Ebbe (Šromotovo).
** Small-town Funk
FBI vyšetřuje nezvyklou diváckou účast na každoročním koncertě americké kapely /Funky Funk/. V úterý 27. se sjelo přes tři tisíce fanoušků zmíněné metalové skupiny na otevřenou planinu poblíž městečka /Nenta Heights/ v Alabamě - nevídaná podívaná, která přitáhla pozornost místních úřadů a posléze vlády Spojených Států.

Agent Reilly na tiskové konferenci vysvětlil: "Před začátkem akce se prodalo tři tisíce sto dvacet čtyři vstupenek. Odborné statistiky naznačují, že téměř všichni se na koncert dostavili. Naše laboratoře nebyly schopné lokalizovat jediný podvrh či nezákonné jednání v jejich prodeji. Jak je jistě zřejmé, něco je v nepořádku." Na otázku novináře dále upřesňuje: "Tolik lidí /Funky Funk/ prostě rádo mít nemůže. Slyšeli jste je někdy hrát?"

Všichni hosté byli zadrženi a na rozkaz generála Howera ve Washingtonu D.C. setrvávají ve vazbě /Nenta Heightské/ věznice. Ačkoli jsou obyvatelé vděčni za rychlý policejní zásah, mnozí se obávají dlouhodobých následků. Starosta města v místním rozhlase vyjádřil nespokojenost se způsobem, jakým bylo s vězni naloženo. Dle jeho slov "nemá /Nenta Heights/ dostatek čtverečních metrů." Bližší zkoumání jeho výroku přineslo poznatek, že vězni nyní početně převyšují tamější policejní sbor, farmářské sdružení, accapella skupinu, rolníky, řezníky, prodavače, jejich děti a manželky[fn:3] v poměru pět ku jedné.

Nezvyklá situace však městu přinesla neočekávané benefity. Turistický ruch se zvýšil osmnáctkrát jen v průběhu jednoho dne, jak se do věznice valí matky s dětmi z celých Spojených Států za svými příbuznými, a manželé Riddleyovi využili vyvstanuvších zásobovacích problémů a založili přepravní firmu /Riddley a spol., do vězení a ven; jen za jeden den/, první soukromý podnik v okruhu padesáti kilometrů za poslední tisíciletí.

/Monte Karlos Někdenník/ bude situaci podrobně sledovat a přinese zprávy o aktuálním vývoji.
** Žalovníček žaluje
Ukrajinské soudy měly tento měsíc napilno. Kauza Ruda versus lid, na kterou byla již nasazena polovina ukrajinského policejního sboru, přinesla nový vývoj a v očích nejvyššího evropského soudce Ištvána Hubla si vysloužila titul nejsložitějšího soudního sporu století.

Vše začalo třetího srpna, kdy pan Ihor Ruda podal žalobu na mezinárodní korporaci /Amazon/ ve svém lokálním soudním okruhu. Předmět obvinění byl prostý - pan Ruda si téhož dne objednal expresní doručení bavlněných ponožek a připlatil si za doručení dronem. Následně však na svou objednávku zapomněl, a byl tudíž doveden na hranici infarktu[fn:4] při pohledu na "létající stvoření neurčitých tvarů a nepřirozených pohybů," které mu přistálo na trávníku, upustilo balíček, čímž poškodilo záhon lilií, a bez omluvy odletělo. Pan Ruda žádal odškodnění ve výši v přepočtu dvou seti tisíc korun, za zrušení poplatku za drona, expresní doručení a ponožky.

O týden později přišlo do oblastního soudu v Odesse upozornění na nezákonně nakládajícího občana - /Amazon/ podal žalobu na pana Ihora na základě statistik provedených firmou /Cambridge Analytica/ jasně ukazujících, že jeho jednání odrazovalo zákazníky /Amazonu/. Původní soudní spor byl pozastaven za účelem rozřešení, zda je jeho dokončení v souladu či rozporu s mezinárodním právem. Po panu Ihoru Rudovi vyžaduje doručovací společnost náhradu ve výši /Empire State Building/ (pokud možno v dvacetidolarovkách) a pan Ruda si najal advokáta Alexova se slibem, že až vyhraje, bude mít peněz jako, cituji, těles.

Trable však nekončily. Necelých pět dní po takzvané /Amazonské pomstě/ podal Odessovský soud na /Amazon/ žalobu nejvyššímu soudu s obviněním, že je nutí zabývat se "takovýma blbostma."[fn:5] Hned následující den podal pan Ruda u nejvyššího správního soudu žalobu na Odessovský soud za zbytečné zdržování, neboť jeho původní spor byl stále pozastaven a jeho nový spor se tímto pozastavil rovněž.

V následujících dvou týdnech se situace poněkud zklidnila, jak je vidno z pouhých třech nedůležitých obvinění na městské úrovni, z nichž se do soudní síně dostalo jen jedno - manželka pana Rudy byla liberálními médii označena za neschopnou výchovy a ukrajinské sociální služby odpověděly žádostí o odebrání jejího manžela do státní péče. Paní Rudová se brání certifikátem první pomoci z třetí třídy základní školy jako formálním důkazem o charakteru.

K novému vývoji v celé rozepři došlo až 31. srpna, kdy nezávislé internetové noviny /Rčečko/ podaly žalobu k ústavnímu soudu na pana Rudu, /Amazon/ a ukrajinský soudní systém, neboť ve čtrnácti dnech od páně Rudovy žaloby proti Odessovskému soudu u nejvyššího správního soudu k žádnému vývoji nedošlo, nebylo tedy o čem psát - fakt, který šéfredaktor /Rčečka/ Yaroslav Velychko označil za porušení listiny základních práv a svobod, článku 17, t.j. svobody slova.
* Rozhovor
  :PROPERTIES:
  :VISIBILITY: content
  :END:
Pan Radovan Langer - ředitel uznávaného gymnázia na střední Moravě, otec blíže neurčitého počtu dětí a uchazeč o místo nejvyššího vůdce všeho učitelstva. Pan Langer je vášnivý malíř, cestovatel a kuřák. /Monte Karlos/ ho pozval na rozhovor po raketovém výstupu na nejvyšší kandidátní příčku.

*Jak dlouho už pracujete jako ředitel?*

No, to už bude nějakých 35 roků.

*Co jste za tu dobu musel obětovat, abyste si tu pozici udržel?*

Já bych řekl, že, když se nad tím zamyslím, nemluvil bych o nějakých obětech. Já jsem na té pozici poměrně velice spokojený.

*Vy také učíte, že? Češtinu.*

Ano, jako ředitel taky musím čas od času vyučovat.

*Jaký je váš vztah s žáky. Jste mezi nimi oblíbený?*

Tak, to chcete, abych se takhle hodnotil.

*Skoro i jo.*

Sebereflexe je dobrá, ale tady bych řekl, že to není úplně na místě. Myslím si, že pokud trochu víte jak to dnes ve školství vypadá,
 myslím, že na to nakolik je těžké se žákům zavděčit jsem na tom poměrně dobře.

*Jakožto ředitel se musíte potkávat a být v úzkém kontaktu s učiteli. Jak to vypadá s nimi? Jaký máte vztah s učiteli na své škole?*

No, já jsem s kantory poměrně spokojený.

/Poměrně/ *spokojený. To je důležité. Dostali jsme anonymní zprávy, že ve vaší škole máte smlouvu s jistým panem Ivem ohledně nástupnictví na trůn. Můžete se k tomu nějak vyjádřit?*

Narážíte patrně na pana zástupce. Chcete tím naznačit, že už jsem ve funkci dlouho?

*To ani ne. Můžete na to klidně odpovědět.*

Vzhledem k tomu, jak zástupce pracuje a že jeho spolupráce s ředitelem je poměrně úzká, tak je celkem logické, že jako první uvažovaný
 člověk je právě ten zástupce.

*Takže vy na tom nevidíte nic zvláštního?*

Ne, myslím, že to je běžná praxe na více školách. Zástupce, který je dobře obeznámený s funkcí ředitele následně funkci ředitele
 vykonává.

*Já bych se nyní s dovolením přesunul do vašeho osobnějšího života. Vy rád cestujete, že?*

Ano.

*Co je vaše nejoblíbenější místo, kam jste kdy vycestoval?*

Tak, mám nějaké přítele v Amsterodamu v Holandsku. Tam rád jezdívám.

*Měříte své zahraniční cesty a jejich vzdálenost na hrnky kafe?*

Popravdě nevím, na co narážíte.

*Já na nic, ale vy často narážíte na ty hrnky.*

No, jestli vám připadá, že piji během svých cest...

*Mám takové informace.*

Za prvé by mě zajímalo, odkud takovéto informace...

*Žurnalistika. Žurnalistika, pane Langer. Žurnalistika. Máme své zdroje.*

Velice nepříjemné. S tím by se mělo něco dělat.

*Mám to brát jako slib v případě, že byste byl zvolen nejvyšším vůdcem všeho učitelstva, že se s žurnalistikou musí něco dělat?*

No neee, to samozřejmě. Je spousta věcí, se kterými by se mělo něco dělat.

A k té kávě, já si myslím, že každý pije jiné množství kávy. Předpokládám, že spousta lidí nepije žádnou a potom jim to může připadat hodně. Chci tím říct, že pro každého je velké množství něco jiného; je to dost relativní pojem. Takže možná, že piji víc kávy, než jiným připadá běžné, ale rozhodně si nemyslím, že by bylo nutné se nad tím pozastavovat. Nicméně, když o tom mluvíte, neměl byste nějakou kávu?

*Kolik hrnků kafe je to do Londýna?*

Tam jsem dlouho nebyl. Když se nad tím zamyslím, záleží na tom, jak jedu. Samozřejmě, pokud člověk jede taxíkem, tak je to příjemné a
 rychlé; sice trošku dražší, ale tolik kávy nevypiji. Někdy si i trochu prospím.

*Tak namátkou, třeba.*

No, pamatuji si, že kdysi jsem jel do Holandska se školou. A to jsme hodně zastavovali tak jsem si nějakou tu kávu dal. To mohlo být
 poměrně více káv, možná tak deset za tu cestu.

*Ano, přiměřené množství.*

*Zmínil jste, že pracujete v umělecké branži. Jak dlouho vám trvá nakreslit obraz?*

Zajímavá otázka, ale hůře se na ní odpovídá. Je vidět, že nemáte představu o tom, jak taková tvorba probíhá.

*Já jsem žurnalista, že, ne umělec.*

To se nedá říct. Podívejte, já tvořím pro radost. Peněz mám dost, mám zaměstnání, takže pro mě je to koníček. A když tvoříte, tak
 nehledíte na čas. Věci děláte, protože vás to baví. Tady je těžké mluvit, kolik děláte času. Já si to neměřím.

*Dobře. Napíšeme šest hodin.*

Prosím?

*Napíšeme šest hodin a jdeme dál. Co s tím obrazem potom děláte, když už jste ho nakreslil.*

No, jak jsem zmínil, mám nějaké přátele v Holandsku, takže s nimi vystavujeme, popřípadě vystavuji tady v Česku. Někdy sám. Myslím, že
 pro toho umělce je to takový způsob jak tu práci nejlépe ocenit. To, že ji může ukázat.

*Stalo se vám někdy, že byste poškodil plátno kvůli nedopalku z cigarety?*

Já jsem ve věku, kdy je dobré si trochu užívat života.

*Někdo by namítl, že užívaní si života tím, že se zkracuje, není efektivní, ale je to váš život, že?*

To záleží na přístupu. Já si zase říkám, že si budu užívat, protože nevím, kolik času ještě mám. Můžete si život šetřit a prodlužovat
 a celou dobu nedělat nic zajímavého, nebo si ho můžete užít. Stejně nevíte, kolik máte času.

*My jsme zde u nás v Monte Karlu našli jeden váš obraz, který bych nejlépe popsal jako portrét rýže. Jak dlouho vám trval nakreslit právě tento obraz?*

Jak dlouho trvá nakreslit takovýto obraz? No, předem je nutné si uvědomit, že nejde o kreslení. Je dobré si uvědomit, že ta technika
 je o něco jiná a řekl bych, že tady je důležitý ten tvůrčí proces. I to, že takovéto obrazy většinou nevzniknou na první pokus.

*Kolik rýže jste takhle rozsypal, než se vám podařilo najít ten správný obraz?*

Myslíte si snad, že je škoda té rýže?

*Já ne, ale někdo v Indii by možná mohl.*

Podívejte se, to je jestli si dám na večeři misku rýže, nebo jestli ji použiji jako umělecké dílo... Je to mnohem lepší, než kdybych
 používal něco jiného. Na to také nemůžete hledět - všechny barvy jsou jedovaté. O tom s vámi snad ani nechci diskutovat. O nějakých logických tématech. To moc neuznávám.
Ale co se takového díla týče, mě jde spíš o tu relaxaci. Při té tvorbě...

*Ať na to padne, kolik na to padne rýže.*
Na to dílo nebylo potřeba velké množství rýže. Navíc, ta rýže se dá použít znovu. Když jednou uschne, můžu ji použít dokola. O rýži
 nemám zájem více se bavit.

*Co je vaším nejoblíbenějším subjektem?*

Nechci být hrubý, ale zdá se mi, že je tady znatelné, že nerozumíte tomu, na co se ptáte.

*To vadí?*

Asi se těžko dá říct, že mám oblíbený subjekt. Jak můžete vidět, ať už je to ta rýže nebo jiná díla, která dělám v poslední době, tak
 spíše dělám abstraktní díla. Určit nějaký oblíbený subjekt je poměrně těžké.

*Dobře. Poslední otázku, když už jste tu rýži přinesl zpátky, vy říkáte, že až uschne, tak ji použijete znova. Časem určitě bude nepoužitelná. Jaký je ve vaší domácnosti poločas rozpadu rýže?*

Víte, mě by zajímalo, jestli svými otázkami něco sledujete.

*Já něco sleduji, ale vy na to nepřijdete.*

V tom případě, o poločasu rozpadu rýže nevím, obávám se, zhola nic.
*** Random otázka dne
*Kolik slepicí je potřeba k přeprání slona?*

 Já bych řekl, že záleží na tom, jak zdatné jsou ty slepice a jak starý je ten slon.

*Můžete nám dát nějaké rozmezí?*

Pokud má ten slon aspoň tři tuny, tak těch slepicí stačí deset.
*** Kampaň
*Jste velice populární mezi mladými studenty českého jazyka. Proč si myslíte, že tomu tak je?*

To by mě zajímalo, na čem zakládáte takovou otázku.

*Statistiky, statistiky.*

Asi v tom hraje roli, že já třídy nemusím připravovat k maturitě, takže já se snažím ty hodiny vést tak, aby vedly spíše k tomu
 porozumění k věcem. Někdy je dost těžké pobavit se s dětmi. Dnešní mládež se moc bavit nechce. Ale řekl bych, že moje výuka je taková volnější.

Ten, kdo je potom dostane, už si je řádně vede podle svých představ k maturitě. Já se snažím spíš o takový vhled do toho, jak ta problematika vypadá, než že bych zakládal na znalostech, které jsou k maturitě potřeba.

*Jakou strategii hodláte v aréně použít proti svým soupeřům?*
Je to docela boj na slepo. Já si myslím, že ze začátku je dobré vyčkávat. Uvidíme, čas ukáže.

*Proč by měli lidé podpořit někoho ve vaší fyzické kondici, specificky na tak náročnou práci jako vůdce učitelstva?*

Já si nemyslím, že na takovouto pozici je potřeba fyzická kondice. To si myslím, že je to irelevantní.

*Pan Ivo Macháček je v současné době vaším největším a nejnebezpečnějším soupeřem. Vy jste v žebříku na nejvyšším místě. Je něco, co byste nám o něm chtěl říct před vstupem do arény?*

Já bych jenom řekl, že je to velmi dobrý kolega.

*Můžeme čekat nějakou alianci mezi vámi dvěma? Aspoň dočasně?*

Já si myslím, že on má spolupráce se mnou dostatek v poli profesním.

*Co hodláte přinést světu jako vůdce učitelstva?*

Já bych řekl, že je třeba přistupovat k učitelství s klidem.

*Takže "relaxujte."*

Podívejte se, jak kantoři v dnešní době stresují studenty. Vedou je k dobrým výsledkům. Myslím, že ze strany těch studentů by mnohdy
 bylo potřeba nadšení a zájem. Výuka v dnešní době tíhne k mechanickému učení.

*Je to tedy váš cíl, byl-li byste zvolen?*

Já bych řekl, že ano.

*Co by byla ta první věc, kterou změníte na současném režimu?*

Víte, já jsem poměrně spokojený.
*** Rychlá střelba[fn:6]
*Kdy jste začal kouřit?*

Kouřil jsem už když jsem byl mladý, to jsem to zkoušel--

*Kdy skončí svět?*

Těžko říct. To nikdo neví.

*Kolik cigaret dokážete vykouřit naráz?*

Naráz? Myslíte, že kouřím cigarety naráz. Já kouřím spíše doutníky.

*Jste muž?*

Ano.

*Správná odpověď je "ne," protože to není v textu.*

*Pokud R. Langer vykouří dvacet cigaret denně a Macháček zapomene zavřít dveře do ředitelny, kolik cigaret neúmyslně vykouří Vlčková?*

Já si myslím, že pasivní kouření se zbytečně přehání. 

*Doplňte následující věty:*

*1. Moje škola je*

Tradiční.

*2. Nejraději mám*

Kávu.

*3. Učitelé mě*

Neobtěžují.

*4. Macháček je*

Můj dobrý kolega.
*** Korespondence
Do /Monte Karla/ nám došel dopis od Elišky Oslové:

Pane řediteli,

Možná si na mě nevzpomínáte. Před osmi lety jsem maturovala ve vaší škole, třída 4.B. Když jsem se doslechla, že kandidujete na vůdce učitelstva, nemohla jsem uvěřit svým uším. Vy a vůdce? Nevím jak vy, ale já si živě pamatuji ten den, kdy jste přišel do třídy a  představil jste se nám.

Píši vám s jednou jednoduchou otázkou: Jak dlouho si myslíte, že vás před námi vaše pozice uchrání? Jistě ne věčně...

S pozdravem,
Eliška Oslová, generální ředitelka ústavu pro duševně neschopné a kultovní hlava Sekty nesplněné pomsty

 *Odpovíte?*

 Já bych Elišce vzkázal, že škola je mnohdy větší blázinec, než ústav, ve kterém pracuje. Takže by to možná byla příjemná změna.
*** Závěrečný proslov
*Kdybych vám ukázal člověka, který vás nepodporuje, a by byste ho měl přilákat na svojí stranu krátkým proslovem, jaký by ten proslov byl?*

 Jaký by ten proslov byl? Měl by být přesvědčivý, krátký, výstižný, vtipný... Asi takový.
* Korespondent
_Volby v Mas´Er-ati._

/Od našeho nestálého korespondenta na Předním, Středním, Zadním, Blízkém, Dálném, Horním a Dolním východě/

V nejbizarnější a nejzáhadnější zemi Blízkého východu, Odpojeném arabském emirátu Mas´Er-ati abd al-Džamal ha-Mámí Habdí is´Ídí Qúrí Abdul-Í, proběhne v polovině příštího týdne zcela jedinečná politická událost – nesvobodné nepřímé nerovné demokratické volby, které se v tomto státě konají vždy jednou za sto dvacet let. 

Systém mas´Er-atských voleb je ve světě vskutku raritní, Mas´Er-aťané však ústy svého státního mluvčího prohlašují, že je to systém dokonalý. A mají ke svému tvrzení mnoho dobrých důvodů. Jejich prvním, nikoli však nejdůležitějším argumentem je suma absolutního i relativního bohatství, které tento orientální ministáteček produkuje v objektivizovaném přepočtu na jednoho svého obyvatele. Zahraniční pozorovatelé a kritici mas´Er-atského systému ovšem tato vyjádření mírní, ne-li přímo zpochybňují jako „těžko verifikovatelné“ s poukazem na „obtížně přijatelný“ fakt, že takzvaný státní mluvčí je zároveň mas´Er-atským emírem, přičemž je dobré mít na paměti, že emír Al-Fieri Er´Ne-es To je v Mas´Er-ati nedotknutelný, nesesaditelný, neodpovědný, nestíhatelný, nežalovatelný, nesouditelný a neodsouditelný, nekontrolovatelný, nehodnotitelný a nekritizovatelný. Někteří pozorovatelé dodávají, že emír je podle všeho zřejmě i nesmrtelný, pro méně radikální je přinejmenším neviditelný. Obě skupiny přitom jen různě vykládají skutečnost, že emíra už sto devatenáct let nikdo na vlastní oči neviděl ani ho neslyšel: posledních deset let komunikuje se světem výhradně prostřednictvím svého twiterového účtu;  předtím (od roku 1950) vydával jeho palác tiskové zprávy, zatímco celou první polovinu 20. století nekomunikoval vůbec s tím, že emír potřebuje klid na práci, kterou odvádí výhradně pro blaho lidu emirátu, a že lid emirátu je prokazatelně blažen, neboť to uvádějí výstupy Nejvyššího statistického úřadu emirátu Mas´Er-ati, a lid, který je blažen, po svém emírovi již nic jiného nežádá, natož tiskové zprávy – které by navíc emíra od práce zdržovaly. Tuto takzvanou Al-Fieriho doktrínu sice několik politologů zpochybnilo poukazem na skutečnost, že emír je předsedou Nejvyššího statistického úřadu emirátu Mas´er-ati, což by mohlo hodnotu výstupů tohoto úřadu poněkud problematizovat, státní mluvčí emirátu se nicméně proti takovým lžím vždy ostře ohradil s tím, že hodnotit nehodnotitelnou osobu emíra je nepřípustné, nepřijatelné, neakceptovatelné, nechutné, neetické, nemorální, nemravné, stupidní a blbé.  

Právě nepřehledná situace vede v posledku některé kritiky režimu k úvahám, že emír Al-Fieri Er´Ne-es To vůbec neexistuje; sami Mas´Er-aťané však proti takovým nepodloženým zprávám důrazně protestují formou petic, otevřených dopisů, deklarací a masových demonstrací s odkazem na skutečnost, že Al-Fieri byl řádně zvolen v posledních volbách a že zpochybňování jeho existence je zpochybňováním výsledku demokratických voleb, což je nepřípustné, nepřijatelné, neakceptovatelné, nechutné, neetické, nemorální, nemravné, stupidní a blbé. V poslední twiterové zprávě emirát ústy svého mluvčího žádá, aby každý, kdo tvrdí, že emír neexistuje, své tvrzení dokázal.

Bez ohledu na osobu emíra Al-Fieriho, výše vzpomenutý Nejvyšší statistický úřad emirátu dodává na svých webových stránkách řadu výstupů, které podporují mas´Er-atskou tezi, že jejich emirát patří v mnoha směrech ke světové špičce. Matematický ústav Akademie přípustných věd emirátu Mas´Er-ati, který pro Nejvyšší statistický úřad zpracovává potřebné odborné analýzy, prokázal, že emirát je nezpochybnitelně nejbohatším státem světa. Bohatství emirátu je založeno na tzv. pokrokové doktríně sdílení, tak jak ji zakotvuje pozoruhodná Ústava emirátu, která ve své preambuli na prvním místě říká a prohlašuje, že „v emirátu Mas´Er-ati jsou si všichni rovni“ a „lid emirátu a jeho emír jedno jsou“. V hlavě jedna téhož dokumentu pak vyhlašuje revoluční tezi „vše je všech“. Všichni Mas´Er-aťané tak sdílejí veškeré své osobní bohatství se svým emírem, s nímž podle dikce ústavy tvoří jednot(k)u, a emír je tudíž jediným držitelem 100% bohatství celého emirátu. Dlužno dodat, že v Mas´Er-ati neexistuje jiné než soukromé vlastnictví. To činí z emíra Al-Feriho suverénně nejbohatšího muže planety, neboť na světě není jiný stát, v němž by jeden člověk vlastnil 100% jeho bohatství. Neubírá to přitom na bohatosti všech obyčejných obyvatel emirátu, kteří na základě pokrokové doktríny sdílení disponují stejným objemem bohatství jako jejich emír. V desetimilionovém emirátě tak dosahuje celkový úhrn státního bohatství úctyhodnou 1 000 000 000%. Není divu, že státní mluvčí v minulosti několikrát navrhl tvůrce pokrokové doktríny sdílení, emíra Al-Fieriho, na Nobelovu cenu za ekonomii. Byl však odmítnut s odůvodněním, že Matematický ústav APV EM nepodal vědecké důkazy platnosti doktríny a že objektivitu práce ústavu zpochybňuje fakt, že emír Al-Fieri je jejím šéfem, což je ve světě nebývalé a „budí to určité pochybnosti“. Proti tomu se prostřednictvím svého mluvčího vymezil sám emír Al-Fieri s tím, že je to politováníhodné zasahování do vnitřních záležitostí země a hrubá urážka morální integrity lidu emirátu, kteří se svým emírem tvoří nerozbornou jednot(k)u,  zatímco státní mluvčí konstatoval, že takové hodnocení od třetího subjektu, který se „rád vidí jako nezávislý“ je nepřípustné, nepřijatelné, neakceptovatelné, nechutné, neetické, nemorální, nemravné, stupidní a blbé, a vyzval na svém twiterovém účtu každého, kdo s tím nesouhlasí, aby to dokázal.

Pokračování příště
* Poznámky

[fn:1] Matematik Adam West je otevřen filozofickým debatám na toto téma.

[fn:2] https://twitter.com/Ošela_Hošela?lang=cz

[fn:3] Tedy, slovy pana starosty, "úplně všechny."

[fn:4] Jeho slova

[fn:5] Řekl pan Buhaj, advokát najatý oblastním soudem na tiskové konferenci v Kyjevu.

[fn:6] Tazatel položí otázku. Tazač má sedm vteřin na odpověď. Po sedmi vteřinách se tazatel přesune na další otázku a tazač ztrácí možnost odpovědi.
