# -*-eval: (setq-local org-footnote-section "Poznámky"); eval: (set-input-method "czech-qwerty"); eval: (set-register ?\' "“"); eval: (set-register ?\" "„");eval: (set-register ? "M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S."); eval: (set-register ? "■"); eval: (ispell-change-dictionary "czech"); eval: (flyspell-mode 1);-*-
:stuff:
<style:style style:name="InterviewSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="3" fo:column-gap="0.497cm">
<style:column style:rel-width="21845*" fo:start-indent="0cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style style:name="NormalSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="2" fo:column-gap="0.998cm">
<style:column style:rel-width="32767*" fo:start-indent="0cm" fo:end-indent="0.499cm"/>
<style:column style:rel-width="32768*" fo:start-indent="0.499cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style          style:name="EditorialSect"         style:family="section">
<style:section-properties                  text:dont-balance-text-columns="true"
style:editable="false">   <style:columns    fo:column-count="2">   <style:column
style:rel-width="3401*"      fo:start-indent="0cm"     fo:end-indent="0.499cm"/>
<style:column          style:rel-width="6237*"         fo:start-indent="0.499cm"
fo:end-indent="0cm"/>        </style:columns>        </style:section-properties><
/style:style>

# ' Toggle smart quotes
# \n		newline = new paragraph
# f			Enable footnotes
# date		Doesn't include date
# timestamp Doesn't include any time/date active/inactive stamps
# |			Includes tables.
# <			Toggle inclusion of the creation time in the exported file
# H:3		Exports 3 leavels of headings. 4th and on are treated as lists.
# toc		Doesn't include table of contents.
# num:1		Includes numbers of headings only, if they are or the 1st order.
# d			Doesn't include drawers.
# ^			Toggle TeX-like syntax for sub- and superscripts. If you write ‘^:{}’, ‘a_{b}’ is interpreted, but the simple ‘a_b’ is left as it is.
#+OPTIONS: ':t \n:t f:t date:nil <:nil |:t timestamp:nil H:nil toc:nil num:nil d:nil ^:t tags:nil
---------------------------------------------------------------------------------------------------------------------------------------
#+STARTUP: fnadjust
# Sort and renumber footnotes as they are being made.
---------------------------------------------------------------------------------------------------------------------------------------
#+OPTIONS: author:nil creator:nil
# Doesn't include author's name
# Doesn't include creator (= firm)
:END:
#+TITLE: MONTE KARLOS NĚKDENÍK
#+SUBTITLE: Spousty hluku na Facebooku

* 8/2020
Ročník XXVV
*Adresa redakce:* Karlosova 77, 000 03 Monte Carlo 4
*E-mail:* EmailNoReply@server.mok
*Zákaznická linka:* 0004 892 223 03E
*Šéfredaktor:* Alžběta Ašelová
*Manažer redakce:* Jiří b'Ačkora
*Zástupce šéfredaktora:* Hobbo Habán
*Fotograf:* Alexandra Dimitrij von Dieseldorf
*Grafická úprava:* Tara Kočí
*Obrazová redakce:* Honza Kůň
*Rozhovor:* Karlos Žebatý, Lubomír Lečko
*Móda:* Šlapeboso Elle'Gante
*Závodní ekonomie:* Financier Kovva-Lečný
*Kaňonskop:* Magistr Celestius
*Vymítač:* Kapitán Surhu Sabat
*Vydavatel:* Monte Karlos Inc. a. s.r.o. a spol©
*Brand manager:* Karlos Žebatý
*Sociální poradce:* Lightningh Danger
*Sociální podpora:* Anna Oleš
*Inzerce:* Many Hrabal
*E-shop:* nakupsisam.cz
*Tiskne:* individuálně
*Korespondent:* 
*Špeh:* nevíme
*Seniorní bankomat:* Evžena Kulibrko
*Cestopis:* Áron Ponurý a Emanuel Bebeš
*Rozšiřují:* google.com
* Editorial                                                             :250:
Já ráda čtu moderní fantasy. Bezesporu nejlepší postava v jedné z nejlepších knižních sérií tohoto žánru jednou řekla: "Varuj se všech, kdo tvrdí, že vidí budoucnost." Dlouze jsme se zamýšlela nad jeho výrokem a došla jsem ke dvěma závěrům. Zaprvé, horoskopy, údolskopy a všechny další typy skopů tvrdí, že vidí do budoucnosti. Zadruhé, budu jeho radu ignorovat.

V dnešním čísle jsme si pro vás připravili něco, na co jsem se dlouho těšila. Náš místní Magistr sestavil kompletní ztvárnění kaňonskopu, který jsme vám představili před týdnem. Doporučujeme podívat se na naši speciální přílohu, než se dáte do čtení. Zároveň doufám, že plně využíváte našich poskytnutých služeb a již dobře víte, pod jakým znamením se nacházíte. Zde vám řekneme, co a jak.

Když o tom tak přemýšlím, možná to řekl trochu jinak. "Varuj se všech, kdo tvrdí, že /znají/ budoucnost." Nějak tak.

Někdeník jinak samozřejmě pokračuje. Naše módní sekce se tentokrát vytáhla svou vlastní přehlídkou a co se dozvíte Na vlnách internetu--

On to možná řekl někdo jiný... Je to tlustá knížka a mě se ty postavy pletou. Upřímně si ani nejsem jistá, ve které scéně to řekli. Ale někdo to řekl.

Každopádně, závod pokračuje bez ohledu na nás. Celý svět je v pozdvižení po nečekaném útěku paní Rotreklové z tajné základny /Omma Céb a la Sviña costa/ před několika týdny. Stopy vedou do Bangladéše a dál přes Tunisko do Alžírska, ale úřady si nejsou jisté, čí stopy to vlastně--

Houby. /On/ to řekl. Měla jsem pravdu. Jenom jsem si spletla knihu. Jasně. Druhá kniha v sérii. Postavy tam byly dvě a ta druhá to neřekla. Pardon.

No a závěrem--

Víte, já si ani nejsem jistá, jestli to nebylo v jiné sérii.

Ale dochází nám čas. Užijte si to, mějte se rádi a sbohem.

Řekl to vůbec někdo?
* Závodní ekonomie - Mezinárodní symbióza
Dnes si trochu popovídáme o politice. Nebojte se, nebude to tak strašné, jak nás Tomáš v kanceláří straší. Řeknu vám ve zkratce o vztahu mezi Úřadem a Spolkovou bankovní federací, co z toho má jaká strana a proč je rozhodnutí zavést Radu odvážných důležité, případně, aby ti někteří z vás, co mají problémy s jednoduchými koncepty - hlavně Bob -, co to vlastně Rada odvážných je.

** Symbióza
Jak jistě víte z našeho minulého povídání, jak Mezinárodní Úřad, tak Spolková bankovní federace jsou nadnárodní organizace. Ovládají dohromady podle jistých neoficiálních statistik 79% světové politické moci[fn:1] a jejich úspěch pramení ze vztahu, kterému se v odborných kruzích říká Mezinárodní symbióza.

M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. je velmi, /velmi/ vlivná organizace s mnoha prsty ve všech světových i vesmírných vládách. Jejich slovo je rozkazem, božím vzkazem či přírodním zákonem, podle toho, v jaké zemi se nacházíte. Svou prestiž a moc získávali postupně. Již od svého založení roku 1915 svého letopočtu drželi v rukou nejvlivnější vlády tehdejšího světa a jejich úchop pouze sílil s časem.

Spolková bankovní federace na druhou stranu vydělávala peníze již dvě stě let před svým založením. Vznikla spojením dvacet devíti do té doby neexistujících bankovních institucí a jednoho kasína, které udrželo celý kolos na vodě prodejem tabáku v Austrálii. Doufám, že vám netřeba vysvětlovat - na rozdíl od Kateřiny z reklamní sekce - že peníze jsou moc.

Jak se tyto dva giganti spojili? Inu, jedná se spíše o nucenou spolupráci. Když se obě organizace rozrostli do takových velikostí, že si začali šlapat do ekonomického zelí, daly hlavy dohromady a uzavřeli pakt. Tento pakt, zvaný Kořistní, zajišťuje následující práva a povinnosti.

Všechny spolkové banky platí daně Úřadu podle výše svých příjmů za poslední měsíc (jsou to daně měsíční), výše svých nepřímých investic do fungování Úřadu a výše hladiny moře v Golfském zálivu. Toto vynáší nesmírnou sumu peněz použitých následně na vnitřní chod především odnože OPF, která následně vydělává Úřadu peníze pro chod celé společnosti ve výši 80% daní získaných z banek.

Naopak, banky mají na území kontrolovaném Úřadem (všude) jistá privilegia, například možnost beztrestného vypálení konkurenční banky či lepší důchody. Toto umožňuje expanzi Federace do míst dosud nedotčených bankovní vymožeností, což přináší Úřadu víc peněz z daní a tak dále, dokud tyto dvě instituce nebudou vlastnit všechno jmění světa a nebudou fungovat na vzájemném zdaňování sebe sama.

** Rada odvážných
Druhým z největších příjmů Úřadu je reality show pořádaná odnoží QXM, která se stará o veřejné mínění o Úřadu. Jejich největším hitem je prodávání klipů ze života Učitelů v /závodě/, nesestříhaných a neupravených, jak si někteří - hlavně Bob - myslí.

Veřejné mínění však kleslo po bitvě u Nového Dilí. To se stává, když se navzájem poperou pětimilionové armády a zanechají za sebou smrt, zkázu a vlnu nezaměstnanosti. Proto začátkem tohoto roku zakázal Úřad učitelům vlastnit armády.

Jenomže pak nebylo, o čem vysílat. Únosy kantorů drželi diváky u obrazovek, ale i tomu bylo učiněno zadost. Úřad proto nevydělával peníze z reality show a kvůli pozastavení /závodu/ nerostl počet hlasů v bankovních trezorech. Hlasy přicházejí jen s volbami, které byly rovněž pozastaveny. Banky proto nemohly platit větší daně, což způsobilo druhou finanční krizi.

Řešení je následující - povolit armády a znovu otevřít /závod/, ale zajistit, aby se diváci neobrátili proti Úřady, nýbrž proti učitelům, kdyby se jim něco nelíbilo. A tak vznikla Rada odvážných. Při každém zasedání drženém v Der Weiderhohlle Flüsemschliessem může učitel v Radě přednést stížnost na jednání jiného učitele, které by podle něj mělo být zakázané pravidly /závodu/. Téma se probírá, o návrhu se hlasuje a výsledek je poslán Úřadu samotnému, který rozhodne.

A tak, milé děti - hlavně Bobe -, funguje ta naše planeta.
* Na vlnách Internetu
~Network activated~
~Listening on port 1452~
~Progress: [30%] [######..............]~

~Sending private key~
~Waiting for response _~

~Connection established:~
** Facebook
_Já jsem Áron Ponurý._

*A já Emanuel Bebeš.*

_*A toto je /Na vlnách Internetu/.*_

_Vítáme vás zpět u druhého dílu našeho cestopisu. Já a Emanuel se tentokrát podíváme na zoubek jednomu z nejnavštěvovanějších rezortů světa._

*Je to tak. V posledním díle jsme vás opustili na cestě do Facebook.com, kam jsme dorazili, s bolavými chodidly a znavenou tváří, před pár minutami.*

_Ano, moje chodidla skutečně bolí k nevydržení. Je tu někde místo, kam se mohou bolaví cestovatelé odebrat k odpočinku?_

*Blázníš, Árone? Toto je Facebook.com. Zde není odpočinku.*

_Asi máš pravdu. Vážení čtenáři, já a Emanuel jsme se ocitli na kraji širokého pásu modrého asfaltu vedoucího do slepé uličky nějakých dvacet, třicet metrů daleko._

*Správce Facebook.com nedávno nechal nainstalovat toto chytré zařízení. Je to tak zvaná žárovka, a zde vypínač, jehož zmáčknutím vyvoláte Dark Mode.*

_Ukaž... Ha! Všechno hned vypadá... temnější._

*Ano, tak to funguje. Pojďme se podívat nejprve do ulice Přátel.*

_Po našem pravoboku ve směru příchodu zeje díra ve stěně Facebook.com, skrze kterou je možné spatřit krátkou uličku vedoucí do tmavé místnosti. Cestou ní míjíme mnohé zatoulané duše, které jako by v transu šoupají nohama na cestě ven i dovnitř._

*Nebuď tak netolerantní, Árone. Toto jsou lidé, kteří byli zablokování jedním ze svých přátel ze základní školy. My dva přicházíme ke dveřím s mikrofonem upevněným ke stěně. Zde máme hlasem zadat jméno hledaného kontaktu.*

_Hm-mmmm! Hm-m-mmmm!_

*Nekašli a mluv.*

_Alžběta Ašelová, prosím._

*Dveře se otevírají a světelné pruhy v koberci nás vedou obrovskou místnosti plnou černých skříní.*

_To jsou servery Facebook.com. Blížíme se svému serveru a dostáváme kupón od Pidižvíka zavřeného v jednom z nich, společně s brožurou a malou mapkou Facebook.com. Co s tím teď?_

*Toto je kupón pro Systém Chatu naproti přes ulici. S Áronem se vracíme ulicí Přátel na asfalt a přecházíme silnici na k protilehlé zdi, kde stojí do cihel zaražené posuvné dveře na kartičku.*

_A to je právě ta kartička, kterou s Emanuelem držíme v ruce. Vsouváme ji do slotu a dveře se otevírají do malé hranaté kabinky, skoro až výtahu._

*Když přijdete s někým chatovat, odveze vás kabinka, tak jako nás teď, k příslušnému příjemci, který k vám bude mluvit z vlastní kabinky jedním ze čtyř bezesklích oken ve stěnách.*

_A, už vidím paní Ašelovou, naši šéfredaktorku. Kabinka se pohybuje nekonečným prostorem temnoty, jen světla vycházející z okolních létajících kabinek naznačují, že nejsme sami._

*Vidíme ale, že paní Ašelová není přítomná. Asi má moc práce, co říkáš?*

_Radši nic. Pojďme zpět._

*Cestou vám řekneme něco o skupinových chatech.*

_Ale jen stručně, prosím._

*Jak jinak? Takže skupinové chaty nastanou, když se více než dva účastníci spojí v komunikaci.*

_Jejich kabinky se poté nalepí jedna na druhou do dlouhé řady, takže všichni vidí na všechny, i když se někdy musí naklánět a nadskakovat. Rozhovory pak probíhají skrz všechny kabinky v řetězci a všichni slyší, co se děje Jedna kabinka může být součástí několika skupinových, nebo i normálních chatů, a na to má právě těch okýnek víc._

*Přesně tak, Árone. Stručně.*

_Pojďme se nyní blíže podívat na Facebook.com samotný. Jak už jsme řekli, je to široká slepá ulička, plná - ne, /přeplněná/ - návštěvníky._

*Člověk pomalu neslyší vlastního slova, jak všichni vykřikují jeden přes druhého.*

_Ale nikdo nekřičí tak hlasitě, jako stánek s novinami._

*Ano, po naší levici vidíme výklenek ve stěně, kde za pultem stojí napudrovaný elegán v levném obleku a provolává všelijaké nesmysly do světa. Před ním na půlkruhovém červeném koberci stojí dav posluchačů a jeho proslovy hltají.*

_My s Emanuelem raději nebudeme poslouchat, ještě bychom mu začali věřit._

*Chraň nás ruka Starších Internetu.*

_Naproti je to lepší. Tam je pouze výloha s manekýnkami. K čemu jsou, Emanueli?_

*Inu, to jsou noví doporučení přátelé. Člověk může vejít dovnitř a objednat si přátelství s nějakým dalším člověkem.*

_To jsou mi věci. Ale opatrně! Málem jsi překročil tuto žlutou pásku._

*Uprostřed ulice je napjatá žlutá páska na po pas sahajících stojanech kolem hluboké, temné díry, jejíhož dna nelze z této pozice dohlédnout.*

_Jedná se o nedávný úspěšný hack, který proběhl na pozemcích Facebook.com. Skřeti a bandité z Dark Webu se prokopali až sem, i přes všechnu tu obranu a ukradli citlivá data z ulice Přátel._

*Je to bezpečné, takhle tu tu díru nechávat?*

_Není. Proto je tam ta páska. Ale přesuňme se nyní ke konci této ulice._

*Jak jsme zmínili, je to ulice slepá, na jejímž konci se tyčí velká Zeď. Zdaleka největší dav se mačká před ní a hledí na ni, jako by šlo o zjevení.*

_Pět se metrů vysoká, Zeď je pokrytá odshora dolů tlustým plátnem, které se obmotává po obou jejích stranách, i když veřejnost má přístup jen k této._

*Na vrcholu Zdi stojí dva svalnatci, kteří točí každý obrovskou klikou a posouvají tak plátno v nekonečném cyklu.*

_Ačkoli je nevidíme, za Zdí pracuje armáda Pidižvíků, kteří připevňují na plátno Zdi projevy a prohlášení všech uživatelů Facebooku.com, aby na ně návštěvníci dobře viděli._

*Zrovna teď někdo živě vysílá jakýsi přístroj s monitory a čudlíky. Na monitorech přistupují jednotlivci k urně ve velké, prázdné místnosti a vhazují do ní čisté listy papíru.*

_To víš, lidé toho navysílají spoustu. Jednou jsem sledoval, jak se někdo natočil, když spí._

*A teď vidím odkaz na video na YouTube.com. Támhle, vedle protestu proti vakcínám a fotce něčí večeře.*

_To je mi zajímavé. Do YouTube.com máme právě namířeno příště. Nalevo od Zdi je průchod vedoucí do Přístavu, odkud odplouvá loď po celém Internetu. Zajdeme tam a necháme se odvézt k tomu Emanuelovu odkazu._

*Odtamtud vám napíšeme zase příště.*

_Jsme rádi, že jste si nás přečetli._

*Byla to legrace.*

_*A Bytu zdar!*_

~Connection terminated~
* Závod
** Vývoj                                                                :400:
Celá komunita /závodu/ je roztřesená. Záhadný úprk paní Rotreklové po vloupání neznámého vetřelce do její cely v tajné základně /Omma Céb a la Sviña costa/ rozrušil voliče i kantory. Probíhá rozsáhlé pátrání po jejím komplici v této realitě i v jiných. Autority však varují, že její dopadení je nepravděpodobně.

Paní Lajdová mezitím získává větší a větší vliv v Radě odvážných. Její nedávný výstup na vrchol žebříčku, kde už jednou byla, značí podle odborníků zlom v průběhu celého /závodu/. Jakožto první z Dvaceti statečných, vyžádala si u Mezinárodního Úřadu vyhlášku, že učitelé nemají povoleno scházet se mimo Der Weiderhohlle Flüsemschliessem. Proč tomu tak je odmítá sdělit, ale s její nechutí k veřejnému vystupování se nejedná o žádnou výjimku. Nyní je nezákonné pro účastníky /závodu/ sejít se jeden s druhým mimo tento komplex, a to pouze na oficiální politické záležitosti, které jakožto nový předseda Rady svolává sama.

Další změny v žebříčku jsou předvídatelné. Paní Jakešová se více a více zaměřuje na svou filmařskou kariéru a ignoruje své voliče, což jí ubližuje v očích sponzorů. Veškeré její finance nyní přicházejí z Hollywoodu, ale jejich investice jde převážně do marketingu jejího díla Rychle a v přesile: Tóny smrti. Její pokles byl tedy očividný.

Pan Šeiner se uzavřel do svých komnat a pracuje na nezveřejněném projektu, který však ubírá čas jeho kampaním. I on poklesl, byť o jediné místo.

Paní Malá, která se proslavila velkou rolí v dopadení paní Rotreklové, se propadá ze stejného důvodu. Její úsilí strávené odhalováním únosce nyní chybí její kampani a může trvat ještě dlouho, než se opět postaví na nohy. To jest, jestli ji paní Lajdová nechá.

A konečně, M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. vyhlásil první velké hlasování Rady statečných. Učitelé hlasují o používání armád při získávání bodů od bankomatů a hlasů od voličů. Jejich rozhodnutí poslouží jako štít, za který se Úřad bude schovávat v případě, že dojde na další Nové Dilí. Paní Lajdová ne samozřejmě odmítá vyjádřit, ale její vojenské síly, tvořené převážně rozpadlou Sektou nesplněné pomsty - tedy vojáky Času pomsty -, mluví za sebe. Ona sama se stále odmítá objevit na veřejnosti jinak než v podobě hologramu a její skutečná pozice je všem zcela neznámá.

#+begin_example
1. Zdenka Lajdová
2. Dagmar Kolářová
3. Dana Kubešová
4. Ludmila Malá
5. Marta Křenková
6. Dušan Rychnovský
7. Věra Zemánková
8. Lenka Vývodová
9. Gustav Havell
10. Marie Vávrová
11. Jiří Šeiner
12. Hana Mužíková
13. Jana Horáková
14. Ivo Macháček
15. Taťána Jakešová
16. Jiří Lysák
17. Martina Hapalová
18. Elisie G’uaun Ebbe
19. Radovan Langer
20. Jan Menšíková
#+end_example
** Rozhovor
*Paní Marta Křenková se nachází na osmnáctém místě a po skončení voleb se předpokládá, že se propadne i mimo Dvacet statečných. I přesto si zachovává velkou míru optimismu, což je také důvod, proč jsme ji pozvali.*

*Než se dáme do věcí /závodních/, pojďme se podívat na pár zajímavých věcí z vašeho života. Vy učíte základy společenských věd, že?*

Ano, mimo jiné.

*Čím vás lákal tento obor?*

Je to jeden z nejdůležitějších předmětů, které se na gymnáziu vyučují.

*Přemýšlela jste někdy změnit ho na /pokročilé společenské vědy/?*

No a kde by se učily ty základy?

*Jste jediná, kdo je učí?*

Ještě kolegyně Lajdová.

*A, to chápu. V tom bychom žáky nechtěli nechat, že? Jaký je váš přístup ke studentům?*

Já bych řekla, že jsem k nim velmi milá.

*Jak vycházíte se svými studenti?*

Já se studenty vycházím velice dobře. Většinou. Takovou menší většinou.

*Máte nějaké procentuální vyjádření?*

Tak přesně jsem to nepočítala.

*Co děláte s těmi, se kterými nevycházíte?*

No nevycházím s nimi.

*Nemyslíte si, že s takovou znalostí /společenských věd/ byste měla dosahovat lepších výsledků v /závodě/?*

Když to tak říkáte... Tak to skoro vypadá jako dobrá otázka...

*Rozumím. Jak se bude váš život vyvíjet, pokud nevyhrajete?*

Asi jako doposud. Ale ta změna, kterou by přineslo vítězství, by byla příjemná.
*** Kampaň
*Momentálně vám hrozí nebezpečí dostat se z Dvaceti statečných. Pokud se tak stane, budete usilovat o místo v Radě odvážných?*

Ano, samozřejmě.

*Myslíte si, že k tomu dojde?*

Samozřejmě, že ne.

*Líbí se mi vaše sebejistota.*

Samozřejmě.

*Jaké strategie jste ochotná zapojit pro zajištění vítězství?*

Všechny legální.

*Legální podle zákona, nebo legální podle pravidel /závodu/?*

Hlavně podle pravidel závodu. To je podle mě důležitější faktor.

*Zvážila byste pozici pobočníka, místo nejvyššího vůdce?*

Samozřejmě bych ji zvážila.

*Víte, komu byste ráda dělala pobočníka, kdyby k tomu došlo?*

Třeba kolegyni Pálkovské, ale ta už vlastně v závodu není.

*Čím si vysvětlujete svůj nedávný neúspěch?*

Já si spíš stále nedokážu vysvětlit ten dávný úspěch.

*Paní Lajdová se jaksi ujala vedoucí pozice. Jak se s ní vypořádáte?*

Asi počkám, až se s ní vypořádá někdo jiný, a pak se do toho vložím.

*Takže počkáte a pak se jaksi chopíte příležitosti.*

Doufám. Tedy samozřejmě.

*Jak s paní Lajdovou vycházíte?*

Já s paní Lajdovou naštěstí příliš nevycházím. Já teď vůbec nevycházím ven.

*Změnila se od doby, co vstoupila do závodu?*

Víte, já s paní Lajdovou moc nevycházím, takže...

*Do arény je povolen jeden jediný předmět z okolního světa. Co si hodláte vzít s sebou?*

No, víte, dlouze jsem o tom přemýšlela.
*** Random otázka dne
*Kolik lidí musí stát v autobuse, aby byl přeplněný?*

Plno.
*** Rychlá střelba
*Kam jste schovala paní Rotreklovou?*

Já? Nikam.

*Kam se zašila paní Lajdová?*

K sobě domů.

*Co je to počitek?*

To je vjem. No, ne tak úplně přesně...

*Pozdě. Koho si vyberete jako svého pobočníka?*

Jo, ta paní Pálkovská vlastně v /závodě/ není, že?

*Koho se v /závodě/ nejvíc bojíte?*

Jezevce.

*Jaké jsou vaše naděje pro budoucnost všeho učitelstva?*

Velké. Hlavně doufám, že--

*Sedm.*
*** Korespondence
*Do Monte Karlos nám přišel telegram. Jedná se o jednoduchou zprávu adresovanou naprosto jednoznačně vám, ačkoli adresát striktně řečeno chybí. Zpráva říká:*

*Umíte vy vůbec zpívat STOP*

*Umíte?*

Samozřejmě.
*** Závěrečný proslov
*Závěrečným proslovem nám prosím sdělte--*

Zpívat přece umí každý učitel.

*Ano.*

Jak jinak by věděli, že jste učitel.

*No jistě. To ten pisatel... Závěrečným proslovem nám prosím sdělte, jak se hodláte postavit více--*

To je nehoráznost, tvrdit, že nějaký učitel neumí zpívat.

*Naprosto souhlasím. Závěrečným proslovem nám prosím sdělte, jak se hodláte postavit více než dvojnásobné bodové přesile paní Lajdové, a Shakespearovým sonetem.*

Shakespearovým sonetem nijak, ovšem uvažovala jsem o využití francouzského sonetu. Paní Lajdová má vrozený odpor k Francii, což je chyba. Myslím, že dostatek francouzských sonetů ji doslova ubije k smrti.

*Vy máte takové štěstí, že tu už nemáme paní Kupé.*
* Korespondent
* Lifestyle
** Karlos-čepice
Módní sekce Monte Karlos Někdeníku vám přináší módní zobrazení moderní sociální struktury lidstva.

Nejprve zde máme znamenitý dvojkus. Jedná se o moderní ztvárnění idey komplementárních identit, které jak známo podle přátelského vzezření i tvaru a směru Karlos-čepice do sebe prostě zapadnou. Kamarád 1 a Kamarád 2 představují vskutku...

...prvotřídní vyjádření vzájemných platonických sympatií (bonusové body vypadají-li kamarád 1 a kamarád 2 identicky). Někdeník doporučuje nosit mezi lidi. (Chcete-li zahrnout i třetí identickou osobu, zakupte si náš rozšiřující Karlos balíček v nakupsisam.cz.

Mezi ty, kteří spolu vychází, patří i ti, kteří nikoli. Styl Ležér se hodí zejména pro věčné pohodáře, ale je akceptovatelný i na hlavách zachmuřených a osamocených samotářů. Mezi lidi nebrat, neboť by se tím porušila podstata módní identity.

A konečně je tu Vladař. Vladař patří na vznešenou hlavu těm, kteří nestojí ani tak mimo společnost, jako nad ní. Vyžaduje namyšlenost a domýšlivost, stejně jako železné nervy, královský postoj a žezlo (možno zakoupit samostatně). Mezi lidmi neviděn za posledních dvanáct set století.
** Kaňonskop
* Šeiner
** Lekce bankomata
*** Lekce VII.
My bankomati to máme těžké. Život jednoho z nás je život konstantního odříkání. Většinou /říkáme/ učitele /od/ mluvení s námi.

Bylo šero a světla λl = ¾σf³, Šeinerova matematicky zaměřeného sídla, tlumeně zářila v chodbách všech patnácti křídel. Ne tak u vedlejšího zadního podzemního tajného vchodu. Stála jsem se svým starým svěřencem před dveřmi, kde jsme netrpělivě čekali signál zvenčí. Když říkám netrpělivě, myslím samozřejmě, že jsem byla nezaujatá a lhostejná podle kázání Kodexu, ale Šeiner přešlapoval z nohy na nohu a mnul si nervózně ruce.

Nevím, proč mě tam tahal tak brzy, když nás host Rychnovský měl dorazit až za dvacet minut, ale bankomatovi nepřísluší stěžovat si vůbec na nic. Šeiner mluvil o počasí, světové politice, světovém počasí a chrtích závodech. Já poslouchala s profesionálním zájmem až do chvíle, kdy se ozval tajný signál - někdo zaklepal na dveře.

"Pojď dál, pojď dál. Nestůj tak v dešti!" zvolal Šeiner, ustoupivše dovnitř se valícímu Rychnovskému, a zavřel dveře na zcela bezmračnou noc. "Jak se vede?"

"Ale to víš," řekl Rychnovský a pověsil suchou pláštěnku na věšák. Učitelé jsou někdy zvláštní a s tím se bankomat musí vyrovnat. "Banány zlevnily a Vídeňská opera hraje Hamleta. Ale ty houby! Ty houby!"

Společně se vydali temnou chodbou, klapání jejich vycházkových holí o mramorovou podlahu doprovázející jejich kroky. "Jak se máte vy, Kulibrko?"

"Jako bych tu nebyla," řekla jsem.

"Ale prosím vás," mávl rukou Rychnovský. "Já tu nejsem taky."

Ano, oficiálně neměl Rychnovský ani Šeiner povolení scházet se s ostatními učiteli mimo Der Weiderhohlle Flüsemschliessem, a to ještě po schválení žádosti, na rozkaz vedoucího Rady Odvážných, jisté paní Lajdové.

"Tahle vyhláška je stupidní," řekl Šeiner a zabočil do jedné z úzkých chodeb vedoucí do druhého podzemí, trochu podzemnějšího než to první. "Jak se máme domlouvat na politice, když se nesmíme scházet? Takhle se nedá /závodit/."

"Přesně," bylo jediné, co k tomu Rychnovský dodal. Já byla zticha. Bankomati nemají za úkol kontrolovat pravidla /závodu/. Naopak, když se učiteli povede nějaké šikovně porušit, je to pro něj bonus a příznivě se to projeví na jeho bodovém ohodnocení.

"Něco se s tím musí dělat," prohlásil rezolutně Šeiner. Dorazili jsme k těžkým kovaným dveřím, které odemkl naskenováním klíče a otočením prstu v zámku. Pokynul Rychnovskému, aby vešel, ten pokynul Šeinerovi, že ne, /on/ má vejít první, ten na oplátku pokynul mě, což Rychnovský schválil kývnutím hlavy. Pokrčila jsem rameny a vešla jsem do místnosti bez oken s několika židlemi a stolem s lampičkou.

Spokojen, že jsem se dostala dovnitř, pokynul Šeiner Rychnovskému, aby vešel, ten zavrtěl hlavou a vytrhl svému kolegovi kliku z rukou, jako že mu podrží dveře, načež Šeiner pokorně sklopil zrak a pokynul mě, abych šla ven jako první. Oba si uvědomili, že ztrácí čas a vyšli naráz, rameno vedle ramena. Promptně se zasekli mezi dveřním rámem a trvalo jim nějakou dobu, než se protlačili za mnou. Já bych jim byla pomohla, ale my bankomati nesmíme zasahovat.

"Takže," řekl Šeiner a odkašlal si. "Jak říkám. Něco se s ní musí dělat."

Okované dveře se na nás se skřípěním zavřely.
*** Lekce VIII.
Mezi základní schopnosti dobrého bankomata patří rychlá adaptace na novou etiketu. Na Luthadelské univerzitě vás naučí všech dvaadvacet standardních způsobů stolování a všech pět verzí židlení, ale více času strávíte cvičením dynamického přizpůsobování se na zvyky nového prostředí.

Bály v Der Weiderhohlle Flüsemschliessem jsou velkolepé a bohaté. Věřte mi, na světě nenajdete výstřednější událost než takový bál. Aspoň ne v téhle dimenzi. Na takovém místě pak zužitkujete veškerý svůj trénink.

"Jiří!" Šeiner volal z plných plic, i když už byl na cestě k Jiřímu Horkému, který o něm dobře věděl a nevyžadoval upoutání pozornosti. Jednou z nejtěžších disciplín zmíněné adaptace je schopnost ignorovat, když někdo etiketu porušuje.

"Jiří!" zařval horký na Šeinera. Tak nic.

"To máme ale hostinu, co?" řekl Šeiner a ukázal na skvostně zdobený sál slavnostního mrakodrapu. "A ten výhled!" Z oken nejvyššího patra bylo možné zpozorovat zakřivení planety. "Jak se ti líbí, tady na Radě?"

"Ujde to, ujde to. Ve Dvaceti statečných by to bylo lepší, ale poslední dobou beru, co můžu." Jiří Horký byl na momentálně dvacátém šestém místě žebříčku a tudíž jeden z nejvýše postavených Radních v Radě Odvážných. Do nejvyšší dvacítky se ale nikdy nedostal.

Šeiner ho vzal za rameno a ustoupil o krok stranou, nakláněje k němu hlavu ve spikleneckém gestu. Ani jeden si nevšiml, že se tím přiblížili ke skupině Malá-Vávrová-Langer, která stála opodál. Já si všimla a hned to šlo do notesu.

"Slyšel jsem," šeptal Šeiner, "že jsi našel skulinu."

Horký mávl rukou. "Jenom malou. Učitelé nesmí vlastnit armády, ale nikdo nic neřekl o skupině biografů, kteří náhodou umějí používat zbraně. Za poslední dny rosteme prakticky závratně. Ale jestli dnes odhlasujeme, že je to legální, tak to bude jedno."

Šeiner zavrtěl vážně hlavou. "Nesmíme jí dovolit postavit armádu. To by s námi byl konec. Ale svoje písaře si nech. Budou se hodit. Chytrá skulina."

Zasedání Rady Odvážných začalo o půl hodiny později. Všech šedesát osm kantorů (Lajdová se nepočítá) z prakticky všech pozic žebříku sedělo v kruhové místnosti na vzestupných lavicích kolem pódia postaveného jako jeviště amfiteatru. Hodiny odbyly desátou ranní. Na pódium přilezla zvláštní platforma na šesti kovových nohách. Vzduch nad ní se zavířil a před shromážděním se objevila Lajdová, průhledná a modrá, jako správný hologram.

"Začněme!"
*** Lekce IX.
Bankomat musí ovládat těsnopis. Co je víc, bankomat musí ovládat úzkopis, který je k těsnopisu co těsnopis k hieroglyfům. Poznámky se sami neudělají.

"Dále bych rád připomněl Radě, že ne všichni mají tu potřebu zdržet se tak logického kroku, jako je stavba vlastní armády. Mým závěrečným protiargumentem je tedy to, že /já nejsem neschopný/, na rozdíl od někoho, /postavit si vlastní armádu/." Macháček se posadil za slabého potlesku.

"Máte nějaké protiprohlášení? Upozorňuje, že je to poslední proslov, než přestoupíme k hlasování." Hologram Lajdové stál a sledoval Radu.

Šeiner se postavil a rozhlédl se po sedících učitelích. "Jak si trojctihodný a double-vážený kantor Macháček jistě vzpomene, mé Podmořské Amazonky Sakumprásk byly velmi účinné. Poukazují na mou /schopnost/ zajistit si vojenské síly. Tudíž můj argument proti jejich používání při /závodě/ nezávisí na neschopnosti, ale morálním základě. Jinak už jsem argumentoval vším." Posadil se za poněkud slabšího potlesku. Nikdo nechtěl slyšet hlas rozumu.

"Dobrá," uzavřela debatu Lajdová. "Přejděme nyní k hlasování o hlasování. Kdo je pro, aby se hlasovalo otevřeně?"

"Promiňte," zvedl se učitel McOliess, 6004. místo. "Ale co když chci hlasovat tajně o tom, jestli chci hlasovat tajně?"

"Dobře. Kdo je pro otevřené hlasování o hlasování o hlasování?"

Nakonec skončili jednoduchým zvednutím ruky. Proti používání armád - 32. Pro používání armád - 29. Zdrželo se - 8. Podle pravidel hlasování sepsaných současným nejvýše postaveným učitelem a předsedou Rady (tedy Lajdovou), kdo nehlasuje, přidá se ke slabší straně. Tudíž proti - 32; pro - 37. Používání armád je v souladu s pravidly závodu.

Šeiner se nehýbal. "Prohrál jste," pobídla jsem ho k reakci. "Já vím," řekl mi na to. "To se dalo čekat. Většině těch, kteří hlasovali pro armády, vyhrožovala, až jí slíbili své hlasy." Nevypadal zrovna překvapeně.
*** Lekce X.
Je téměř svatou povinností bankomata seznámit se detailně s charakterem svého svěřeného učitele. V mém případě jsme pracovala jen s jednou, byť o to komplikovanější myslí, abych měla čas sepsat tyto lekce, ale v běžném životě se jich nakupí klidně šest. Znalost učitelů je důležitá, neboť ignoranství vede často k chybnému hodnocení. Rozhazuje a rozdává váš učitel moc hala bala kam se podívá, nebo si chytře připravuje půdu pro pozdní fáze /závodu/? Musíte se proto naučit klást správné otázky a pronásledovat všechna podezření.

První polovina zasedání skončila. Rada Odvážných odhlasovala, pod silným výhružným vlivem paní Lajdové, že používat vojka k získávání bodů není protizákonné. Šeinera tento prospekt znepokojil. Bál se další války.

Když Rada dojedná hlavní body programu, dají si pauzu. V mrakodrapu je místnost, do které během této přestávky každý kantor povinně zaleze, bez doprovodu, a navrhne další bod jednání. Pokud žádný nemá, vhodí do urny prázdný papír. Pokud chce něco projednat, napíše na něj své návrhy a nikdo pak nebude schopen dopátrat, kdo navrhl které téma. Šikovný systém.

U výtahu jsem se prokázala průkazem bankomata a spolu nás pustili dovnitř. Bankomati mají jistá privilegia. Podle Dohody o poskytnutém prostoru nesmíme prozradit, co naši svěřenci vhodili do urny, ale je naší povinností /vědět/, co to bylo.

"Co teď budete dělat?" zeptala jsem se Šeinera, aby řeč nestála.

"Lajdová se postupně staví do nezničitelné pozice." Zněl, jako by se o tom chtěl s někým bavit a byl vděčný, že jsem začala. "Teď má možnost svolat všechny ty armády, co jsme nechali stranou po Novém Dilí. Měla víc času si zajistit podporu - /vynutit/ podporu - mnoha učitelů. A pomalu přebírá kontrolu nad celým /závodem/."

"To je sice hezké, ale vůbec to neodpovídá na moji otázku."

"Musíme použít jedinou autoritu, kterou máme, a /dokud/ ji máme. Svojí pozici staví na bankách. Má nejvíc bodů, díky svým výhrůžkám, a to bankám přináší poplatky za její účet. A banky mají moc nad M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. Takže to musíme zastavit."

Na to jsem se ho sice neptala, ale vycítila jsme důležitější téma. "Když jsme byli u Rotreklové, něco se stalo."

"Ano. Nechali jsme mezeru v zabezpečení a Martina utekla." Dveře výtahu se otevřely. Zavezl nás o patro níž, kde celé podlaží zabírala jedna jediná místnost. Byla dvacet metrů vysoká, dlouhá jako malá ulice a osvětlená neonovými zářivkami na stropě. Zrcadla lemovaly všech šest stěn a uprostřed stál kamenný stupínek s urnou, ke které vedly majestátní schody. Šeiner se vydal k urně.

"To nemyslím," řekla jsem. "Když nás trpaslíci zahnali do prádelny, nějak jste se změnil. Bylo chladno, mluvil jste jinak. A říkal jste si Albert. Albert něco."

"Albert Bílí," povzdechl si Šeiner. "On někdy vezme kontrolu. Ignorujte to."

S tím vystoupil na schody.
*** Lekce XI.
Lajdová zírala na nově navržená témata k hlasování. Její modrý hologram četl z listu na pultě před ním. Lajdová v posledních měsících zalezla kdoví kam a nikdo z ní neviděl víc než matný obrys na chodícím kovovém podstavci.

"Máme jeden bod k probrání," řekla nejistě. "Neznámý trojctihodný a double-vážený kantor navrhuje zadržet všechny finance od sponzorů až do Arény. Prý aby se zabránilo zbytečné soutěži mezi učiteli a vedlejším ztrátám. Kdo se chce vyjádřit?"

Zněla vyděšeně. Zněla poraženě. Zněla naštvaně. Kdyby neměla přístup ke svým financím, jak správně Šeiner a Rychnovský odhadli, nedokázala by si udržet svou pozici ani sídlo ani armádu, kterou teď může postavit. Kdyby se peníze od sponzorů ukládali až do Arény, bylo by po její možnosti se tam dostat.

Paní Zemánková se zvedla. "To je blbost. Jakýkoli double-tohleto, který to vymyslel, je pomatený. Bez peněz se nedá vést kampaň."

"To není pravda," řekl Rychnovský, který rovněž vstal. "Dostáváme peníze od voličů. Ty by mohli jít do kampaně a ty od sponzorů zůstanou v bankách."

"Nesmysl!" zvolala Mužíková. A tak to šlo dál. Hádali se víc, než bych čekala. Lajdová nic neřekla, zato házela pohledy po různých učitelích Rady. Šeiner bedlivě sledoval dění a nevadilo mu, že víc hlasů jde proti jeho návrhu, než pro něj. Většina učitelů mlčela s ním.

Konečně, když všichni dořvali, Lajdová vyhlásila hlasování. Průhledný modrý pot na jejím průhledném modrém čele byl zcela neviditelný. "Kdo hlasuje pro?"

Ze šedesáti devíti učitelů, deset zvedlo ruku. Šeiner mezi nimi nebyl. Nechtěl se prozradit. Naklonil se ke mně a zašeptal: "Těch proti je víc. Ale většina je bez názoru. Takže naše strana bude slabší a ti nerozhodnutí připadnou nám." Kývl na Rychnovského na druhé straně sálu.

"A kdo je proti?"

Všichni ostatní zvedli ruku. Šeinerovi zaskočilo.

"Návrh se zamítá. Končíme." Její hologram zmizel okamžitě.
*** Lekce XII.
"Já myslel, že se vzpamatují." Šeiner stál v dolní hale, jedné z místností spodního patra mrakodrapu. Ostatní učitelé si oblékali kabáty a připravovali se, až je ochranka Der Weiderhohlle Flüsemschliessem pustí ven. Schovali jsme se vedle velkého přístroje plného tlačítek a obrazovek - dálkového ovládání super-satelitu, které bylo veřejně vystaveno na důkaz jeho všeobecného využití.

"Kdo?" Neměla bych se ptát. Správně by mi měl všechno říct sám. Takhle ho akorát dovedu k tomu, co chci slyšet, ne k tomu, co mi chce říct. Ale bylo mi ho líto. To je samozřejmě neideální pro nás bankomaty.

"Všichni. Myslel jsem, že si uvědomí, že jsou důležitější věci než /závod/. Že se postarají, aby Lajdová nepřivedla nějakou pohromu. Ale oni by si radši nechali všechny ty peníze."

Nechápala jsem, co jiného by mohlo být důležitějšího než /závod/, ale nechala jsem to bez komentáře.

"Pardon, že se opakuji," řekla jsem opatrně, "ale co teď budete dělat?"

Šeiner zavrtěl hlavou. "Musíme na to jít jinak. Tajněji. Chytřeji." Povzdechl si. "Ale jak, to nevím."

Najednou se za námi ozvalo pípání a pískání. Otočila jsem se a uviděla, že dálkové ovládání satelitu ožilo. Nikdo u něj nestál - nikdo neměl povolení od M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. satelit použít - ale obrazovky přesto zářily a dokonce to vypadalo, že někdo satelit ovládá.

"Co to je?" zašeptal Šeiner, ale to už se odevšad řinuly protesty pobouřených kantorů.

Jejich nespokojenost nebyla nic proti tomu, jak pobouření byli, když viděli, co se na monitorech zobrazuje. Někdo nechal sledovat - /bez povolení/ a protizákonně - místnost se zrcadli. Teď se (asi dálkově) přihlásil a díval se na záznam. Jeden po druhém učitelé vystupovali po schodech a vhazovali prázdné papírky do urny.

Kantoři byli voláni postupně podle pořadí. Šeiner přišel jako desátý. Vystoupal se mnou po schodech a bylo vidět, jak se bavíme. Utrhl ze štosu list papíru. Přikročil k urně. A prázdný ho hodil dovnitř.

Důležitá lekce pro začínající bankomaty: Když nechcete být odhaleni, přemluvte někoho jiného, aby udělal špinavou práci za vás. Respektive, když učitel přemluví svého protivníka, aby se za něj ujal nepříjemného úkolu, má pojistku, že když se na to přijde, bude tento protivník viněn a tudíž potrestán. Každopádně dobrý výsledek.

Šeiner (a Rychnovský) u mě dostali bod za přemluvení Ebbe.
** Špeh
~Zaznamenáno špehujícími satelitními talíři Monte Karlos~

Cíl opustil hlasovací patro v 19:37. Připravuje se na odchod. Bankomat je stále přítomný. Štěnice úspěšně umístěna na cílův kabát.

Satelitní stanice naznačuje aktivitu. Na monitoru probíhají videa učitelů. Video s cílem proběhlo bez následků.
Bankomat se tváří pyšně. Cíl se panicky rozhlíží.

Bankomat: Co to děláte?
Cíl: To je Lajdová. Musíme to zastavit.
Bankomat: Proč?

Cíl nereaguje. Rozhlíží se po hale a něco hledá.

Cíl uhodil pěstí do stěny.
Cíl: Není tu anténa!
Sluha v bílém: Anténa je na střeše.
Cíl: Na to není čas.
Bankomat (šeptem): Prostě to nechte běžet.

Cíl nereaguje. Poklepává si kapsy. Vítězně vytáhne telefon.

Cíl: Ale ne! To je Nokia.
Bankomat: No a co?
Cíl (nahlas): Má tu někdo smartphone?

Jakešová neochotně podá svůj Android. Cíl se začíná připojovat k internetu. Žádost o zablokování systému.

~Šifrovaná zpráva opačným směrem~

Potvrzuji - žádost zamítnuta.

Bankomat (potichu): Proč ji prostě nenecháte?
Cíl: Kdyby se Lajdová dozvěděla takhle veřejně, že to napsala Ebbe, jak dlouho bude trvat, než to hodí na nás? Než řekne, že jsme ji k tomu navedli?
Cíl se úspěšně připojil na internet - vyhledal Facebook.

Videa na monitoru postupují. Právě zkoumají Macháčka.

Bankomat: Já myslela, že to byl váš cíl. Hodit to na ni a mít o soupeře míň.
Cíl: Ale ne tak očividně. Tohle je moc nápadné. Lajdová se to stejně dozví, ale Ebbe nebude mít šanci na nás ukázat prstem, protože si to Lajdová nechá pro sebe. Takhle si to pro sebe nechat nemůže.

Cíl zapnul streamování. Nahrává ovládací panely a monitory a živě je vysílá do éteru.
Bankomat: A tohle je co?
Cíl: Když Lajdová zjistí, že se na ni kouká veřejnost, nebude si moct dovolit pokračovat. Pořád ještě se tu hraje na hlasy voličů a co dělá je nezákonné. Podržte mi to.

Cíl vrazil telefon do rukou bankomatovi a znovu se začal rozhlížet, tentokrát pomalu a pátravě.

Bankomat: Nic se neděje.
Cíl: Dejte tomu chvíli.
Bankomat: Jak se Lajdová dozví, že to vysíláme?
Cíl: Telefonem.

Ovládací panely zhasly. Všem se ulevilo. Cíl vrátil telefon Jakešové.

Bankomat: Co jste to sledoval?
Cíl: Kdo zavolá Lajdové.
Bankomat: A?
Cíl: Menšíková.
Bankomat: A co jí brání podívat se na to znovu?
Cíl: Nic. Ale to už budou všichni doma.

Rada Odvážných jde domů. Cíl jede do λl = ¾σf³. Další zprávy přijdou, až cíl poruší svou rutinu.
* Poznámky

[fn:1] Především podle profesora Aßohla Biebelbaubera, který po publikování svých poznatků záhadně zmizel a byl nahrazen mrtvým tělem s třikrát prostřelenou plící překvapivě akurátní kvality (ne plíce, tělo - jeho napodobenina byla velmi akurátní).
