# -*-eval: (setq-local org-footnote-section "Poznámky"); eval: (set-input-method "czech-qwerty"); eval: (set-register ?\' "“"); eval: (set-register ?\" "„");eval: (set-register ? "M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S."); eval: (set-register ? "■"); eval: (ispell-change-dictionary "czech"); eval: (flyspell-mode 1);-*-
:stuff:
<style:style style:name="InterviewSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="3" fo:column-gap="0.497cm">
<style:column style:rel-width="21845*" fo:start-indent="0cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style style:name="NormalSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="2" fo:column-gap="0.998cm">
<style:column style:rel-width="32767*" fo:start-indent="0cm" fo:end-indent="0.499cm"/>
<style:column style:rel-width="32768*" fo:start-indent="0.499cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style          style:name="EditorialSect"         style:family="section">
<style:section-properties                  text:dont-balance-text-columns="true"
style:editable="false">   <style:columns    fo:column-count="2">   <style:column
style:rel-width="3401*"      fo:start-indent="0cm"     fo:end-indent="0.499cm"/>
<style:column          style:rel-width="6237*"         fo:start-indent="0.499cm"
fo:end-indent="0cm"/>        </style:columns>        </style:section-properties><
/style:style>

# ' Toggle smart quotes
# \n		newline = new paragraph
# f			Enable footnotes
# date		Doesn't include date
# timestamp Doesn't include any time/date active/inactive stamps
# |			Includes tables.
# <			Toggle inclusion of the creation time in the exported file
# H:3		Exports 3 leavels of headings. 4th and on are treated as lists.
# toc		Doesn't include table of contents.
# num:1		Includes numbers of headings only, if they are or the 1st order.
# d			Doesn't include drawers.
# ^			Toggle TeX-like syntax for sub- and superscripts. If you write ‘^:{}’, ‘a_{b}’ is interpreted, but the simple ‘a_b’ is left as it is.
#+OPTIONS: ':t \n:t f:t date:nil <:nil |:t timestamp:nil H:nil toc:nil num:nil d:nil ^:t tags:nil
---------------------------------------------------------------------------------------------------------------------------------------
#+STARTUP: fnadjust
# Sort and renumber footnotes as they are being made.
---------------------------------------------------------------------------------------------------------------------------------------
#+OPTIONS: author:nil creator:nil
# Doesn't include author's name
# Doesn't include creator (= firm)
:END:
#+TITLE: MONTE KARLOS NĚKDENÍK
#+SUBTITLE: 

* 9/2020
Ročník XXVV
*Adresa redakce:* Karlosova 77, 000 03 Monte Carlo 4
*E-mail:* EmailNoReply@server.mok
*Zákaznická linka:* 0004 892 223 03E
*Šéfredaktor:* Alžběta Ašelová
*Manažer redakce:* Jiří b'Ačkora
*Zástupce šéfredaktora:* Hobbo Habán
*Fotograf:* Alexandra Dimitrij von Dieseldorf
*Grafická úprava:* Tara Kočí
*Obrazová redakce:* Honza Kůň
*Rozhovor:* Karlos Žebatý, Lubomír Lečko
*Móda:* Šlapeboso Elle'Gante
*Závodní ekonomie:* Financier Kovva-Lečný
*Kaňonskop:* Magistr Celestius
*:* 
*Vydavatel:* Monte Karlos Inc. a. s.r.o. a spol©
*Brand manager:* Karlos Žebatý
*Sociální poradce:* Lightningh Danger
*Sociální podpora:* Anna Oleš
*Inzerce:* Many Hrabal
*E-shop:* nakupsisam.cz
*Tiskne:* individuálně
*Korespondent:* 
*Špeh:* nevíme
*Seniorní bankomat:* Tera Mažetková
*Cestopis:* Áron Ponurý a Emanuel Bebeš
*Rozšiřují:* google.com
* Editorial                                                             :250:


Alžběta Ašelová, šéfredaktor
* Závodní ekonomie - Obratná finanční šipka
Pojďme se společně pobavit o způsobu, jakým spolkové banky získávají peníze. Vzhledem k tomu, že celý /závod/ stojí na daních z těchto příjmů, neváhal bych to nazvat klíčovou informací.

Inu, banky mají jistý zavedený styl drásání peněz ze svých zákazníků. Tak zvaná Obratná finanční šipka je pravděpodobně nejvyspělejší takový styl, široce používaný všem spolkovými bankami.

Jako každá správná šipka má čtyři vrcholy: banky, učitele, voliče a sponzory. Nevíte-li, kdo je kdo, doporučím vám přečíst si mé první dílo. Mnozí - hlavně Bob - si myslí, že banky dostávají peníze jen od učitelů za poskytnutý prostor podle Dohody o poskytnutém prostoru. Ačkoli tomu tak není, pojďme se nejprve podívat na způsob jejich úschovy.

** Trezory
Každá banka má svůj trezor. To je jasné. Ty lepší ze spolkových banek jich dokonce musí mít několik - minimálně jeden pro každého kantora. V těchto trezorech schovávají učitelé své hlasy získané ve volbách ve formě dvanáct centimetrů širokých a devět centimetrů dlouhých perfektních safírových kuliček.

Volba banky je čistě na učiteli, ale bez bankovního účtu není možné zůstat členem /závodu/. Trezory jsou střežené špičkovým softwarovým zabezpečením a s hlasy je možné pracovat s jakoukoli jinou komoditou běžně schraňovanou v bance - naftou, emocionální inteligencí, inspirací a podobně. Dostat se přes tento firewall je prostě nemožné bez bezpečnostního kódu a přiděleného čipu, unikátního pro každého učitele.

Fyzický přístup do trezoru je možný, ale banky ho nedoporučují netrénovanému personálu. Od doby, co Harry vykradl Gringotovy, nechává ministerstvo kouzel draky volně pobíhat po sklepeních a bez patřičného výcviku návštěvníkům hrozí upečení.

Nyní body šipky:

** Sponzoři
Sponzoři dávají své peníze učitelům na kampaně. Tak se to aspoň říká oficiálně. Ve skutečnosti většina z nich jde na splátku astronomických poplatků za hlasový trezor. Sponzoři jsou podle definice bohatí jedinci, kteří doufají v eventuální návrat svých financí, až dostanou čestné místo v radě výherce /závodu/, tedy nejvyššího vůdce všeho učitelstva, a tak jim nevadí ztrácet peníze v hlubinách banek.

** Učitelé a voliči
Učitelé mají dva různé povolené proudy příjmů. Jedním z nich jsou samozřejmě sponzoři. Druhým jsou jejich voliči. Voliči jsou žádání, lež ne nuceni, finančně podporovat svého kandidáta malými sumami peněz, které když se sečtou vydávají v průměru za 40% sumy od sponzorů.

Čím důležitější učitel s více body, tím víc peněz získá od svých voličů a sponzorů, ale tím větší jsou pro něj poplatky u banky za pronajatý prostor, takže celá maškaráda pokračuje.

** Banky
Banky tvoří poslední článek tohoto pazvláštního řetězu. Sponzoři a voliči posílají peníze učitelům, ti je posílají bankám, a celá věc, když se nakreslí, připomíná někomu - hlavně Bobovi - šipku.

#+begin_comment
Obrázek Obratné finanční šipky bez půjček.
#+end_comment

Avšak zde nejde jen o finanční šipku, nýbrž o /obratnou/ finanční šipku. Co se tedy obrací?

** Obratná finanční šipka
Ptal jsem se Marie, stážistky zde v Někdeníku, kde si myslí, že voliči berou peníze, kterým učitelům přispívají? Nevěděla.

V bankách, Marie, v bankách.

Ano, volič jde a půjčí si u banky peníze. Tyto peníze poskytne jako dar učiteli, který jimi zaplatí místo za voličův hlas. Tím pádem se peníze pohodlně vrátí do banky. Ale banka sama ještě vydělává na splátkách z původní půjčky, dostane tudíž ty samé peníze dvakrát a jednou z toho i s úroky.

Dohromady to vytváří nekřesťanský Obrat.

#+begin_comment
Obrázek Obratné finanční šipky s vyznačenými půjčkami.
#+end_comment
* Na vlnách Internetu
~Network activated~
~Listening on port 1452~
~Progress: [55%] [###########.........]~

~Sending private key~
~Waiting for response _~

~Connection established:~
** Pirate's Bay
_Já jsem Áron Pokorný._

*A já Emanuel Bebeš.*

_*A toto je /Na vlnách Internetu/.*_

_Opět k vám promlouváme optickými kabely, tentokrát z paluby /Rychlého šípu/, lodě, která nás po vlnách Internetu plaví do YouTube.com._

*Jedná se o osvědčený design Packet, kterých na informačním moři vidíme sta tisíce.*

_Ano, od schválení modelu Packet Staršími Internetu se rozšířilo jeho využívání na více než sto procent._

*A proč jim píšeme teď, Árone, ještě daleko od YouTube.com?*

_To je jednoduché, Emanueli, to je jednoduché. Kapitán lodi nám právě oznámil, že cestou uděláme neplánovanou (a neoficiální) zastávku._

*Přesně tak. /Rychlý šíp/ na pár hodin zastaví v Pirátově zátoce, neboli ThePirateProxy3se.com.*

_To je nějaké zvláštní jméno, to ti povím._

*Je. Dřív se zátoka jmenovala ThePiratesBay.com, ale z jistých ne úplně legálních důvodů se museli přejmenovat.*

_Každopádně, já a Emanuel jsme nechtěli marnit čas a rozhodli jsme se využít této příležitosti k popsání dalšího koutu těchto vod._

*Loď připlouvá k zátoce, a hned je vidět, že jsme zavítali mimo běžnou civilizaci. Jak můžete vědět, Pirátova zátoka je místo pro stahování všeho možného materiálu z hlubin Internetu, a majitelům těchto materiálů to ne vždy vyhovuje.*

_Místní úřady proto musí jednat tajně a vydělávat na reklamách. Zátoka sama má oválný tvar ohraničený z jedné poloviny pevninou a z jedné třetiny úzkým poloostrovem, který jako by se natahoval po pevné zemi a tvořil tak téměř samostatnou vodní masu. Lodě proplouvající z oficiálních vodních silnic musí proplout kolem tohoto poloostrova a jsou přivítány desítkami bilboardů s reklamami a upoutávkami._

*O kousek dál střeží malou mezeru mezi poloostrovem a pevninou místní přístav. /Rychlý šíp/ zde zakotvil u dlouhého mola a kapitán propustil cestující do malého města, kde vyčkají jeho návratu.*

_Na naši žádost nám povolil doprovodit ho na jeho cestě. První zastávkou je Jukebox, místo, kde si kapitáni vyzvedávají magnety._

*Magnety, Árone?*

_Magnety, Emanueli. Soubory získané v Pirátově zátoce se nalodí pomocí speciálního zařízení zvaného Torrent Client a zvláštního identifikátoru zvaného magnet._

*Tento magnet se připevní na spodní část Clientu a slouží jako hák na prutu. Za chvíli jej uvidíte v akci.*

_Kapitán vybere v Jukeboxu příslušný magnet z výběru, podle klíčových slov, která zadal Pidižvíkovi uvnitř, a vezme si od něj, co mu dá._

*Ne vždy se toto předání povede. Magnety mohou být poškozené, či se Pidižvík splete, ale většinou proběhne vše bez problému.*

_S kapitánem a jeho posádkou jsme se nalodili na /Rychlý šíp/, další cestující se baží civilizovaným životem přístavu, a vypluli jsme do zátoky._

*Proplouváme kolem špičky poloostrova a před námi se ocitá prazvláštní podívaná. Desítky Packetů se pomocí lan a dřevěných ramp spojilo do mnoha řetězů vedoucích k Těžební jednotce, městu vyčnívajícímu z pobřeží a připomínajícímu Benátky.*

_Každá loď používá svůj Client a když vyloví, co nepotřebují, pošlou to po řetězu dál na další lodě, které si to buďto nechají, nebo to pošlou dál a tak dále a tak dále._

*/Rychlý šíp/ se zapojuje do jednoho takového řetězu. Kapitán umísťuje magnet na konec dlouhého kabelu, který takto zatížený hází do vody.*

_Client je vlastně takový naviják - malá skříňka s motorkem uvnitř, kabelem vycházejícím z jejího nitra a čipem někde uvnitř. Kabel hledá na dne zátoky a když najde, vytáhne to Client na světlo._

*Než se kapitánovi podaří něco vylovit, pojďme se podívat na Těžební jednotku, beze sporu nejzajímavější kout zátoky.*

_To proto, že tu nic jiného není._

*Přesně. Ani já, ani Áron tam nezavítáme. Je to totiž nebezpečné.*

_Ano, i když z dálky vypadá jako další místo k odpočinku, Těžební jednotka je plná přetvářky a vyzvědačství. Kdo tam vkročí, podstupuje se návalu nezřízeného alkoholu, v jehož spárech z něj tamní obyvatelé vytáhnou jeho osobní údaje - bankovní číslo, rodné číslo, číslo pasu, číslo IP, telefonní číslo a všelijaká další osobní tajná čísla._

*Krom toho tam staví pirátské lodě se zbožím ukradeným na počestných Packetech na moři.*

_To všechno pak jde na záda Pidižvíků a prodává se třetím stranám._

*i z dálky jsou k rozeznání silnice vedoucí z Jednotky dál na pevninu mezi kamennými zákoutími a tmavou půdou, po kterých Pidižvíci nesou citlivé informace.*

_A pár set kilometrů dál stojí zlověstná černá brána zasazená do úbočí velké tyčící se hory, kde všechny silnice končí. Co to je, Emanueli?_

*To je vstup na Dark Web. Tam se všechny ty informace prodávají.*

_Radši od nich zůstat daleko._

*A, Client něco našel. Kabel tahá ze dna zátoky těžkou dřevěnou truhlu. Kapitán ji otevírá a uvnitř nachází DVD kýženého filmu. Skvěle. Zvedáme kotvy a odplouváme.*

_Tak si říkám, jak tohle místo může přežít. Nemají Starší Internetu zákon proti stahování dokumentů?_

*Mají, ale ani Starší Internetu nejsou všemocní. Mají dost práce bojovat s Dark Webem o planiny Apple Inc. a místo jako Pirátova zátoka je trpěno z nedostatku prostředků.*

_No, každopádně, my již nabíráme cestující a vydáváme se dál. Příští zastávka, doufejme..._

*Ha ha ha.*

_... bude YouTube.com. My se s vámi pro dnešek loučíme._

*Těšíme se na psanou.*

_Těší nás, že se o nás zajímáte._

*Byla to legrace.*

_*A Bytu zdar!*_

~Connection terminated~
* Závod
** Vývoj                                                                :400:
Při posledním zasedání Rady Odvážných došlo k neoprávněnému přístupu k datům super-satelitu, který nezákonně pozoroval činnosti kantorů. Tamní, nyní propuštěný, vedoucí bezpečnosti říká:

"Tož, to bylo něco, tohléto. Totální chaosnice. Si nemůžu ani vysvjétlit, jak se k tému došlo. Nějací hekéráci, povídám. Tož hrůza."[fn:1]

Je však veřejným tajemstvím, že porušení pravidel se dopustila paní Lajdová, momentální a evidentně i budoucí vedoucí žebříčku /závodu/. Jako jediná chyběla na zasedání, rozhodnuvši se před měsíci, že její přítomnost nebude nadále potřeba a že přímý hologramový přenos bohatě postačí, a kromě toho se neobtěžovala podobná nařčení vyvracet.

A přitom to je právě ona, kdo přebírá kontrolu nad /závodem/. Nedávno vyhlásila dekret, jímž nařizuje všem závodníkům platit poplatky předsedovi Rady Odvážných, kterým je ona sama. Platit mohou penězi či /závodními/ hlasy na její soukromý účet, jehož číslo je veřejnosti neznámo.

Tsunami pobouření, které následovalo, bylo předvídatelné a přitom zamezitelné. Otakar Pátek, odborník na práva /závodu/, se vyjádřil takto:

"Věříme-li, že paní Lajdová se zmocnila vedení díky podpoře Spolkové Bankovní Federace[fn:2], mohli ostatní členové Rady jednoduše sesadit její vládu. Anonymní kantor navrhl hlasování o snížení vlivu banek, ale většina učitelů se rozhodla, že se jim stálý příval peněz líbí, a zamítli. Kdyby tak neudělali, přišla by Lajdová o svou mocenskou základnu a neměla by teď možnost takto zneužívat svého postu."

O zneužívání rozhodně jde. Ihned po vyhlášení dekretu zakázala učitelům opouštět sídla bez povolení[fn:3] a převzala oficiální kontrolu nad super-satelitem, aby mohla jejich pohyb kontrolovat. Data teď volně proudí do jejího sídla, které je stále veřejnosti zcela neznámo.

Její armádní síly, které přejmenovala na Jednotky Zkázy, působí problémy. Na armádních operacích posledních dní došlo k sabotáži a Lajdová nedrží v tajnosti, že se poohlíží po nových rekrutech. Čirou náhodou na světlo vstoupila nově vzniklá armáda pana Horkého, přecvičená z jeho biografů, a pan Horký se dal slyšet, že jim nechce velet věčně.

Mezitím /závod/ pokračuje, ale s náskokem paní Lajdové ztrácí pořadí význam. Za zmínku stojí paní Jakešová, která je plně zabrána do pokračování Tónů smrti, točeného procesem Motion Caputre[fn:4]. Nebude trvat dlouho a z Dvaceti statečných zmizí.

Jedinou další zajímavou osobou je paní Zemánková, která se ostře ohradila proti vznikajícím precedentům a bojuje proti vlivu paní Lajdové, i když při hlasování o vlivu banek stála pevně na straně statusu quo. Pozoruhodná je proto, že den po jejím vyjádření jí tři banky odmítly poskytnout prostor pro hlasy v /závodě/, čímž porušily Dohodu o poskytnutém prostoru. Odborníci ukazují na Lajdovou. 

#+begin_example
1. Zdenka Lajdová
2. Dagmar Kolářová
3. Dana Kubešová
4. Lenka Vývodová
5. Dušan Rychnovský
6. Marie Vávrová
7. Ludmila Malá
8. Jiří Šeiner
9. Věra Zemánková
10. Gustav Havell
11. Hana Mužíková
12. Jana Horáková
13. Jiří Lysák
14. Radovan Langer
15. Ivo Macháček
16. Martina Hapalová
17. Marta Křenková
18. Jan Menšíková
19. Taťána Jakešová
20. Elisie G’uaun Ebbe
#+end_example
** Rozhovor
* Korespondent
* Lifestyle
** Karlos-čepice
** Kaňonskop
* Šeiner
** Špeh
** Lekce bankomata

* Poznámky

[fn:1] Přepsáno a přeloženo z jeho rodné huttštiny.

[fn:2] Věříme.

[fn:3] Toto vedlo k rozsáhlému rekrutování majordomů a mistrů služebníků, protože ani nakoupit si učitelé nesmí. Všech sedm a půl tisíce kantorů si pořídilo domácí kino, tělocvičnu, bazén a saunu, čímž zároveň zvýšili akcie firmy /Vše doma jako venku/ a vyprázdnili její sklady.

[fn:4] Najděte si to.
