# -*-eval: (setq-local org-footnote-section "Poznámky"); eval: (setq-local default-justification 'full); eval: (auto-fill-mode 1); eval: (toggle-truncate-lines); eval: (set-input-method "czech-qwerty"); eval: (set-register ?\' "“"); eval: (set-register ?\" "„");eval: (set-register ? "M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S."); eval: (set-register ? "■"); eval: (set-register ? "Der Weiderhohlle Flüsemschliessem");-*-
:stuff:
<style:style style:name="InterviewSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="3" fo:column-gap="0.497cm">
<style:column style:rel-width="21845*" fo:start-indent="0cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style style:name="NormalSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="2" fo:column-gap="0.998cm">
<style:column style:rel-width="32767*" fo:start-indent="0cm" fo:end-indent="0.499cm"/>
<style:column style:rel-width="32768*" fo:start-indent="0.499cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style          style:name="EditorialSect"         style:family="section">
<style:section-properties                  text:dont-balance-text-columns="true"
style:editable="false">   <style:columns    fo:column-count="2">   <style:column
style:rel-width="3401*"      fo:start-indent="0cm"     fo:end-indent="0.499cm"/>
<style:column          style:rel-width="6237*"         fo:start-indent="0.499cm"
fo:end-indent="0cm"/>        </style:columns>        </style:section-properties>
</style:style>

#+OPTIONS: ':t \n:nil f:t date:nil <:nil |:t timestamp:nil H:nil toc:nil num:nil d:nil ^:t tags:nil
# tags		Toggle inclusion of tags
# '			Toggle smart quotes
# \n		newline = new paragraph
# f			Enable footnotes
# date		Doesn't include date
# timestamp Doesn't include any time/date active/inactive stamps
# |			Includes tables.
# <			Toggle inclusion of the creation time in the exported file
# H:3		Exports 3 leavels of headings. 4th and on are treated as lists.
# toc		Doesn't include table of contents.
# num:1		Includes numbers of headings only, if they are or the 1st order.
# d			Doesn't include drawers.
# ^			Toggle TeX-like syntax for sub- and superscripts. If you write ‘^:{}’, ‘a_{b}’ is interpreted, but the simple ‘a_b’ is left as it is.
---------------------------------------------------------------------------------------------------------------------------------------
#+STARTUP: fnadjust
# Sort and renumber footnotes as they are being made.
---------------------------------------------------------------------------------------------------------------------------------------
#+OPTIONS: author:nil creator:nil
# Doesn't include author's name
# Doesn't include creator (= firm)

#+ODT_STYLES_FILE: "/home/oscar/Documents/Monte-Karlos/odt vzor/MonteKarlosNěkdeník1-2020.ott"
:END:
#+TITLE: MONTE KARLOS NĚKDENÍK
#+SUBTITLE: 
Vítejte v Monte Karlos, 
#+ODT: <text:section text:style-name="EditorialSect" text:name="Editorial">
* 2/2019
Ročník XXVIIII

*Adresa redakce:* Karlosova 77, 000 03 Monte Carlo 4

*E-mail:* EmailNoReply@server.mok

*Zákaznická linka:* 0004 892 223 03E

*Šéfredaktor:* Alžběta Ašelová

*Manažer redakce:* Jiří b'Ačkora

*Zástupce šéfredaktora:* Hobbo Habán

*Fotograf:* Alexandra Dimitrij von Dieseldorf

*Grafická úprava:* Tara Kočí

*Obrazová redakce:* Honza Kůň

*Rozhovor:* Karlos Žebatý, Lubomír Lečko

*Politická recenze:* Olšana Kupé

*Móda:* Šlapeboso Elle'Gante

*Editoři:* 

*Věštec:* Theodrios Appol-Théby

*Vydavatel:* Monte Karlos Inc. a. s.r.o. a spol©

*Brand manager:* Karlos Žebatý

*Sociální poradce:* Lightningh Danger

*Sociální podpora:* Anna Oleš

*Inzerce:* Many Hrabal

*E-shop:* nakupsisam.cz

*Tiskne:* individuálně

*Korespondent:* 

*Vyšetřovatel:* Sir Daniel Jonathan Pace

*Rozšiřují:* google.com
* Editorial                                                             :200:


Alžběta Ašelová, šéfredaktor
#+ODT: </text:section>
* Zprávy                                                                :350:
:news:
Topic [fish in heating]
Designing principle [new house; fish are a feature; we're selling]
Random thing [this stuff is normal in Ukraine since 1976]
Story [Housing agency struggling to sell the houses]
Characters [salesmen, CEO]
Voice [author eats fish]
Logistics of story [public reaction; history of product;...]
Quotes, vision, assessment
:END:
#+ODT: <text:section text:style-name="NormalSect" text:name="Zprávy">
** Třetí světová
„Budeme mít  největší jméno jídla na  světě. Bude to ohromné  jméno, které ještě
nikdo nikdy neměl. Takové jméno, to vám povídám, to tu ještě nebylo.“

Tato slova vyřkl  prezident Donald Trunp na jednom se  svých tradičních sjezdů v
Kalifornii,  poté, co  mu jeho  poradce oznámil,  že mají  k večeři  španělského
ptáčka.  Prezident  Trump  se  rozzlobil na  Theodora  Roosevelta,  že  nenechal
vynaleznout vlasní jídlo s „amrerický“ ve  jméně, a tímto výrokem se zavázal, že
situaci napraví.

Čínská vláda se  doslechla o jeho plánech  a zavázala se, že  ho nenechá vyhrát.
Japonsko,  ve snaze  předehnat kulturně  Čínu, se  přidalo rovněž,  což zapojilo
Jižní Koreu, následně Severní, to  přilákalo pozornost NATO. Tato byla opětována
pozorností Ruského impéria  a následně Ukrajiny jako pomstu Rusku  za Krym. Na v
poslední době  nečinném politickém  poli světa  se tak  rozjel závod  o dobývání
vlivu v oblasti kuchařské.

Ostatní,  menší státy  jako  Holandsko,  Chorvatsko či  Austrálie  se do  závodu
přidali ze zvyku.

Trump  ihned skočil  po  „americkém hamburgru“.  Německo mu  ho  rádo nechalo  a
soustředilo svou energii na „německou  pizzu“, kterou vyšoupli Itálii pod nosem.
Rusko bylo diskvalifikováno /Radou všeobecně  kuchařskou/, protože už mají ruská
vejce, načež Putit  jejich rozhodnutí ignoroval a zamluvil  si „ruskou anglickou
slaninu“.  Velká Británie  se nenechala  zahambit  a agenti  MI6 ukradli  jejich
spojenci - Číně - nudle.

Turecko se rozhodlo neangažovat a vyhlásilo neutralitu. Vše, říkají, jen aby jim
zůstal turecký med.  Norové se spojili se Švědskem a  společně přemluvili Finsko
ke spolupráci. Dělají tak, aby čelili jižnímu nátlaku v podobě balkánského sýra,
a zařídili  si „skandinávský buřt“. Balkán  do protiútoku poslal řecký  jogurt a
řecký salát, čímž Skandinávii totálně odrovnal.

Češi se zatím  pyšní moravským vrabcem, ale  vyjádřili se, že by  rádi dostali i
českého  pštrosa a  slezskou husu.  To  je problém,  neboť husa  je již  zabrána
Poláky, kterří se jí nehodlají vzdát. Probíhají rozsáhlá vyjednávání přes Skype,
ale osud Vyšegrádské čtyřky visí na vlásku.

V tom  všem zmatku si  Argentina mne ruce,  protože skoupila bezmála  dvacet pět
stovek receptů na černém trhu a má  teď téměř neomezenou smlouvací moc. Kanada i
Madagaskar už s nimi  uzavřeli dohodu o dovozu zbraní a  munice výměnou za malou
část jejich  skladu a Mexiko  zvažuje skoupit od  nich hranolky, než  je dostane
Trump, a pomstít se mu tak za tu Zeď.

Argentině v počtu zásob jako jediný vzdoruje Monte Karlos. Nejsme sice stát, ale
to  je  nám jedno.  Jsme  ochotni  smlouvat  o  podmínkách prodeje,  ale  předem
vyhlašujeme, že od  dnešního odpoledne se po celém světě  bude prodávat Karlosův
kebab.
** Příště uvidíte
:pojmy:
muž světla: ŠEINER
žena (své) Země: ZEMÁNKOVÁ
vzpomínka: STARÝ SYSTÉM ZÁVODU
nebeský kůň: DEATH STAR
: LAJDOVÁ
mrtví hrdinové: KUPÉ
hrob dávných nepřátel: DŮM PÁLKOVSKÉ
postrach zapomněný: ZÁCHELOVÁ
knihy (dosud) nenapsány: UČEBNICE DĚJEPISU V BUDOUCNOSTI
Ruka trýzně; Našeptávač; Sok rozumu/pravdy; On, jejž můžeš pouze přežít: LYSÁK
Temná síť: DARK WEB
(odpověď/spása/pomoc) ve hvězdách: PES
Kde se potká živel s živlem: ARÉNA
První vzdor: VŠICHNI SE SPOJÍ PROTI LYSÁKOVI
:END:

#+ODT: </text:section>
* Závod
#+ODT: <text:section text:style-name="NormalSect" text:name="Závod">
** Vývoj                                                                :400:
KKL, vojensko-vymahatelská odnož M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S., znovu zasahuje.
Přes všechny své snahy odradit učitele od používání armád Mezinárodní Úřad stále
čelí  jistým nechápavým  jedincům, kteří  se  svých bojovníků  drží zuby  nehty.
Minulou sobotu  provedla KKL druhý  největší vojenský  zásah v dějinách  šachu a
vyloučila ze závodu tři stovky učitelů.

Už několik měsíců shromažďovala KKL  informace o nebezpečných individuích, kteří
podle  jejich zdrojů  stále  přechovávali armády  zakázané  začátkem roku.  Tyto
zdroje jsou při nejlepším pofidérní, ale KKL trvá na tom, že se jim dá věřit. Po
bezmála  čtvrt  roce  špionáže  se   jim  podařilo  identifikovat  ony  jedince,
slavnostně je popravit a jejich zbytky hodit lvům.

Tento  čin vyvolal  v široké  veřejnosti popuzení  a odpor.  Prý není  důvod pro
M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. přechovávat smečku lvů v civilizovaném světě.

KKL  oznámila, že  při  příštím  odhalení používání  nezákoných  sil nebude  tak
shovívavá. I přes to se ukazuje,  že některým lidem zkrátka není pomoci. Spojené
vojenské  jednotky Úsvit  započali pochod  mongolskými pláněmi,  v čele  s třemi
kantory neznámé identity. Co je jejich  cílem nevíme, stejně jako netušíme, proč
by riskovali osud  popravených. Monte Karlos Někdeník měl původně  v plánu najít
je pomocí našeho ultra-mega satelitu, ale báli  jsme se úniku informací do KKL a
nechtěnému ovlivnění závodu.

Jak se ukázalo, báli  jsme se oprávněně. V Kanadě učetel  McKay využil situace a
podal  KKL anonymní  typ na  jeho  spolupracovnici Carterovou,  která podle  něj
vlastnila skupinu osmi  mariňáků. KKL zasáhla bleskově a  osudu Carterové raději
pomlčíme pro případ, že by Monte  Karlos Někdeník četlo dítě mladší dvaapadesáti
let. McKayův čin se dostal na  světlo veřejnosti díky jeho vlastní stupiditě. Na
svém Facebooku prohlásil, že se konečně zbavil svého největšího nepřítele a nyní
se připravuje na Dvacet statečných. Pomineme-li  to, že Dvacet statečných jsou z
velké části  pohřešovaní, tento komentář  mu způsobil nemalé potíže  s Kanadskou
vládou. Byl zbaven čestného titulu Kn.  (Kantor) a vržen do chladného, hlubokého
vězení, odkud není úniku.

KKL ohlásila, že co  si Kanada dělá se svými učiteli, do  toho jí mluvit nebude,
ale každá  informace o ilegálních  vojácích, zejména pak o  Spojených vojenských
jednotkách Úsvit,  bude vítána. Máte  prý kontaktovat  klientskou linku KKL  i v
případě pouhého podezření.

Monte Kalos shromažďuje  informace, jak jen může, aby napomohl  celé věci k tomu
novinářsky nejzajímavějšímu konci.
** Postupy v žebříčku                                                   :400:
Zmatek! Chaos! Neznámo! Dvacet statečných se rozpadlo! Co budeme dělat?!!

Po hromadném  zmizení učitelů  z Der  Weiderhohlle Flüsemschliessem  čelí Dvacet
statečných nepříjemným  změnám. Z původní  vedoucí dvacítky zbývá už  jen pohých
osm učitelů,  kteří se uráčili  nezmizet. Jejich  přítomnost v pevnosti  je nyní
hlídána pečlivěji, než  kdy dříve. Zatím byl zbytek  Dvaceti statečncých obsazen
zcela novými jmény.  Jmény, která nikoho nezajímají, jako  Ošumpraši Škrobe Kaši
nebo Aladíme  Sobeprostje B,  Monte Karlos Někdeník  tak ani  neposkytl žebříčej
jejich umístění. Protože jsou všem ukradení.

Ukradení jsou  ale i  M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. Jeden  z nich,  jehož jméno
jsme ani neměli čas si zapamatovat, se  už z hradu ztratil, ale nikoho nenapadlo
zajímat se  o něj natolik, aby  jeho zmizení vyšetřovali. Osm  zbylých původních
členů zůstává  pohromadě a  odmítá se  věnovat nově  příchozím, s  výjimkou paní
Kubešové,  která si  už udělala  několik  nových známostí  mezi svými  čerstvými
kolegy.

Vyšetřování  zatím probíhá  v plném  proudu. Paní  Malá oznámila,  že našla  síť
tajných  chodeb v  bunkru, kde  všichni  přespávali, a  hypotetizuje, že  těmito
chodbami  byli uneseni  všichni učitelé  v posledních  týdnech. Navrhla  opustit
prostor a přestěhovat  se na Náměstí Míru a Pokoje,  kde teď Skálopevná osmička,
jak se jim začalo na internetu  říkat, přespává pod celtou velikosti fotbalového
stadionu,  všichni v  dohledu všech  ostatních.  Paní Lajdová  se drží  stranou,
ačkoli ani ona neodmítla bezpečí společného bydlení.

Pan  Hevell se  nechal slyšet,  že  spát pod  jednou  střechou se  jim už  jedou
nevyplatilo, takže by to možná neměli dělat, ale nemluvil předem dohodnutou řečí
a nikdo mu tak nerozumněl. Paní Křenková každý večer vypráví strašidelné history
z mládí,  většinou s tématem  únosu či  zmizení. Pana Rychnovského  její příběhy
náramě  baví  a  přidává  svou   trošku  do  mlýna  soustavným  strašením  svých
spolu-spáčů za světla měsíce.

Paní Rotreklová  s paní Malou  tráví značný čas  spolu mimo doslech  ostatních a
řeší  něco, co  by slušný  čtenář  snad ani  slyšet  nechtěl. Jediný,  kdo se  v
současné situaci  nechová podezřele, je  paní Kolářová,  což na jí  vrhlo světlo
podezření silnější, než na všechny ostatní.

Kvůli  nedostatku  jiných  možností  musel Monte  Karlos  limitovat  svůj  výběr
pozvaných osobností. Jak už bylo  zmíněno, noví učitelé nikoho nezajímají, takže
byl postaven  před otázku, zda  pozvat Křenkovou (to určitě),  Kubešovou (zrovna
tak), či někoho,  kdo už v Monte  Karlos byl. Netřeba říkat, že  paní Lajdová je
zcela vyloučena a Malá a Rotreklová byly obě nadávnými hosty. Výběr byl jasný...
#+ODT: </text:section>
** Rozhovor - „“

#+ODT: <text:section text:style-name="InterviewSect" text:name="Interview">
*** Kampaň
*** Rychlá střelba
*** Korespondence
*** Závěrečný proslov

#+ODT: </text:section>
** Hodnocení odborníka                                                  :350:
#+ODT: <text:section text:style-name="NormalSect" text:name="Hodnocení">

#+ODT: </text:section>
* Korespondent - 
* Lifestyle
Módní sekce Monte Karlos Někdeníku vám přináší 

* Vyšetřování
** Dokumenty
** _Část první: Nepřítel za branami_
*** 
* Poznámky
