# -*-eval: (setq-local org-footnote-section "Poznámky"); eval: (setq-local default-justification 'full); eval: (auto-fill-mode 1); eval: (toggle-truncate-lines); eval: (set-input-method "czech-qwerty"); eval: (set-register ?\' "“"); eval: (set-register ?\" "„");eval: (set-register ? "M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S."); eval: (set-register ? "■"); eval: (set-register ? "Der Weiderhohlle Flüsemschliessem");-*-
:stuff:
<style:style style:name="InterviewSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="3" fo:column-gap="0.497cm">
<style:column style:rel-width="21845*" fo:start-indent="0cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style style:name="NormalSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="2" fo:column-gap="0.998cm">
<style:column style:rel-width="32767*" fo:start-indent="0cm" fo:end-indent="0.499cm"/>
<style:column style:rel-width="32768*" fo:start-indent="0.499cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style          style:name="EditorialSect"         style:family="section">
<style:section-properties                  text:dont-balance-text-columns="true"
style:editable="false">   <style:columns    fo:column-count="2">   <style:column
style:rel-width="3401*"      fo:start-indent="0cm"     fo:end-indent="0.499cm"/>
<style:column          style:rel-width="6237*"         fo:start-indent="0.499cm"
fo:end-indent="0cm"/>        </style:columns>        </style:section-properties>
</style:style>

#+OPTIONS: ':t \n:nil f:t date:nil <:nil |:t timestamp:nil H:nil toc:nil num:nil d:nil ^:t tags:nil
# tags		Toggle inclusion of tags
# '			Toggle smart quotes
# \n		newline = new paragraph
# f			Enable footnotes
# date		Doesn't include date
# timestamp Doesn't include any time/date active/inactive stamps
# |			Includes tables.
# <			Toggle inclusion of the creation time in the exported file
# H:3		Exports 3 leavels of headings. 4th and on are treated as lists.
# toc		Doesn't include table of contents.
# num:1		Includes numbers of headings only, if they are or the 1st order.
# d			Doesn't include drawers.
# ^			Toggle TeX-like syntax for sub- and superscripts. If you write ‘^:{}’, ‘a_{b}’ is interpreted, but the simple ‘a_b’ is left as it is.
---------------------------------------------------------------------------------------------------------------------------------------
#+STARTUP: fnadjust
# Sort and renumber footnotes as they are being made.
---------------------------------------------------------------------------------------------------------------------------------------
#+OPTIONS: author:nil creator:nil
# Doesn't include author's name
# Doesn't include creator (= firm)

#+ODT_STYLES_FILE: "/home/oscar/Documents/Monte-Karlos/odt vzor/MonteKarlosNěkdeník1-2020.ott"
:END:
#+TITLE: MONTE KARLOS NĚKDENÍK
#+SUBTITLE: 
Vítejte v Monte Karlos, 
#+ODT: <text:section text:style-name="EditorialSect" text:name="Editorial">
* 2/2019
Ročník XXVIIII

*Adresa redakce:* Karlosova 77, 000 03 Monte Carlo 4

*E-mail:* EmailNoReply@server.mok

*Zákaznická linka:* 0004 892 223 03E

*Šéfredaktor:* Alžběta Ašelová

*Manažer redakce:* Jiří b'Ačkora

*Zástupce šéfredaktora:* Hobbo Habán

*Fotograf:* Alexandra Dimitrij von Dieseldorf

*Grafická úprava:* Tara Kočí

*Obrazová redakce:* Honza Kůň

*Rozhovor:* Karlos Žebatý, Lubomír Lečko

*Politická recenze:* Olšana Kupé

*Móda:* Šlapeboso Elle'Gante

*Editoři:* 

*:* 

*Vydavatel:* Monte Karlos Inc. a. s.r.o. a spol©

*Brand manager:* Karlos Žebatý

*Sociální poradce:* Lightningh Danger

*Sociální podpora:* Anna Oleš

*Inzerce:* Many Hrabal

*E-shop:* nakupsisam.cz

*Tiskne:* individuálně

*Korespondent:* 

*Vyšetřovatel:* Sir Daniel Jonathan Pace

*Rozšiřují:* google.com

/Monte Karlos Někdeník/ byl založen  skupinou černých nosorožců afrických v létě
roku  1989.  Jeho  stránky  byly   poznamenány  takovými  autory  jako  Alexandr
Malinovský, Jack  O'Clock a Veronika Oškalová  a všeobecnému ohlasu se  těší již
třetím rokem  pod brilantním  vedením šéfredaktorky  Alžběty Ašelové©.  Stojí na
železobetonových základech, neboť všichni zaměstnanci od grafiků přes editory po
prachbídné korespondenty  se řídí  všestrannými, nesmrtelnými  pravidly slušného
chování.
* Editorial                                                             :200:


Alžběta Ašelová, šéfredaktor
#+ODT: </text:section>
* Zprávy                                                                :350:
:news:
Topic [fish in heating]
Designing principle [new house; fish are a feature; we're selling]
Random thing [this stuff is normal in Ukraine since 1976]
Story [Housing agency struggling to sell the houses]
Characters [salesmen, CEO]
Voice [author eats fish]
Logistics of story [public reaction; history of product;...]
Quotes, vision, assessment
:END:
#+ODT: <text:section text:style-name="NormalSect" text:name="Zprávy">
** Porušení dohody Duny
Silniční války v druhé polovině šedesátých  let byly krutou a nepříjemnou etapou
naší společné historie. Ke konci pohltila statisíce životů nejen lidských, nýbrž
i protivníkových.  Dohoda Duny  představovala mírovou  smlouvu mezi  všemi třemi
válčícími stranami  - lisdtvem, Unií  asfaltu, železa  a betonu a  štěrkem. Naši
nepřátelé tehdy přistoupili na lidské  podmínky souznění a společně uzavřeli mír
na půdě neutrálního  písku v Gobi. Následovalo vytvoření dohody  Duny, která mír
stvrzovala.

Podle  dohody,  mimo  jiné,  jsou  asfalty  zavázány  ke  spolupráci  ve  věcech
silničních výměnou za pravidelnou (a nadměrnou) dodávku ananasu. Jistý asfalt na
T-křižovatce na  západní Ukrajině se  však nedávno odhodlal napadnout  tuto námi
poskytnutou  symbiózu. V  noci  z úterý  na pátek  bez  varování odmítl  povolit
přepravu tří dodávek přes střed křižovatky. Řidiči tak byli v rozpacích.

„Já  nejsem  žádnej právník,“  říká  pan  Chrastivějský,  který jím  od  pohledu
opravdu, ale  opravud není,  „ale znám  trochu historie.  DD nikdy  nepočítala s
takovou situací, jestli  se tam můžu vyjádřit.“ Pan  Chrastivějský má překvapivě
pravdu. Podle  dohody nesmí člověk  nutit asfalt dělat,  co sám dělat  nechce, v
souladu  s Deskou  základních materiálních  práv.  Podle stejné  dohody je  však
asfalt  povinen  sloužit,  chci  říct  asistovat nám  na  cestách.  Dohoda  Duny
nestanovuje žádný aparát pro řešení takovéto situace.

Mezinárodní  sdružení asfaltů  se distancovalo  od názorů  tohoto asfaltu.  Jeho
předleža praví:  „Je zřejmé, že  asfalt na křižovatce  E125 a R554  trpí jakousi
poruchou mysli  a MSA je  toho názoru, že  by mu neuškodila  celková přestavba.“
Štěrk se vzápětí distancoval od celé situace a odsypal se ze záběru kamer.

Zatím  nevděčný  asfalt na  křižovatce  odmítá  podat hlášení.  Jeho  stanovisko
ohledně přejezdu  přes „jeho území“, jak  tomu panovačně říká, se  nijak nemění.
Pokusy o mírové řešení selhaly ještě dřív, než začaly, a ukrajindká policie byla
nucena  uzavřít   celou  oblast   a  vyhraničit  několikametrový   objezd  kolem
inkriminované křižovatky. MSA  si následně začalo stěžovat, že  na jejich asfalt
jsou pokládána příliš těžká břemena, a vyžaduje okamžitou nápravu.

Na  rozdíl od  své  vlády začala  asfaltská komunita  s  asfaltem na  křižovatce
sympatizovat. Mnozí  se teď  ptají, jestli  je dohoda  Duny stále  prospěšná pro
původní Unii. Nevděčníci[fn:1]■
**                                                                               

#+ODT: </text:section>
* Závod
#+ODT: <text:section text:style-name="NormalSect" text:name="Závod">
** Vývoj                                                                :400:
Mezinárodní Úřad  pro Úplnou a  Asertivní Spolupráci Spojených Států  Místních i
Zahraničních za Účelem Světového Míru, Obchodu  a Výměny Služeb měl v posledních
týdnech napilno. Ve světle mizících  učitelů Dvaceti statečných (dvaceti nejvýše
postavených učitelích v závodě o /nejvyššího vůdce všeho učitelstva) se rozhodli
provést důkladné  vyšetřování níže  situovaných kantorů přihlášených  do závodu.
Jejich cílem bylo objevit, kdo z nich může stát za těmito útoky.

Pokusy Mezinárodního  Úřadu byly  zcela bez  výsledku na  poli vyšetřovatelském,
přinesly zato plody  v oblasti jiné. Podrobným zkoumáním míst  3042 až 3990 byli
objeveni dosud  přehlížení učitelé z  Guatemalských jižních kmenů. Na  rozdíl od
svých aftických  protivníků, nemají  tito patřičné  doklady potřebné  k doložení
svého  učitelství. Mezinárodní  Úřad  zahájil další  vyšetřování  do celé  věci,
posunul ho na dobu neuričtou, protože se právě soustředil na mizející kantory, a
tváří v tvář  svému neúspěchu se k  nim vrátil s vervou  poražených a odhodláním
těch, kterým hrozí pokles ve veřejném mínění.

Političtí  odborníci  praví,  že  jejich  zásah do  života  Guatemaly  je  zcela
pochopitelný. Musí  prý světu  ukázat, že přestupky  proti pravidlům  se nebudou
tolerovat. Celá situace  je tedy o to  ošemetnější, že nikdo na  Úřadě neví, kdo
kantory unáší, a nemůže tudíž nikoho potrestat.

„Může se stát,“  řekl Obřísko Šuplijský, „že se dostaneme  k symbolickému trestu
pachatelů. Úřad si někoho vybere a  potrestáho ho exemplárně, bez ohledu na jeho
vinu. Co vidíme v Guatemale je jen začátek.“

A co že to vidíme v Guatemale? Celkem devět tamních okultních lídrů je podrobeno
důkladným prověrkám a přezkoumáváním, aby se  Úřad ujistil, že se skutečně jedná
o učitele.  Vyšetřující si Někdeníku  stěžují na obtížnost svého  úkolu, protože
M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. nikdy  nestanovilo, co všechno musí  kantor umět,
aby kantorem byl, a  od kdy je jeho kantorství dostatečné  pro příjem do závodu.
Tyto otázky měly prý být vyžešeny před jejich přijetím do závodu v minulém roce.

Mezi ostatními  kantory se šíří  pobouření. Pan Komenský, jako  seniorní poradce
Úřadu, se  vyjádřil, že dokud neučí  národ, nemají, co v  soutěži dělat. Obi-Wan
Kenobi, nejproslulejší spirituální učitel, zastává  názor opačný, a to že jejich
příspěvky  světovému učení  mohou přinést  potřebnou dávku  osvícení. Profesorka
McGonagallová se zdrřela komentáře.

Osud  guatemalských rádoby  kantorů je  nejistý. Vše  záleží na  tom, jestli  se
podaří najít  pachatele únosů. Lidé si  přitom nejsou jisti, že  se tento skrývá
mezi kantory. Nezbývá, než čekat.
** Postupy v žebříčku                                                   :400:
#+BEGIN_EXAMPLE
1. Ludmila Malá
2. Jiří Šeiner
3. Dana Kubešová
4. Dagmar Kolářová
5. Dušan Rychnovský
6. Martina Rotreklová
7. Zdenka Lajdová
8. Věra Zemánková
9. Lenka Vývodová
10. Taťána Jakešová
11. Marie Vávrová
12. Jana Horáková
13. Marta Křenková
14. Hana Mužíková
15. Elisie G’uaun Ebbe
16. Josef Král
17. Ivo Macháček
18. Gustav Havell
19. Jiří Lysák
20. Otakar su-džima a'Líma
#+END_EXAMPLE
Zatímco se  M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. snaží  zastavit mizení  své autority,
učitelé  Dvaceti statečných  se  snaží  zastavit mizení  sebe  sama. Po  zmizení
tehdejšího vůdce  žebříčku, pana Šeinera,  který se  propadl o jedno  celé míst,
začali společně  stavět bunkr,  do které  se plánují  schovat. Jenpilněji  se na
práci podílí paní Rotreklová a Malá, které jsou si obě jisté, že útočníci půjdou
brzy po  nich. Jejich  ustavičné popohánění  ostatních jim  vysloužilo přezdívku
diktátorky, ale vesměs se zdá býti účinné.

Paní Kubešová ke  své smůle nedokázala využít výhody  poskutnuté svým špehováním
na  někdejší /Pálkovská  squad/,  a  začase postupně  ztrácet  body. Její  místo
převzala paní  Malá, nemalou zásluhou  svého vystoupení  na Tlačence, a  ta byla
následně vynesena na místo první, když Šeiner Kubešovou následoval.

Ostatní zmizelí kantoři se potkávají  se stejným osudem. Macháček zažil největší
propad - celých  devět míst, ale Horáková ho těsně  následuje. Mužíková ztratila
dvě příčky, Vávrová rovněž a nejdéle  zmizelý pan Langer byl kompletně vystřídán
na poli Dvaceti statečných  Otakarem su-džimou a'Límou, severohavajskému učiteli
tance, kterému dal  Mazinárodní Úřad pět dní k dostavení  se do Der Weiderhohlle
Flüsemschliessem.

Zde je  nutno podotknout, že podle  stále platících pravidel jsou  všichni dosud
zmínění zmizelí  vyloučeni z  celého závodu,  ale M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S.
nehodlá  ztrácet  čas  vyřazováním  jejich  jmen z  žebříčku.  Prý  se  postupně
propadnou sami a nebudou dělat problémy.

Mluvíme-li ale  o zmizelích  učitelích, nesmíme  opomenout jistéha  pana Lysáka,
slavného učitele  tělocviku a dějepisu na  gymnáziu v Hranicích. Na  Moravě. Pan
Lysák si  vyžádal neplacené  volno od Der  Weiderhohlle Flüsemschliessem  a jako
důvod uvedl naléhavou  záležitost s hraničkou tělocvičnou.  Ačkoli jeho povolená
doba nepřítomnosti  ještě nevypršela,  neodpovídá na žádné  pokusy o  kontakt ze
strany svých  voličů, sponzorů, novinářů  ani Úřadu samotného. Jeho  nejbližší -
dva   medicimbálové  míče   -  se   domnívají,  že   dostal  vzkaz   od  únosce,
předstírajícího poruchu  v tělocvičnách, a  byl unesen. Veřejnost  zaplavil stav
bláznivého nadšení, ale rovněž strachu z budoucnosti závodu.

Kdo zůstává  nepříjemně klidný,  je paní Lajdová.  Přesněji řečeno,  její nemalé
rozhořčení pramení čistě  jen ze ztráty jejích bodů. Zatímco  ona voliče ztrácí,
paní Rotreklová  je nabírá (ku svě  jistě nemalé radosti) a  momentálně jsou obě
učitelky vedle  sebe. Na závěr ještě  dodáme, že kromě přehození  Rychnovského a
Kolářové je v žebříčku docela klidno.
#+ODT: </text:section>
** Rozhovor - „“

#+ODT: <text:section text:style-name="InterviewSect" text:name="Interview">
*** Kampaň
*** Rychlá střelba
*** Korespondence
*** Závěrečný proslov

#+ODT: </text:section>
** Hodnocení odborníka                                                  :350:
#+ODT: <text:section text:style-name="NormalSect" text:name="Hodnocení">

#+ODT: </text:section>
* Korespondent - Welcome to Moon!
Převzato z nezávislého extranetového serveru B-S ENQUETE

Když jsem před šesti týdny nalezl ve schránce pozvánku na otevření nového bistra
Moonlight se slibným názvem „Easter on  the Moon“, nebyl jsem nadšený. Ano, byla
pocta  ocitnout se  ve  dvacítce gurmet-reportérů,  vybraných  k účasti na  této
mimořádné  události, a  bylo úžasné  představit  si cestu  na odvrácenou  stranu
Měsíce,  kam jsem  se  vždy  toužil podívat,  ale  z pocty  samotné nakonec  nic
příjemného  nekouká,   nemáte-li  čas,   peníze  a   koneckonců  ani   moc  chuť
k zajišťování všech  náležitostí, které  s cestou na  Měsíc souvisí.  Kdo jednou
prošel martyriem shánění a ověřování  všech potřebných dokladů a potvrzení, věru
se do nich nežene podruhé – a moje propustka, kterou jsem před lety získal kvůli
letu  na restaurační  základnu  Brillat-Savarin  na Mysu  Bec  fin se,  bohužel,
ukázala  bezcennou,   neboť  servisní   společnost  Dossier,   patřící  majiteli
Brillat-Savarinu,  exterestrickému gastropodnikateli  André  Béovi, odmítá  dané
dokumenty předat jakékoli třetí straně.

Naštěstí mezinárodní vesmírná  agentura GASA nám byla ochotna pro  let na Catena
Lucretius,   kde   je   nové   bistro  situováno,   udělit   výjimku   z většiny
administrativních i  zdravotních pravidel.  Od této neobyčejné  benevolence GASA
neustoupila  ani po  obvyklých protestech  André Béa,  jenž si  již dlouhá  léta
pěstuje  v centrále  GASA vlivovou  pozici,  zastiňující  i pravomoci  samotného
jejího šéfa; jádrem roztržky mezi vesmírnou agenturou a předním transgalaktickým
investorem se ukázal  být, jako obvykle, střet Béových  podnikatelských zájmů se
zájmy agentury, která se v posledních  letech usilovně snaží rozbít Béův solaire
gastromonopol, čehož důkazem je,  koneckonců, samo zprovoznění bistra Moonlight.
Tento  malý,  ale   sympatický  podnik  patří  dosud   málo  známému  anglickému
podnikateli Bamesi Jondovi, který  je sice v oboru solaire-gastronomie naprostým
začátečníkem, ale jehož minulost je provázena množstvím těžko uvěřitelných mýtů,
legend  a dobrodružných  příběhů, o  nichž si  ani nejzasvěcenější  kruhy v GASA
nejsou jisty, nakolik  mohou být odrazem skutečnosti a nakolik  dílem odvážné PR
strategie.  V kuloárech  se proto  nikoli  náhodou  v souvislosti s  vybudováním
Moonlightu šeptalo, že GASA se  konečně povedlo najít na podnikatelskou aroganci
a neotřesitelnou pozici André Béa protiúder náležitého kalibru.

Nevelká lunární  provozovna, poskytující  jednoduché , ale  poctivé občerstvení,
byla v jihovýchodní části vnějšího valu  kráteru Hertzsprung na odvrácené straně
Měsíce, vybudována s finančním přispěním  britské společnosti Universal Exports,
pro  niž  Bames   Jond  v minulosti  pracoval  a  která,  jak   se  ukazuje,  má
v exterestrickém byznysu velké plány.  Propojení solidnosti britského kapitálu a
svobodomyslného podnikatelského  ducha připravuje  návštěvníkům již  při příletu
řadu příjemných překvapení od portrétu  britské panovnice nad vstupem po placení
výhradně britskými librami. Provozovatelé bistra vsadili i v jiných aspektech na
kvalitu a tradici: obsluhu obstarává výhradně mužský personál, v nabídce nechybí
lojový pudink a nápojovému lístku vévodí pravý lapsam se smetanou, servírovaný s
original  scottish   shortbread.  Ubytovací   kapacity  Moonlightu   jsou  zatím
limitované,  poskytují však  dostatek  soukromí a  pohodlí. Pokoje,  designované
v duchu  edwardovské estetiky,  jsou  vybaveny vším  dostupným komfortem,  který
naznačuje další možnosti rozvoje.

Jak ukázala mezinárodní vernisáž bistra Moonlight, André Béovi v prostoru, který
až dosud považoval za své výsostné působiště, vyrůstá zdatný protivník. Byl by o
to zdatnější,  pokud by se vyplnily  pokradmu šířené zprávy, jež  se objevily po
zdárném  uvedení podniku  do  provozu, že  za rok  v dubnu  zde plánuje  britská
panovnice Alžběta II. oslavit své 134. narozeniny. André Béovi by se tak konečně
postavil  soupeř,  který  by  –  po  dlouhých desítkách  let  –  mohl  být  jeho
exterestrickému monopolu skutečně nebezpečný.
* Lifestyle
Módní sekce Monte Karlos Někdeníku vám přináší 

* Vyšetřování
** Dokumenty
** _Část první: Nepřítel za branami_
*** 

* Poznámky

[fn:1] Neberte mě špatně. Já nejsem materialista. Můj nejlepší přítel ze střední
školy byl  kus chodníku. Ale když  si ti asfalti nedovedou  uvědomit, jakou čest
jim nabízíme, když je necháváme pro nás pracovat, co mám dělat?
