# -*-eval: (setq-local org-footnote-section "Poznámky"); eval: (auto-fill-mode 1); eval: (toggle-truncate-lines); eval: (set-input-method "czech-qwerty"); eval: (set-register ?\' "“"); eval: (set-register ?\" "„");eval: (set-register ? "M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S."); eval: (set-register ? "■"); eval: (set-register ? "Der Weiderhohlle Flüsemschliessem");-*-
:stuff:
<style:style style:name="InterviewSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="3" fo:column-gap="0.497cm">
<style:column style:rel-width="21845*" fo:start-indent="0cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style style:name="NormalSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="2" fo:column-gap="0.998cm">
<style:column style:rel-width="32767*" fo:start-indent="0cm" fo:end-indent="0.499cm"/>
<style:column style:rel-width="32768*" fo:start-indent="0.499cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style          style:name="EditorialSect"         style:family="section">
<style:section-properties                  text:dont-balance-text-columns="true"
style:editable="false">   <style:columns    fo:column-count="2">   <style:column
style:rel-width="3401*"      fo:start-indent="0cm"     fo:end-indent="0.499cm"/>
<style:column          style:rel-width="6237*"         fo:start-indent="0.499cm"
fo:end-indent="0cm"/>        </style:columns>        </style:section-properties>
</style:style>

#+OPTIONS: ':t \n:nil f:t date:nil <:nil |:t timestamp:nil H:nil toc:nil num:nil d:nil ^:t
# ' Toggle smart quotes
# \n		newline = new paragraph
# f			Enable footnotes
# date		Doesn't include date
# timestamp Doesn't include any time/date active/inactive stamps
# |			Includes tables.
# <			Toggle inclusion of the creation time in the exported file
# H:3		Exports 3 leavels of headings. 4th and on are treated as lists.
# toc		Doesn't include table of contents.
# num:1		Includes numbers of headings only, if they are or the 1st order.
# d			Doesn't include drawers.
# ^			Toggle TeX-like syntax for sub- and superscripts. If you write ‘^:{}’, ‘a_{b}’ is interpreted, but the simple ‘a_b’ is left as it is.
---------------------------------------------------------------------------------------------------------------------------------------
#+STARTUP: fnadjust
# Sort and renumber footnotes as they are being made.
---------------------------------------------------------------------------------------------------------------------------------------
#+OPTIONS: author:nil creator:nil
# Doesn't include author's name
# Doesn't include creator (= firm)

#+ODT_STYLES_FILE: "/home/oscar/Documents/Monte-Karlos/odt vzor/MonteKarlosNěkdeník1-2020.ott"
:END:
#+TITLE: MONTE KARLOS NĚKDENÍK
#+SUBTITLE: 
Vítejte v Monte Karlos, 
#+ODT: <text:section text:style-name="EditorialSect" text:name="Editorial">
* 2/2019
Ročník XXVIIII

*Adresa redakce:* Karlosova 77, 000 03 Monte Carlo 4

*E-mail:* EmailNoReply@server.mok

*Zákaznická linka:* 0004 892 223 03E

*Šéfredaktor:* Alžběta Ašelová

*Manažer redakce:* Jiří b'Ačkora

*Zástupce šéfredaktora:* Hobbo Habán

*Fotograf:* Alexandra Dimitrij von Dieseldorf

*Grafická úprava:* Tara Kočí

*Obrazová redakce:* Honza Kůň

*Rozhovor:* Karlos Žebatý, Lubomír Lečko

*Politická recenze:* Olšana Kupé

*Móda:* Šlapeboso Elle'Gante

*Editoři:* Andrew McTallas, Lobor Sko'madženta

*:* 

*Vydavatel:* Monte Karlos Inc. a. s.r.o. a spol©

*Brand manager:* Karlos Žebatý

*Sociální poradce:* Lightningh Danger

*Sociální podpora:* Anna Oleš

*Inzerce:* Many Hrabal

*E-shop:* nakupsisam.cz

*Tiskne:* individuálně

*Korespondent:* 

*Vyšetřovatel:* Sir Daniel Jonathan Pace

*Rozšiřují:* google.com

/Monte Karlos Někdeník/ byl založen  skupinou černých nosorožců afrických v létě
roku  1989.  Jeho  stránkami  byly poznamenány  takovými  autory  jako  Alexandr
Malinovský, Jack  O'Clock a Veronika Oškalová  a všeobecnému ohlasu se  těší již
třetím rokem  pod brilantním  vedením šéfredaktorky  Alžběty Ašelové©.  Stojí na
železobetonových základech, neboť všichni zaměstnanci od grafiků přes editory po
prachbídné korespondenty  se řídí  všestrannými, nesmrtelnými  pravidly slušného
chování.
* Editorial


Alžběta Ašelová, šéfredaktor
#+ODT: </text:section>
* Zprávy
#+ODT: <text:section text:style-name="NormalSect" text:name="Zprávy">
** Španělská mutace
Otec de'Galla, farář v kostele svaté  Anny v Barceloně, odhalil Někdeníku pozadí
nepříjemné politicko-památkářské situace. Otec  de'Galla upozornil na jev, který
v tu dobu již několikátým dnem probýhal nejen po celém Španělsku.

„Jak je známo,“ praví, „pro založení  nového města je třeba kostelní semínko. To
vláda zasadí a hnojí tři měsíce. Z něj vyroste malá kaple, která posléze dospěje
v kostel.“  Otec de'Galla  zde naráží  na středověký  postup praktikující  se ve
španělsky mluvících  zemích již  od dvanáctého  století. „V  posledních měsících
musela svatá  buňka -  amenius dominika  - zmutovat,  protože po  celé Barceloně
začaly závratně růst nové kostely.“

Otec Někdeníku  ukázal kostel na náměstí  sv. Anny. „Tohle není  můj kostel. Můj
kostel je za tím, schovaný.“

Zdá se, že v průběhu několika hodin  před branami kostela dokázal vyrůst druhý a
zcela zabarikádovat budovu původní. Není zdaleka jediným ve městě.

Otec de'Galla poslal petici na městský úřad, aby se situace vyřešila radikálními
opatřeními.  Radní  města byl  připraven  jednat,  ale Sbor  památkářů  amatérů,
mezinárodní  organizace pro  ochranu volně  vyrůstajících budov,  situaci značně
zkomplikoval.

„Listina základních práv a budov jasně praví, že volně vyrostlá budova nesmí být
zbourána,  neohrožuje-li ekonomický  růst,“ praví  Zachariáš Šťastný,  prezident
SPA. „Nikde není zmíněno, že by  situace byla jiná v průmyslových oblastech.“ Na
dotaz, co  si myslí  o teorii  mutujících svatých buňek,  se pak  vyjádřil pouze
písemně, a to tak, že nám neví neví.

I když urbaničtí biologové několikátým  rokem varují Švědskou královskou rodinu,
že starobylá praktika může přinést nepříjemnosti, náhlý růst budov nepředvídali.
Celé Španělsko  je tak zcela  nepřipraveno na  nával náboženství, který  ho nyní
čeká. Debaty o řešení situace se ale potáhnou měsíce a do té doby může být podle
některých odhadů postiženo přeš šedesát procent volného prostoru.

V Barceloně  se vyskytlo již několik  znatelných potíží. Celá čínská  čtvrť byla
pohlcena bazilikou sv. Petra a přilehlými zahradami a mnozí občané si stěžují na
vtěrné dřevořezby, schopné  jim přes noc zabarikádovat okna.  Do dnešního večera
došlo k  třem vážným konvercím a  jednomu fatalnímu selhání víry.  Otec de'Galla
zatím  zápasí s  konkurenčními  farnostmi  o účast  na  mších,  neboť věřící  se
rozprostřeli do nově  vyrostlých kostelů a vytváří tak  nestabilní prostředí pro
náboženství■
** Ryby v topení

#+ODT: </text:section>
* Závod
#+ODT: <text:section text:style-name="NormalSect" text:name="Závod">
** Vývoj
Zatímco  se dvacet  statečných  připravovalo na  tiskvou konferenci  přezdívanou
tlačenka, starali se zbylí uchazeči v  závodě, téměř osm tisíc učitelů, kteří si
již tlačenkou prošli, o své vlastní problémy. Zejména došlo ke sporům mezi KUS -
kantoří umělé společenství -, M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. a vládou v Chile.

Spory se  týkají dvou oblastí: sídla  budoucího nevyššího vůdce a  stavby arény,
která  byde použita  v  poslední fázi  výběru zmíněného.  V  posledním týdnu  se
několik KUSů najednou  a zcela nezávisle rozhodlo protestovat  proti oběma bodům
naráz.

KUS je  označení pro skupinu  kantorů, kteří se  rozhodli spojit síly  v závodě.
Důvody mohou  být různé -  politická nestabilita, nedostatek  hlasů jednotlivých
členů nebo  příliš silná konkurence. KUSy  se nesmí zaměňovat s  KBSy, kantořími
bláhovými společenstvími, která  se zásadně uzavírají mezi  dvojicí kantorů, kde
se  jeden druhému  zavazuje, že  bude-li zvolen,  vybere si  truhého jako  svého
pobočníka.  Bláhové  se  jmenují proto,  že  M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S.  sám
ohlásil, že pobočníkem může být pouze  někdo z prvních patnácti učitelů, to jest
těch, kteří  se dostanou do  arény (a přežijí).  KUS je jen  dočasné spojenectví
dvou a více  osob, založené s cílem  účelné pomoci a vědomím, že  se rychle zase
rozpadne. Asi jako politická strana. Velká pětka byla jedním takovým KUSem.

Ihned  po vyhlášení  závodu se  Chile  rozhodlo vystavět  vítězi malebné  sídlo.
Doufalo tak, že zvýší své místo na poli světového oblibu. Architekt Chobroščenko
Gister-Rotti přednesl své  plány v OSN 22.4. tohoto roku.  Několik KUSů se velmi
hlasitě ozvalo  na Twitteru, že  s jeho návrhem  principielně nesouhlasí a  že v
takovém sídle nehodlají žít. Mezi  důvody zařadily například nedostatek prostoru
pro koňskou dráhu,  nadměrné množství severních zdí a své  přesvědčení, že se na
ně stavba (v tuto dobu existující pouze v plánech) nepříjemně a vysmívavě dívá.

Ve  stejnou dobu  zveřejnil M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S.  své plány  vybudovat
arénu pod  vodní hladinou v  atolu Usmen  v Atlantiku. Toto  rozhodnutí vyvolalo
vlnu  pobouření v  KUSech  ze střední  Asie, které  si  stěžovaly na  nedostatek
finančních prostředků pro  přepravu na místo, alergie na  písečné pláže, kterými
je  Usmen  proslulý,  a  na  nedostatek  ohledu  na  fakt,  že  některá  tamější
náboženství  výslovně zakazují  pobývání  pod vodní  hladinou  déle než  dvanáct
hodin.

Karlos Žebatý celou  situaci shrnul nejlépe: „Nevím, proč si  stěžují. Stejně se
tam nedostanou.“
** Postupy v žebříčku
#+BEGIN_EXAMPLE
1. Jiří Šeiner
2. Zdenka Lajdová
3. Jana Horáková
4. Ludmila Malá
5. Dušan Rychnovský
6. Ivo Macháček
7. Dagmar Kolářová
8. Hana Mužíková
9. Dana Kubešová
10. Martina Rotreklová
11. Věra Zemánková
12. Marie Vávrová
13. Lenka Vývodová
14. Marta Křenková
15. Taťána Jakešová
16. Elisie G’uaun Ebbe
17. Josef Král
18. Radovan Langer
19. Gustav Havell
20. Jiří Lysák
#+END_EXAMPLE
Nad Der  Weiderhohlle Flüsemschliessem se  stahují metaforická mračna.  Na hradě
vládne nehostiná  nálada a kantoři  se začali  smykat do hloučků,  kdykoli spolu
něco probírají. Panuje nevyřčené pravidlo zákazu vycházení po deváté hodině a do
zahrad  se  odváží přinejmenším  ve  dvojicích.  Hradní televizní  štáb  bedlivě
monitoruje každý kout, ale až na problémy s vodovodními trubkami na skladě zatím
neobjevili nic nápadného.

Obyvatelé  Der  Weiderhohlle  Flüsemschliessem  se ale  mohou  radovat.  Všichni
zmizelí kantoři, Langer, Macháček, Horáková  a nově Mužíková, poznali komplikace
své nepřítomnosti na poviné tiskové  konferenci. I když jsou technicky vyloučeni
ze závodu - Mužíková, protože opustila hrad bez dovolení, a ostatní tři, protože
se  ani   nedostavili  -  technologické   křidlo  M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S.
opravuje chybu v systému, a všichni  jsou tudíž stále přítomni v žebříčku. Ústav
nás ubezpečuje, že do arény času dost, a všechno se zpraví.

Kantorům  se  i  tak  zachtělo   zvýšit  ochranu.  Počet  bodyguardů  se  zvíšil
dvanáctinásobně  a  Mezinárodní  ústav  poukazuje,   že  tento  čin  hraničí  se
shromažďováním  armád.  Paní   Křenková  se  dala  do   debat  obhajujících  své
rozhodnutí, což ji v žebříčku nijak neprospělo. Naopak paní Jakešová, tvrdohlavě
odmítající  jakékoli  nebezpečí,  získala  bonusové  body  za  nekonfliktnost  a
vystoupala o dvě příčky.

Tak  zvaná tlačenka  proběhla tiše  a neceremoniálně.  Monte Karlos  Někdeník si
zamluvil slíbené množství sedadel a  položil kantorům vámi zvolené otázky. Přímý
přenos celé události najdete na našem YouTube kanále.

Za zmínku  stojí tři  zásadní body toho  dne. My se  budeme zabývat  dvěma. Paní
Kubešová dosáhla  neočekávaného úspěchu,  když odpovídala  na otázku  „Co nemáte
ráda na matematice.“ Její  odpověd - trojčelenky - jí výstup  o tři příčky. Zato
Lajdová, kterou  celá akce  otravovala, se nezmohla  na kloudnou  větu. Odradila
publikum, když vešla do místnosti a oznámila, že všichni smrdí. Dále pak odmítla
odpovědět přímo  na jednoduché otázky  jako jak se  jí podařilo zajistit  si tak
dobré místo, když o její kampani veřejnost neví naprosto nic.

Výsledkem  jejího neúspěchu  se stala  rapidní ztráta  sponzorů a  propad o  dvě
místa, což ale podle odborníků není v žádném případě dost■
#+ODT: </text:section>
** Rozhovor - „“

#+ODT: <text:section text:style-name="InterviewSect" text:name="Interview">
*** Kampaň
*** Rychlá střelba
*** Korespondence
*** Závěrečný proslov

#+ODT: </text:section>
** Hodnocení odborníka
#+ODT: <text:section text:style-name="NormalSect" text:name="Hodnocení">

#+ODT: </text:section>
* Korespondent - 
* Lifestyle
Módní sekce Monte Karlos Někdeníku vám přináší 

* Vyšetřování
** Dokumenty
** _Část první: Nepřítel za branami_
*** 
* Poznámky
