# -*-eval: (setq-local org-footnote-section "Poznámky"); eval: (setq-local default-justification 'full); eval: (auto-fill-mode 1); eval: (toggle-truncate-lines); eval: (set-input-method "czech-qwerty"); eval: (set-register ?\' "“"); eval: (set-register ?\" "„");eval: (set-register ? "M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S."); eval: (set-register ? "■"); eval: (set-register ? "Der Weiderhohlle Flüsemschliessem");-*-
:stuff:
<style:style style:name="InterviewSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="3" fo:column-gap="0.497cm">
<style:column style:rel-width="21845*" fo:start-indent="0cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style style:name="NormalSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="2" fo:column-gap="0.998cm">
<style:column style:rel-width="32767*" fo:start-indent="0cm" fo:end-indent="0.499cm"/>
<style:column style:rel-width="32768*" fo:start-indent="0.499cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style          style:name="EditorialSect"         style:family="section">
<style:section-properties                  text:dont-balance-text-columns="true"
style:editable="false">   <style:columns    fo:column-count="2">   <style:column
style:rel-width="3401*"      fo:start-indent="0cm"     fo:end-indent="0.499cm"/>
<style:column          style:rel-width="6237*"         fo:start-indent="0.499cm"
fo:end-indent="0cm"/>        </style:columns>        </style:section-properties>
</style:style>

#+OPTIONS: ':t \n:nil f:t date:nil <:nil |:t timestamp:nil H:nil toc:nil num:nil d:nil ^:t tags:nil
# tags		Toggle inclusion of tags
# '			Toggle smart quotes
# \n		newline = new paragraph
# f			Enable footnotes
# date		Doesn't include date
# timestamp Doesn't include any time/date active/inactive stamps
# |			Includes tables.
# <			Toggle inclusion of the creation time in the exported file
# H:3		Exports 3 leavels of headings. 4th and on are treated as lists.
# toc		Doesn't include table of contents.
# num:1		Includes numbers of headings only, if they are or the 1st order.
# d			Doesn't include drawers.
# ^			Toggle TeX-like syntax for sub- and superscripts. If you write ‘^:{}’, ‘a_{b}’ is interpreted, but the simple ‘a_b’ is left as it is.
---------------------------------------------------------------------------------------------------------------------------------------
#+STARTUP: fnadjust
# Sort and renumber footnotes as they are being made.
---------------------------------------------------------------------------------------------------------------------------------------
#+OPTIONS: author:nil creator:nil
# Doesn't include author's name
# Doesn't include creator (= firm)

#+ODT_STYLES_FILE: "/home/oscar/Documents/Monte-Karlos/odt vzor/MonteKarlosNěkdeník1-2020.ott"
:END:
#+TITLE: MONTE KARLOS NĚKDENÍK
#+SUBTITLE: 
Vítejte v Monte Karlos, 
#+ODT: <text:section text:style-name="EditorialSect" text:name="Editorial">
* 2/2019
Ročník XXVIIII

*Adresa redakce:* Karlosova 77, 000 03 Monte Carlo 4

*E-mail:* EmailNoReply@server.mok

*Zákaznická linka:* 0004 892 223 03E

*Šéfredaktor:* Alžběta Ašelová

*Manažer redakce:* Jiří b'Ačkora

*Zástupce šéfredaktora:* Hobbo Habán

*Fotograf:* Alexandra Dimitrij von Dieseldorf

*Grafická úprava:* Tara Kočí

*Obrazová redakce:* Honza Kůň

*Rozhovor:* Karlos Žebatý, Lubomír Lečko

*Politická recenze:* Olšana Kupé

*Móda:* Šlapeboso Elle'Gante

*Editoři:* Aráb a'Ráb, P. Harrold

*Inkvizitor:* Paramount Fox

*Vydavatel:* Monte Karlos Inc. a. s.r.o. a spol©

*Brand manager:* Karlos Žebatý

*Sociální poradce:* Lightningh Danger

*Sociální podpora:* Anna Oleš

*Inzerce:* Many Hrabal

*E-shop:* nakupsisam.cz

*Tiskne:* individuálně

*Korespondent:* 

*Vyšetřovatel:* Sir Daniel Jonathan Pace

*Rozšiřují:* google.com

/Monte Karlos Někdeník/ byl založen  skupinou černých nosorožců afrických v létě
roku  1989.  Jeho  stránky  byly   poznamenány  takovými  autory  jako  Alexandr
Malinovský, Jack  O'Clock a Veronika Oškalová  a všeobecnému ohlasu se  těší již
třetím rokem  pod brilantním  vedením šéfredaktorky  Alžběty Ašelové©.  Stojí na
železobetonových základech, neboť všichni zaměstnanci od grafiků přes editory po
prachbídné korespondenty  se řídí  všestrannými, nesmrtelnými  pravidly slušného
chování.
* Editorial                                                             :200:


Alžběta Ašelová, šéfredaktor
#+ODT: </text:section>
* Zprávy                                                                :350:
:news:
Topic [fish in heating]
Designing principle [new house; fish are a feature; we're selling]
Random thing [this stuff is normal in Ukraine since 1976]
Story [Housing agency struggling to sell the houses]
Characters [salesmen, CEO]
Voice [author eats fish]
Logistics of story [public reaction; history of product;...]
Quotes, vision, assessment
:END:
#+ODT: <text:section text:style-name="NormalSect" text:name="Zprávy">
** Porušení dohody Duny
Silniční války v druhé polovině šedesátých  let byly krutou a nepříjemnou etapou
naší společné historie. Ke konci pohltila statisíce životů nejen lidských, nýbrž
i protivníkových.  Dohoda Duny  představovala mírovou  smlouvu mezi  všemi třemi
válčícími stranami  - lisdtvem, Unií  asfaltu, železa  a betonu a  štěrkem. Naši
nepřátelé tehdy přistoupili na lidské  podmínky souznění a společně uzavřeli mír
na půdě neutrálního  písku v Gobi. Následovalo vytvoření dohody  Duny, která mír
stvrzovala.

Podle  dohody,  mimo  jiné,  jsou  asfalty  zavázány  ke  spolupráci  ve  věcech
silničních výměnou za pravidelnou (a nadměrnou) dodávku ananasu. Jistý asfalt na
T-křižovatce na  západní Ukrajině se  však nedávno odhodlal napadnout  tuto námi
poskytnutou  symbiózu. V  noci  z úterý  na pátek  bez  varování odmítl  povolit
přepravu tří dodávek přes střed křižovatky. Řidiči tak byli v rozpacích.

„Já  nejsem  žádnej právník,“  říká  pan  Chrastivějský,  který jím  od  pohledu
opravdu, ale  opravud není,  „ale znám  trochu historie.  DD nikdy  nepočítala s
takovou situací, jestli  se tam můžu vyjádřit.“ Pan  Chrastivějský má překvapivě
pravdu. Podle  dohody nesmí člověk  nutit asfalt dělat,  co sám dělat  nechce, v
souladu  s Deskou  základních materiálních  práv.  Podle stejné  dohody je  však
asfalt  povinen  sloužit,  chci  říct  asistovat nám  na  cestách.  Dohoda  Duny
nestanovuje žádný aparát pro řešení takovéto situace.

Mezinárodní  sdružení asfaltů  se distancovalo  od názorů  tohoto asfaltu.  Jeho
předleža praví:  „Je zřejmé, že  asfalt na křižovatce  E125 a R554  trpí jakousi
poruchou mysli  a MSA je  toho názoru, že  by mu neuškodila  celková přestavba.“
Štěrk se vzápětí distancoval od celé situace a odsypal se ze záběru kamer.

Zatím  nevděčný  asfalt na  křižovatce  odmítá  podat hlášení.  Jeho  stanovisko
ohledně přejezdu  přes „jeho území“, jak  tomu panovačně říká, se  nijak nemění.
Pokusy o mírové řešení selhaly ještě dřív, než začaly, a ukrajindká policie byla
nucena  uzavřít   celou  oblast   a  vyhraničit  několikametrový   objezd  kolem
inkriminované křižovatky. MSA  si následně začalo stěžovat, že  na jejich asfalt
jsou pokládána příliš těžká břemena, a vyžaduje okamžitou nápravu.

Na  rozdíl od  své  vlády začala  asfaltská komunita  s  asfaltem na  křižovatce
sympatizovat. Mnozí  se teď  ptají, jestli  je dohoda  Duny stále  prospěšná pro
původní Unii. Nevděčníci[fn:1]■
** Avalon 4
:news:
Topic [fish in heating]
	Books too good for their own good.
Designing principle [new house; fish are a feature; we're selling]
	An author has written a book series  so good people started bullying him for
	it.
Random thing [this stuff is normal in Ukraine since 1976]
	No book series is allowed to be so good and share the spotlight with LOTR.
Story [Housing agency struggling to sell the houses]
	P. Harrold has been writing a book series for the past eight years. With all
	the books he's been on the edge  of perfection, but the last one practically
	pushed him  to the realm  of perfect books. This  is not allowed  and people
	have started to demand his head.
Characters [salesmen, CEO]
	P. Harrold
Voice [author eats fish]
	Written by P. Harrold himself
Logistics of story [public reaction; history of product;...]
Quotes, vision, assessment
:END:
Světoznámý autor moderní Sci-Fi P. Harrold čelí nařčení z ataku na pravidlo JRR,
stanovené soudním precedentem  v 18. století. Jeho slavná knižní  série Avalon 4
je podle jeho fanoušků příliš dobrá a vyžaduje přepracování.

Před osmi  lety vydal P.  Harrold první knihu  Avalonu 4, Temnou  Skulinu. Kniha
byla vyprodána  do dvou týdnů a  nakladatelství muselo dělat dva  další dotisky,
než se čtenáři uklidnili. Od té  doby vydal Sloupy štěstí, Pět černých skořápek,
Pofidérní  vagabundy a  začátkem tohoto  roku Skupinu  jezevců, jeho  (podle jeho
skromného názoru) nejlepší dílo.

Celá  série se  těšila nevídanému  výsluní.  Autor na  ní vydělal  přes tři  sta
milionů dolarů. Jeho poslední kniha, Skupina jezevců, ale jeho úspěchy zhatila.

Podle každého  žijícího kritika je Skupina  jezevců nejlepší kniha v  Avalonu 4.
Prodala víc  kopií než Windows XP  a nelegálně si ji  stáhlo víc lidí než  Hru o
stoly. Ale její úspěch se stal její záhubou.

V soudním sporu z roku 1768 rozhodla porota, že žádná kniha, především fiktivní,
nesmí dosahovat kvality Pána prstenů. Zejména  pak hloubka jejího světa musí být
limitována detailností Středozemě. Harroldova série je přitom především chválena
za kvalitu jím vytvořeného vesmíru. Když vyšla Skupina jezevců, netrvalo dlouho,
než si fanoušci všimli, že se jedná o knihu takřka perfektní a bez vady. A to se
nesmí tolerovat.

Mnozí  přispěchali na  obranu  skvělého autora.  Jeden  velmi potentní  argument
tvrdil, že Pán  prstenů není zas tak  dobrý, načež byl mluvčí  ušlapán davem. P.
Harrold přitom cítil, že  měl pravdu. Ale precedent je precedent  a Avalon 4 tak
čelí  největšímu útoku  na fiktivní  svět v  dějinách toho  skutečného[fn:2]. P.
Harrold byl zachráněn z pranýře skupinou největších fanoušků a převezen do Jižní
Afriky, kde  tamější komunita strávila  pět let  stavěním známých lokací  z jeho
příběhu. P. Harrold se  obrnil na palubě své nejoblíbenější lodi  a nevyšel z ní
již druhým  měsícem, ačkoli je  těžké rozeznat,  jestli ze strachu  před soudním
řízením, nebo před koronavirem.

Útoky  na jeho  osobu  neustaly  ani v  jeho  nepřítomnosti. Celkové  stanovisko
knižního parlamentu v Himálajích je silně ovlivněno jejich vztahem k celé sérii,
což  P. považuje  za zcela  normální, ale  veřejnost s  ním opět  nesouhlasí. P.
Harrold tak píše další knihu v sérii a čeká na svou příležitost zaútočit.
#+ODT: </text:section>
* Závod
#+ODT: <text:section text:style-name="NormalSect" text:name="Závod">
** Vývoj                                                                :400:
Mezinárodní Úřad  pro Úplnou a  Asertivní Spolupráci Spojených Států  Místních i
Zahraničních za Účelem Světového Míru, Obchodu  a Výměny Služeb měl v posledních
týdnech napilno. Ve světle mizících  učitelů Dvaceti statečných (dvaceti nejvýše
postavených učitelích v závodě o /nejvyššího vůdce všeho učitelstva) se rozhodli
provést důkladné  vyšetřování níže  situovaných kantorů přihlášených  do závodu.
Jejich cílem bylo objevit, kdo z nich může stát za těmito útoky.

Pokusy Mezinárodního  Úřadu byly  zcela bez  výsledku na  poli vyšetřovatelském,
přinesly zato plody  v oblasti jiné. Podrobným zkoumáním míst  3042 až 3990 byli
objeveni dosud  přehlížení učitelé z  Guatemalských jižních kmenů. Na  rozdíl od
svých aftických  protivníků, nemají  tito patřičné  doklady potřebné  k doložení
svého  učitelství. Mezinárodní  Úřad  zahájil další  vyšetřování  do celé  věci,
posunul ho na dobu neuričtou, protože se právě soustředil na mizející kantory, a
tváří v tvář  svému neúspěchu se k  nim vrátil s vervou  poražených a odhodláním
těch, kterým hrozí pokles ve veřejném mínění.

Političtí  odborníci  praví,  že  jejich  zásah do  života  Guatemaly  je  zcela
pochopitelný. Musí  prý světu  ukázat, že přestupky  proti pravidlům  se nebudou
tolerovat. Celá situace  je tedy o to  ošemetnější, že nikdo na  Úřadě neví, kdo
kantory unáší, a nemůže tudíž nikoho potrestat.

„Může se stát,“  řekl Obřísko Šuplijský, „že se dostaneme  k symbolickému trestu
pachatelů. Úřad si někoho vybere a  potrestáho ho exemplárně, bez ohledu na jeho
vinu. Co vidíme v Guatemale je jen začátek.“

A co že to vidíme v Guatemale? Celkem devět tamních okultních lídrů je podrobeno
důkladným prověrkám a přezkoumáváním, aby se  Úřad ujistil, že se skutečně jedná
o učitele.  Vyšetřující si Někdeníku  stěžují na obtížnost svého  úkolu, protože
M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. nikdy  nestanovilo, co všechno musí  kantor umět,
aby kantorem byl, a  od kdy je jeho kantorství dostatečné  pro příjem do závodu.
Tyto otázky měly prý být vyžešeny před jejich přijetím do závodu v minulém roce.

Mezi ostatními  kantory se šíří  pobouření. Pan Komenský, jako  seniorní poradce
Úřadu, se  vyjádřil, že dokud neučí  národ, nemají, co v  soutěži dělat. Obi-Wan
Kenobi, nejproslulejší spirituální učitel, zastává  názor opačný, a to že jejich
příspěvky  světovému učení  mohou přinést  potřebnou dávku  osvícení. Profesorka
McGonagallová se zdrřela komentáře.

Osud  guatemalských rádoby  kantorů je  nejistý. Vše  záleží na  tom, jestli  se
podaří najít  pachatele únosů. Lidé si  přitom nejsou jisti, že  se tento skrývá
mezi kantory. Nezbývá, než čekat.
** Postupy v žebříčku                                                   :400:
#+BEGIN_EXAMPLE
1. Ludmila Malá
2. Jiří Šeiner
3. Dana Kubešová
4. Dagmar Kolářová
5. Dušan Rychnovský
6. Martina Rotreklová
7. Zdenka Lajdová
8. Věra Zemánková
9. Lenka Vývodová
10. Taťána Jakešová
11. Marie Vávrová
12. Jana Horáková
13. Marta Křenková
14. Hana Mužíková
15. Elisie G’uaun Ebbe
16. Josef Král
17. Ivo Macháček
18. Gustav Havell
19. Jiří Lysák
20. Otakar su-džima a'Líma
#+END_EXAMPLE
Zatímco se  M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S. snaží  zastavit mizení  své autority,
učitelé  Dvaceti statečných  se  snaží  zastavit mizení  sebe  sama. Po  zmizení
tehdejšího vůdce  žebříčku, pana Šeinera,  který se  propadl o jedno  celé míst,
začali společně  stavět bunkr,  do které  se plánují  schovat. Jenpilněji  se na
práci podílí paní Rotreklová a Malá, které jsou si obě jisté, že útočníci půjdou
brzy po  nich. Jejich  ustavičné popohánění  ostatních jim  vysloužilo přezdívku
diktátorky, ale vesměs se zdá býti účinné.

Paní Kubešová ke  své smůle nedokázala využít výhody  poskutnuté svým špehováním
na  někdejší /Pálkovská  squad/,  a  začase postupně  ztrácet  body. Její  místo
převzala paní  Malá, nemalou zásluhou  svého vystoupení  na Tlačence, a  ta byla
následně vynesena na místo první, když Šeiner Kubešovou následoval.

Ostatní zmizelí kantoři se potkávají  se stejným osudem. Macháček zažil největší
propad - celých  devět míst, ale Horáková ho těsně  následuje. Mužíková ztratila
dvě příčky, Vávrová rovněž a nejdéle  zmizelý pan Langer byl kompletně vystřídán
na poli Dvaceti statečných  Otakarem su-džimou a'Límou, severohavajskému učiteli
tance, kterému dal  Mazinárodní Úřad pět dní k dostavení  se do Der Weiderhohlle
Flüsemschliessem.

Zde je  nutno podotknout, že podle  stále platících pravidel jsou  všichni dosud
zmínění zmizelí  vyloučeni z  celého závodu,  ale M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S.
nehodlá  ztrácet  čas  vyřazováním  jejich  jmen z  žebříčku.  Prý  se  postupně
propadnou sami a nebudou dělat problémy.

Mluvíme-li ale  o zmizelích  učitelích, nesmíme  opomenout jistéha  pana Lysáka,
slavného učitele  tělocviku a dějepisu na  gymnáziu v Hranicích. Na  Moravě. Pan
Lysák si  vyžádal neplacené  volno od Der  Weiderhohlle Flüsemschliessem  a jako
důvod uvedl naléhavou  záležitost s hraničkou tělocvičnou.  Ačkoli jeho povolená
doba nepřítomnosti  ještě nevypršela,  neodpovídá na žádné  pokusy o  kontakt ze
strany svých  voličů, sponzorů, novinářů  ani Úřadu samotného. Jeho  nejbližší -
dva   medicimbálové  míče   -  se   domnívají,  že   dostal  vzkaz   od  únosce,
předstírajícího poruchu  v tělocvičnách, a  byl unesen. Veřejnost  zaplavil stav
bláznivého nadšení, ale rovněž strachu z budoucnosti závodu.

Kdo zůstává  nepříjemně klidný,  je paní Lajdová.  Přesněji řečeno,  její nemalé
rozhořčení pramení čistě  jen ze ztráty jejích bodů. Zatímco  ona voliče ztrácí,
paní Rotreklová  je nabírá (ku svě  jistě nemalé radosti) a  momentálně jsou obě
učitelky vedle  sebe. Na závěr ještě  dodáme, že kromě přehození  Rychnovského a
Kolářové je v žebříčku docela klidno.
#+ODT: </text:section>
** Rozhovor - „“

#+ODT: <text:section text:style-name="InterviewSect" text:name="Interview">
*** Kampaň
*** Rychlá střelba
*** Korespondence
*** Závěrečný proslov

#+ODT: </text:section>
** Hodnocení odborníka                                                  :350:
#+ODT: <text:section text:style-name="NormalSect" text:name="Hodnocení">

#+ODT: </text:section>
* Korespondent - 
* Lifestyle
Módní sekce Monte Karlos Někdeníku vám přináší 

* Vyšetřování
** Dokumenty
** _Část první: Nepřítel za branami_
*** 

* Poznámky

[fn:1] Neberte mě špatně. Já nejsem materialista. Můj nejlepší přítel ze střední
školy byl  kus chodníku. Ale když  si ti asfalti nedovedou  uvědomit, jakou čest
jim nabízíme, když je necháváme pro nás pracovat, co mám dělat?

[fn:2] Je  nutné dodat, že  v Avalonu 4 existuje  knižní série Babylon  5, která
čelí většímu

