# -*-eval: (setq-local org-footnote-section "Poznámky"); eval: (set-input-method "czech-qwerty"); eval: (set-register ?\' "“"); eval: (set-register ?\" "„");eval: (set-register ? "M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S."); eval: (set-register ? "");-*-
:Uvozovky:
# \bdquo = „
# \ldquo = “
# \sbquo = ‚
# \lsquo = ‘
# [[https://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html][LaTeX symbols]]
:END:
:stuff:
#+OPTIONS: ':t \n:t f:t date:nil <:nil |:t timestamp:nil H:nil toc:nil num:1 d:nil ^:t
# '			Toggle smart quotes
# \n		newline = new paragraph
# f			Enable footnotes
# date		Doesn't include date
# timestamp Doesn't include any time/date active/inactive stamps
# |			Includes tables.
# <			Toggle inclusion of the creation time in the exported file
# H:3		Exports 3 leavels of headings. 4th and on are treated as lists.
# toc		Doesn't include table of contents.
# num:1		Includes numbers of headings only, if they are or the 1st order.
# d			Doesn't include drawers.
# ^			Toggle TeX-like syntax for sub- and superscripts. If you write ‘^:{}’, ‘a_{b}’ is interpreted, but the simple ‘a_b’ is left as it is.
---------------------------------------------------------------------------------------------------------------------------------------
#+STARTUP: fnadjust
# Sort and renumber footnotes as they are being made.
---------------------------------------------------------------------------------------------------------------------------------------
#+OPTIONS: author:nil creator:nil
# Doesn't include author's name
# Doesn't include creator (= firm)
:END:
#+TITLE: MONTE KARLOS NĚKDENÍK
#+SUBTITLE: Časy se mňeňý

* 26/2019
Ročník XXVIIII

*Adresa redakce:*
Karlosova 77, 000 03 Monte Carlo 4

*E-mail:*
EmailNoReply@server.mok

*Zákaznická linka:*
0004 892 223 03E

*Šéfredaktor:*
Alžběta Ašelová

*Manažer redakce:*
Jiří b'Ačkora

*Zástupce šéfredaktora:*
Hobbo Habán

*Fotograf:*
Alexandra Dimitrij von Dieseldorf

*Grafická úprava:*
Tara Kočí

*Obrazová redakce:*
Honza Kůň

*Rozhovor:*
Karlos Žebatý, Lubomír Lečko

*Politická recenze:*
Olšana Kupé

*Editoři:*
Šimon Balabán, Aráb a'Ráb, Andrew McTallas

*Lyžař:*
Natürlich Teppich

*Vydavatel:*
Monte Karlos Inc. a. s.r.o. a spol©

*Brand manager:*
Karlos Žebatý

*Sociální poradce:*
Lightningh Danger

*Sociální podpora:*
Anna Oleš

*Inzerce:*
Many Hrabal

*E-shop:*
nakupsisam.cz

*Tiskne:*
individuálně

*Korespondent:*
Ž'pel alla Frusciogn

*Rozšiřují:*
google.com

/Monte Karlos Někdeník/ byl založen skupinou černých nosorožců afrických v létě roku 1989. Jeho stránkami byly poznamenány takovými autory jako Alexandr Malinovský, Jack O'Clock a Veronika Oškalová a všeobecnému ohlasu se těší již třetím rokem pod brilantním vedením šéfredaktorky Alžběty Ašelové©. Stojí na železobetonových základech, neboť všichni zaměstnanci od grafiků přes editory po prachbídné korespondenty se řídí všestrannými, nesmrtelnými pravidly slušného chování.
* Editorial
Při svých cestách Indickými tundrami jsem se seznámila s tamním mecenášem, Ivanem Osčkou Islijoviččem, svým pozdějším spoluautorem Listů Korejských. Když jsem ho potkala (na rozcestí mezi dvěma chudými vesničkami), dali jsme se do řeči o životě v indické komunitě. Ivan mi tehdy předal své oblíbené pořekadlo, které si přivezl z Nigerijské savany: „Svět se nepodělal - tys zestárnul.“

Rychle jsem pochopila, co touto jednoduchou větou nigerští šamani mysleli. Lidé se neradi mění, jsou spokojení ve svém osobním /statutu quo/ a opovrhují progresi a inovaci světa. Jelikož jsem tehdy oslavila své první sedmdesátiny, považovala jsem se za jednoho z těch, kteří se ještě neuvelebili ve svých botách a kterým trocha změny neuškodí. Bylo těžké si myslet něco jiného, vzhledem k tomu, že jsem stála uprostřed zaprášené cesty od nikud nikam přes nic a nikudy, a to z vlastní, byť nedobrovolné, vůle.

Tehdy mladá dívčina, vřela ve mně touha bojovat proti celému světu a když by mi nebylo k dostání jiného způsobu, byla jsem připravena zuby nehty drápy kopyty bránit toto všeobjímající moudro: tys zestárnul. Svět je normální, říkala jsem si, jenom /vy/ staří s ním máte problém.

Teď už si to neříkám.

Za mých mladých let, jestli mi odpustíte ten výraz, bylo neslýchané, že by se bojům a válkám přihlíželo jako fotbalu či vodnímu pólu. Vojenské invaze byly brány s humorem státního pohřbu a kapitalistická vrstva si dobře uvědomovala, kde leží její hranice: v nedohlednu, ale nikdo to nesmí vědět. Dnes, pokud mi odpustíte i tento výraz, se s podobnými věcmi setkáváte denně, hodinně, možná i minutně. A aplaudujete tomu!

Závod o /nejvyššího vůdce všeho učitelstva/ přináší změny dosud nevídané. Neškodné soupeření mezi jednotlivci o totální vládu nad třemi procenty světové populace, tedy spor sám o sobě zcela neškodný, přerostl v naprostý chaos, ve kterém i prostý pracující člověk pln nadějí a touh nalézá své nezasloužené a popravdě nebezpečné místo. Zápas kantorů se nafoukl a přeměnil v zápas gigantů na poli bezmocných, raněných a níže sociálně postavených. Američtí finančníci si dělají ze světa boxovací ring a mocní a silní tohoto světa se obrací proti blahu svých poddaných a závislých pro osobní prospěch, zábavu a nezřízené choutky.

V takovém světě se pohybovat zabere energii. Mnoho energie. Nechcete-li se zaseknout a pozorovat, jak se civilizace pohybuje kolem vás, musíte se připoutat vystrčit nohu a pádlovat po proudu. Nebo veslovat - vaše preference jsou čistě vaše věc.

Ačkoli tomu sama nemohu uvěřit, vše je jiné. Lidé jsou jiní, společnost je jiná, prostředí je jiné. Stejně tak komunikace, doprava a moralita. Jediné, co není jiné, jsem já. Takže bych vás všechny, co se nestačíte divit, jak se vše kolem hýbe a posouvá, chtěla utěšit. Vězte, že já sama stojím pevně za starými tradicemi a budu podporovat vás všechny, kdo budete podporovat mě. A nezapomeňte - „Neposrali jste se - svět se změnil.“

Alžběta Ašelová, šéfredaktorka
* Zprávy
  :PROPERTIES:
  :VISIBILITY: content
  :END:
** Oranžová okupace
Koncem minulého týdne došlo na první krvavou potyčku v závodě o /nejvyššího vůdce všeho učitelstva/. Naštěstí nebyl nikdo zraněn. Nově zformovaná armáda Modré klobouky[fn:1] zahájila takzvaný Blitz-creek - čistě vojenskou akci pod praporem paní Pálkovské, při které byla sídla všech osmnácti kantorů hodnocených výše než paní Pálkovská obležena, dobyta a (podle paní Pálkovské dočasně) zkonfiskována. Velvyslanci Modrých klobouků, takzvaní Hockinéři, zajali ony představitele a pod přímím rozkazem zhůry jim pohrozili nepředstavitelnými lety nepopsatelných muk. Cílem byla legální abdikace části jejich hlasů v prospěch paní Pálkovské, která se tímto nečekaným krokem prodrala ze sedmnáctého místa na třinácté, oficiálně tak vstoupila do Arénské smečky[fn:2] a téměř tak dohnala rychle se propadajícího Iva Macháčka, veřejně usvědčeného ze soucitu, i pana Langera, který po svém stále nevysvětleném zmizení stoupl o šest míst a nyní je devátým v pořadí.

Momentálními největšími soupeři paní Pálkovské jsou paní Kolářová a Gustavel Havell, kteří se od prvního dne podílí o stejné místo. Na následující konferenci vedené panem Havellem, bohatým řeckým kantorem bujného ducha a svalnaté postavy, odhalil, že se spojil s paní Kolářovou a podepsali kontrakt permanentní aliance, ačkoli na sociálních i asociálních médiích se o jejich spojenectví spekulovalo již několik týdnů. Neboť tito noví společníci okupují dvanácté místo, budou sloužit jako první linie obrany proti dalším případným útokům paní Pálkovské na svou pozici.

Na dotaz, co pana Havella vedlo k tomuto spojenectví poznamenal: „[Paní Kolářové] nerozumím. Mluvíme jinými jazyky a žijeme daleko od sebe. Připadá mi to jako perfektní spojenectví.“ Tento výrok ho zřejmě stál nějaké body u nového spojence; později se snažil situaci vyžehlit: „To jsem řekl? Ne. Ne ne ne. To jsem neřekl. Nebo řekl? Ne. Ne, neřekl.“ a paní Kolářová na jeho náhlou změnu názoru reagovala: „Kdybych věděla, co říká, byla bych naštvaná.“

Paní Pálkovská se však (alespoň na oko) nijak Dagavlem Havářovou[fn:3] nezabývá. Její zrak se upíná na západ k vile Toogen-Hut, kde sídlí jediná skupina schopná jejím vojskům dočasně odolat. Velká pětka zřejmě v tajnosti sestavila značnou vojenskou sílu a její švýcarská pevnost padla až v jedenáct hodin večer po tvrdých bojích na zemi, ve vzduchu i pod stolem za cenu značných ztrát na straně Modrých klobouků. Všichni čtyři členové Velké pětky[fn:4] ale nakonec své body na paní Pálkovskou přepsali, ač neochotně a s brekem. Paní Horáková, vedocí Velké pětky, s pomocí UNICEFu - Uniquely Neccessary Ideological and Ceremonially Effective Faction, prchla z vily Toogen-Hut a v současnosti přetrvává v klášteře v Šumperku pod ochranou církve. Ostatní členové byli chyceni Elfem Oslovem, Hockinářem pro Toogen-Hut, a jsou drženi jako vojenští zajatci.

Paní Horáková v posledních dnech přizvávala pana Rychnovského, paní Ebbe, paní Jakešovou a dokonce, podržte se!, paní Křenkovou na soukromou konverzaci v klášteře. Paní Jakešová omylem oznámila obsah těchto setkání, když namísto emailu otevřela Facebook a poslala svůj kalendář všem svým následovníkům. Paní Horáková sestavuje dočasnou alianci mezi dostupnými a ochotnými kantory Dvaceti statečných za účelem kontraútoku na paní Pálkovskou a její Modré klobouky.

Veřejnosti neunikla značná absence paní Lajdové při těchto strategických krocích. Paní Lajdová, ačkoli neušetřena vojenské akce, i přes nemalou ztrátu bodů postoupila o další dvě místa. Matematici celého světa se sjeli na konciliu v Istanbulu, aby dvakrát dvojitě potvrdili, že tři minus dva je skutečně, bezesporu, nekompromisně jedna. Jelikož byla paní Lajdová na třetím místě, museli největší mozky světa[fn:5] prohlásit, že se paní Lajdová, přes všechny představitelé důvody, proč by se tak nemělo stát, momentálně dostala do naprostého vedení Dvaceti statečných. Sama zatím odmítá komentovat svůj úspěch.

Podle neoficiálních klepů Ivo Macháček odmítl spolupráci s paní Horákovou na takzvané Větší pětce a tajně se sešel s paní Pálkovskou. Jejich setkání zůstává nepotvrzené stejně jako záhadné, paní Kupé spekuluje, že se jedná o proti-alianci, kterou dává Pálkovská dohromady. Je-li její hypotéza správná, což ona vždy je, má /Monte Karlos Někdeník/ dobrý důvod se domnívat, že paní Malá, pan Král a pan Lysák se k ní přidali taktéž.

Momentálně je dějiště rozdělené na pět táborů: Pálkovská squad, Větší pětka, Dagavel Havářová, Nerozhodnutí a Lajdová. Ke konfrontaci mezi Dagavelem Havářovou a Pálkovsou squad zatím nedošlo, menší potržky se však již objevily na hranici mezi Argentinou a Brazílií, což ponechává nejednoho odborníka ve stavu zmatení, neboť ani jedna strana nemá s Argentinou ani Brazílií nic společného
** PO - DĚ
Irákem dmýchají nepokoje a masové protesty jak v ulicích největších měst Iráku[fn:6] tak v ulicích největších měst Iráku[fn:7]. Důvodem pro pobouření obyvatel je nová reforma školství, zavedená současným vůdcem Ikáru - současným vůdcem Iráku[fn:8], která se přímo dotýká všech oblastí lidského života od ekonomiky přes učitelství a zemědělství po nekrmovací. Současný vůdce Iráku spolu se svými spoluvlada-... rádc-... se svou vlád-... se svými /kolegy/ od začátku listopadu přísně vyžaduje dodržování vědeckého faktu, že číslo osm je, vždy bylo a vždy jen bude marnou snahou náboženských fanatiků o narušení chodu státu a jeho vývoje, čímž je současný vůdce Iráku označil za přímo zodpovědné za „současný stav naší země“, ačkoli mezi europolitiky vyvstává dotaz, zda náhodou, ve své egocentrické sebestřednosti, nemyslel Zemi.

O čísle osm se v Iráckém parlamen-... vládním orgánu debatuje již druhým rokem, nová školní reforma, ve které zákonodárce/i opomněli tento spor, však postrčila celý argument opozice do nicoty, neboť „když už se to jednou děti učí, proč si přidělávat starosti a ztěžovat lidem život?“ Starobylé označení pro množství dva krát čtyřech bylo tedy v Iráku zrušeno[fn:9] a od Iráčanů se očekává, že si na tuto změnu svižně a bezproblémově navyknou. Konec konců číslo osm nikdy neexistovalo.

Současný vůdce Iráku ustanovil pětidenní hranici, ve které občané o čísle osm, jeho zrušení a jeho existenci mohou otevřeně debatovat. Řada politických spekulantů na něj vznesla otázky typu: „Když mám v jedné ruce pět koulí a ve druhé ruce tři koule, kolik mám tedy dohromady koulí?“[fn:10] a „Kolik je devět minus jedna?“[fn:11] Všechny tyto otázky byly současným vůdcem Iráku hravě smeteny ze stolu a ze zdravotních důvodu byla spekulační doba zkrácena z pěti dní na dva. Dotazy.

Všechny Irácké počítače byly svezeny na místo určení a vhozeny do největší irácké řeky[fn:12]. Irácký lid bude adaptovat novou výpočetní techniku, která uznává, že 2^3 = 16, což podle iráckého vědeckého minis-... odbo-...[fn:13] vědecké kanceláře zvýší výkonnost procesorů, neboť na co bylo dříve potřeba tranzistorů pět jsou nyní potřeba tři, tedy značené vylepšení v poměru 14:-0,44.

Učitelé na základních školách budou v polovině iráckého vzdušného měsíce[fn:14] testováni, zda plně adaptovali novou vyučovací formu. Dva krát čtyři kontroloři, tedy devět, bude přiděleno každé mateřské škole, aby v přestrojení za žáky vysledovali ty kantory, kteří zůstávají při starých vyvrácených taktikách nezbožné matematiky. Případné dopady této reformy na ekonomiku na Istanbulské burze[fn:15] bude řešen, až tento nastane.

V dalších zprávách ze středního východu, Irák přidává další den do svého dodnes standardního týdne. Oficiální seznam dní je nyní: Pondělí, úterý, středa, čtvrtek, pátek, sobota, neděle, děle. Duchovní vůdce blíže nespecifikovaného počtu Iráčanů vznesl námitku, že s osmi dny v týdnu nikdo nepočítá, byl poté předvolán před nejvyšší státní soud a popraven za kacířství
** HTBBB Club, Mayami
Noviny /Mayami Yesterday/ publikovaly v průběhu předešlých dvanácti dní šest anonymních článků ve své stálé rubrice /Tell us about/ Your /problems/ nazvaných /Tales of the ring/, zabývající se neortodoxním podnikem v severně severní části Mayamského přístavu. Tak zvaný HTBBBC - How to Bear a Bare Bear Club - jeden z nejstarších městských klubů v okolí se po vydání prvního z těchto šesti článků stal místní senzací a turistickou atrakcí milénia.

How to Bear a Bare Bear Club, vedený Ostentativním Bažantem Ludvíkem zvaným Děravým, je k nalezení na střetu osmačtyřicáté rovnoběžky a tramvajových kolejí linky 18 v rekonstrukci. Jeho vchod - velké dubové gotické dveře zdobené ornamenty a skalpy Ludvíkových nepřátel - vás zavede do předsálí, takzvané čekárny smrti. Zde vám budou servírovány koktejly z celého světa (oblíbeným se zdá být London Lemming[fn:16]) a obsluhovat vás bude nejlepší personál ve městě. To však jen pokud přijdete před pátou hodinou ranní. Západního standardního času, tj. jedenáct hodin v Mayami. Jinak budete ochrankou v gepardích kožiších provedení čekárnou smrti a vpuštěni do podzemní arény, kde každou noc jeden zahraniční a jeden domácí student soupeří o plné stipendium na místní technopolitické universitě v krvavém zápase na život a na smrt s medvědem.

Tato praktika je necelé století stará, avšak až do vydání /Mayami Yesterday/-ových článků nebyla známá ani přístupná široké veřejnosti - čekárnou smrti po jedenácté hodnině jste mohli projít jen s platnou zákaznickou kartou nebo dokladem o studentském dluhu. Dlouhé generace majitelů tvrdě pracovaly na svém malém profilu, aby nepřitahovaly zbytečnou pozornost ochráncům zvířat a později liberálních médií. V důsledku publikace se však přede dveřmi HTBBBC shromažďují davy turistů i místních zvědavců a Ostentativní Bažant Ludvík v úsvitu nového ekonomického plánu otevřel dveře nočních aktivit svého podniku pro všechny odvážlivce, bez ohledu na sexualitu, světovou orientaci či rasistické předsudky.

Pokud se budete chtít podívat na jeden takový zápas v televizi, musíme vám bohužel oznámit, že jste přišli pozdě. V race 2003 bylo veškeré natáčení a všechna distribuce již natočených zápasů přísně zakázána státem, neboť inspekce shledala, že se v ringu jednalo o nepovolené natáčení zvířat a ohrožování filmového štábu.

Tento tah, který sliboval majetkový i firemní růst se však ukazuje, jako nedostatečně promyšlená akce. Zaměstnanci HTBBBC si v posledních dnech začali stěžovat na pokles podnikových standardů. Někteří z nich poskytli /Monte Karlos Někdeníku/ exkluzivní rozhovor (stejně jako /Mayami Yesterday, New York Times, Times, The Times, The Time, Sometimes/ a /Mladé frontě dnes Times/). Manažer večerních zápasů ku příkladu mluvil o náhlém nedostatku míst na sezení.

Současní političtí kandidáti, zejména Bernie Sanders, na jedné ze svých shromáždění vyjádřit znepokojení s americkým systémem školství. „Jak je to možné,“ ptal se, „že studenti musí podstupovat takové aktivity, jen aby si mohli dovolit dostat diplom? V jedenáct hodin už mají přece dávno spát!“ Dále navrhuje posunutí celé akce do studentům příjemnějších, brzkých ranních hodin. Rovněž se objevily spekulace ohledně morálního hlediska celého podniku. Nutit dva studenty denně do zápasu s medvědem, jen aby mohli zaplatit za své vzdělání, je podle některých progresivních aktivistů netolerovatelné a hraničí to s neetickým zacházením se zvířaty
* Host
  :PROPERTIES:
  :VISIBILITY: content
  :END:
** Rozhovor - „[Lenger] mně nijak nechybí“/„Kdo by mi chtěl něco udělat?“/„To nechápu proč.“/„Chtěla bych napodobit tažení Napoleona.“
Paní Lenka Pálkovská - dvojnásobná mistryně světa v nesmyslných testech, pětinásobná držitelka ceny za nejdelšího zápisu za hodinu a členka Guinnessovy knihy rekordů za největší množství nepodstatných informací za hodinu! Paní Pálkovská učí dějepis na Gymnáziu v malém městě na střední Moravě ve střední Evropě na střední Zemi. Ve středním slunečním systému na kraji Galaxie. S podprůměrnými znalostmi ve svém oboru. A ve všem ostatním.

*Proč učíte dějepis, když o něm nic nevíte?*

Já toho vím o dějepise spoustu.

*Pokud se naše zdroje nemýlí, máte děti. Teď, když jste se dostala do vrchní patnáctky, tak zvané arénské smečky, připravila jste je na svou statisticky pravděpodobnou smrt v aréně, jako by panovník připravil svého dědice?*

Abych pravdu řekla, tak nepřipravila. Ale myslím, že se s tím dobře srovnají i tak.

*Takže si sama připouštíte možnost, že to tak pro vás dopadne. Tedy smrtí.*

Samozřejmě se to může stát. V historii ale spousta panovníků s něčím počítala a dopadlo to úplně jinak.

*Vidíte se sama, jako panovník?*

Rozhodně ne. Já se vidím jenom jako blbá chudá učitelka.

*Ve vztahu k postu /nejvyššího vůdce všeho učitelstva/, berete to jako sílu nebo slabinu, že vám nikdo nemusí odpovídat, stačí jen kývat hlavou?*

Nevím tak úplně, o čem mluvíte, ale rozhodně je to silná stránka.

*Konec konců je asi lepší mít panovníka, který vás nepopraví, když nemáte odpověď, že?*

Já si myslím, že když vám nedají odpověď, je nejlepší si odpovědět sám. Aspoň jste s tou odpovědí pak spokojený.

*Jak reagujete na zmizení pana Langera?*

Mně nijak nechybí.

*Zavedla jste nějaká nová bezpečnostní opatření?*

Já osobně? Ne. Ale mí kolegové až příliš.

*Takže se nedomníváte, že byste sama byla v nebezpečí?*

Neeee. Kdo by mi chtěl něco udělat?

*Pan Langer je vaším nadřízeným. Jak využíváte jeho absence ve škole?*

Já bych řekla, že je to úplně stejné, jako když ve škole byl. Stejně tam nic nedělal.

*Myslíte si, že byste jeho práci dělala lépe?*

No... Když je teď tak někde pryč, tak si troufnu říct, že ano.

*Ucházela jste se někdy o jeho místo?*

Ne, neucházela. To by mi nestálo za to.

*Popište nám prosím, co nejpřesněji, co dělala Marie Terezie, když její manžel zemřel.*

Zachovala chladnou hlavu, zavedla novou reformu školství, sbalila si svých pět švestek a odjela na dovolenou do Jugoslávie.

*Správná odpověď je "truchlila". Pan Rychnovský odmítl sdělit své důvody pro nespojení se s paní Křenkovou. Vy s ní sdílíte kabinet, je to tak?*

Ano.

*Jaké důvody máte vy?*

Víte, paní Křenková nám až moc podezřele nabízela spolupráci.

*Takže jde o strategické rozhodnutí, nikoli osobní?*

Řekla bych, že ano.

*Kolují zvěsti, že se ve vaší škole pracuje na reorganizaci kabinetů, protože s vámi paní Křenková odmítá sdílet pracoviště. Můžete na to nějak reagovat?*

To nechápu proč.

*Jak soudíte jednání velké pětky ve vztahu k paní Záchelové?[fn:17]*

A co myslíte, že měla dělat, když si to tak pokazila.

*Myslíte si, že je jakýkoli způsob, jakým by se mohla dostat aspoň do první stovky?*

Určitě nějaký je, ale nevím, proč bych jí měla radit.

*Dovedete si představit, že se sama ocitnete tak nízko a sama byste využila tohoto způsobu?*

Pokud bych se dostala tak nízko, tak bych samozřejmě bojovala o návrat.

*Takže bojovat až do poslední chvilky?*

Rozhodně. Já tuto soutěž neberu na lehkou váhu a doufám, že vy také ne.

*Já rozhodně ne. Tato soutěž mě živí. Co vaše další kolegyně, paní Lajdová? Dokážete si, se svým historickým rozhledem, vysvětlit její postup?*

Upřímně řečeno, ne. Je to skoro jako když se Hitler ujal vlády v Německu.

*Myslíte si, že někoho utlačuje?*

Ona utlačuje úplně všechny, jenom některé s cukrovým úsměvem. Jiné, na ty jí ani nestojí za to, aby ho používala.
*** Kampaň
*Jste spokojena s názvem vaší nedávné akce, Oranžová okupace, či byste preferovala jiný?*

Já bych raději svému vojsku říkala Modré klobouky. Rozhodně nechápu, kde někdo vzal tak směšné jméno. Modré klobouky by rozhodně byl lepší název.

*Mezinárodní ústav pro úplnou a asertivní spolupráci atd. se vyjádřil, že jste technicky neporušila žádná pravidla voleb. Věděla jste, že tomu tak je, nebo vás to nezajímalo?*

Pročíst se celými pravidly voleb je nesplnitelný úkol. Nicméně, kdybych tušila, že je to proti pravidlům, tak bych takovýto krok nepodnikla. Takže jsem doufala, že to je v pořádku.

*Musí si vaše armáda psát zápisy, když jim vysvětlujete strategii?*

Ne, moje armáda je soběstačná. Moji žáci si musí psát zápisy, aby dějepis zvládli. To snad ani jinak nejde.

*To dává smysl. Někomu. Zůstanete-li v arénské smečce, bude vám povoleno, jako každému uchazeči, vzít si s sebou do arény jeden libovolný předmět či jednu věc. Budete se snažit právně dokázat, že vaše armáda je jedna věc?*

Myslím, že ne. Stačí, když si postaví dost velkého trojského koně.

*Jakožto učitel dějepisu máte přístup k velkým strategickým vítězstvím historie. Hodláte některá z nich v závodě napodobit?*

Rozhodně bych chtěla napodobit tažení Napoleona. A také se mi líbí způsob boje římských centurionů.

*Necháváte si podobně kroky až do arény, nebo je hodláte použít dříve?*

To, co jsem vám řekla, to využiju dříve a do arény si chystám překvapení.
*** Random otázka dne
*Musíte se přeobjednat na konzultaci s věštcem?*

Víte, v historii tomu tak dříve bývalo. Například v Delfách jste měli čekací dobu tak rok nebo dva. Ale dne už se na to pohlíží jinak. Ale pravda, dlouho už jsem u žádného věštce nebyla a nevím, jak to teď je.

*Zvážila byste návštěvu věštce ohledně tohoto závodu?*

Rozhodně. Ale víte, dnes je velice těžké najít někoho dobrého.
*** Rychlá střelba
*Kdy byla bitva na Bílé hoře?*

Roku 1426.

*Kdy byla bitva na Hnědé hoře?*

Bitva na Hnědé hoře... Nebyla.

*Podrobně nám popište události druhé světové války.*

Hitler obsadil Polsko, ale nakonec prohrál.

*Kdo z dvaceti statečných vás nejvíce děsí?*

Pan Rychnovský.

*Měla jste někdy pocit, že vaše učitelské schopnosti nedosahují národních standardů?*

Ne. Já si myslím, že s titulem PhD nemám problém.
*** Korespondence
*V historickém muzeum v Chicagu byl nalezen mayský obětní kámen s následujícím nápisem:*

*Paní Pálkovská,*

*Jak si to jako přestavujete?*

*Berete si tuto urážku osobně?*

Upřímně, nepřipadá mi to jako urážka.
*** Závěrečný proslov
*Po vítězství svých vojsk jste prohlásila, že hledáte armádního maskota. Závěrečným proslovem nám prosím popište, co máte na mysli, pokud možno tak, aby diváci poznali, jaké jsou vaše hodnoty jako benevolentního a mírumilovného lídra.*

V Římě se často bojovalo ve formaci želva. Já si myslím, že želva by tudíž nebyl dobrý maskot pro mojí armádu. Spíše kohouta. Nejlépe fialového.

*To je velmi zajímavá barva. Jak jste na ní přišla?*

Ona symbolizuje svobodu a vítězství
** Hodnocení odborníka
Paní Pálkovská je zapeklitý případ a tak trochu doutník z oceli, jestli víte, co tím myslím. Na jednu stranu vypadá inteligentně a uspořádaně - odpovídá k věci (až na jednu chvíli, kdy na otázku, zda souhlasí s pojmenováním /akce/ Oranžová okupace, odpověděla, že by byla radši, kdyby se její /armáda/ jmenovala Modré klobouky; ale to se dá připsat profesionální únavě stejně snadno jako debilitě, takže to necháme stranou), zbytečně nemluví ani neodporuje a její nedávný úspěch ukazuje na člověka s bystrou myslí a taktickým důvtipem. Na druhou stranu je úplně mimo.

Jak bych to jenom popsala? Vypadá to, že paní Pálkovská není v přímém kontaktu s realitou. Možná jí volá jednou za měsíc, možná si občas pošlou pohled s dalekých... předalekých krajin, ale v jedné místnosti se nesešli už dobrých dvacet, třicet let a špatných dvakrát tolik. Je mi upřímně záhadou, jak se to mohlo stát, že její plány vyšly, když nedokáže ani odhadnout celkový stav politického prostředí a šlape na vzpomínku pana Langera, který stoupá v popularitě každým dnem. Můj osobní názor na jeho současnou kandidaturu je nepodstatný, jen bych chtěla podotknout, že vyhraje-li aniž by se našel, bude z něj pravděpodobně ten nejúspěšnější diktátor všech dob.

Stejně tak si paní Pálkovská nechce připustit, že je v nějakém nebezpečí. „Kdo by mi chtěl něco udělat?“ ptá se. Ale no tak, Lenko, to snad nemyslíš vážně... Jak jako, kdo by mi chtěl něco udělat? Všichni. Úplně. Všichni. Do jednoho. Neposílila obranu a dokonce si dělá srandu ze svých kolegů, kteří tak učinili. Mícha předchází řád.

V rozhovoru demonstrovala znalost svého oboru na úrovni opeřeného jednorožce. „Marie Terezie si sbalila svých pět švestek a odjela na dovolenou do Jugoslávie.“ To pardon, ale ne. Marie Terezie měla mnohem, mnohem víc švestek.

Podobné rozpolcení mezi nadměrným intelektem a naprostou ignorací světa demonstruje paní Pálkovská velmi konzistentně. Pan Macháček, jak jsme se doslechli, s ní uzavřel spojenectví, zatímco pomoc Křenkové razantně odmítá. Paní Křenková se teď pravděpodobně přidala na stranu Větší pětky a paní Pálkovská si za to může sama.

O jejím vojenském tažení jsem se již zmínila. Ale na veřejnosti přiznat, že nečetla pravidla voleb... Vypovídá to hodně o vás jako o člověku, když nemáte ani tolik úsudku lhát v mezinárodní televizi o svých znalostech těchto voleb. Může jí to stát nejeden hlas a paní Pálkovská mi přijde trochu podnapilá svým náhlým úspěchem.

Co se týče její strategie, upřímně ji nemohu dostatečně vynachválit. Paní Pálkovská, zdá se, rozumí této hře lépe, než zatím kdokoli, koho jsme v /Monte Karlos/ měli. Nechává si překvapení pro své soupeře, ale navnazuje voliče a sponzory nepřímými narážkami na svou strategii se slibem bezprecedentní zábavy. Neříká toho moc a neříká toho málo. Co bych ji vytkla, bylo přímě přiznání strachu z pana Rychnovského, ale jinak si v pohodlí své strategické vlády sedí jako Johana v kalamáři.

Shrnutím bych tedy řekla toto: Paní Pálkovská mi zůstává záhadou. Jedná se o případ génia v kůže malomocného, či malomocného tak řka ve vlastní šťávě? Je její úspěch pouhou náhodou, či přetrvá a vynese ji do předních příček? Těžko se posuzuje, zda je natolik inteligentní, že dokáže vystupovat neinteligentně, či natolik zaostalá, že nám její nápady připadají z jiného světa? Může to být tak i tak - vždyť i Ikaros občas listí shrabával. Nezbývá, než dočkat času jako sovět pasu
* Korespondent
Beaujolais nouveau 2059

Převzato z nezávislého extranetového serveru B-S ENQUETE

Kdo na jaře nezaváhal a zakoupil ve „first minute“ předstihu některý z limitované edice reduit- voucherů na transterestrickou restaurační základnu Brillat-Savarin na Mysu Bec fin při okraji Mare ingenii, aby zde strávil oblíbený La Semaine du Saint-Martin, jenž je už mnoho let kýženým zážitkovým eventem všech solaire-systéme-gurmánů, takže jistě není třeba jej nějak zvlášť představovat, ten jednoduše neprohloupil. Chcete-li si dopřát opravdu jedinečný, komplexní extraordinární zážitek, pak investice do cesty na Bec fin je tou první a bez diskuse nejlepší volbou, zvlášť pokud máte zálibu v lunárním brandu středomořské kuchyně a v lehkých francouzských vínech s extrapolovaným zráním. Nedejte se však tak úplně zmást: za své víno a šneky zaplatíte víc, než si myslíte…

…

Patnáct Lovellovských hvězd, které restaurace řetězce Brillat-Savarin za dobu své existence posbíraly, je i pro neznalé či začátečníky dostatečnou garancí špičkového lunárního gastronomického zážitku. Zakladatel a majitel první transterestrické sítě gastronomických zařízení Brillat-Savarin – mecenáš-lidumil André Bé – vtiskl tomuto svému životnímu počinu pečeť všestranné nekompromisní kvality, z níž se jeho potomci (a budoucí dědicové), kteří restauraci nyní spravují, neodvažují ani v nejmenším slevit, neboť by jim hrozila nejen ostuda vpravdě meziplanetárních rozměrů, ale, což je horší, také vydědění, a to samozřejmě nechtějí riskovat. (Majetek Andrého Bé je, mimochodem řečeno, nezávislými odborníky odhadován na stovky miliard Spacecoinů.) Pro návštěvníky je to jedině dobře, poněvadž náklady, které vynaložili na letenky, ubytování a samotnou konzumaci, jsou vskutku nemalé, ba nezdráhejme se přiznat, že jsou přímo velké, takže za ně oplátkou očekávají přiměřeně úchvatné požitky a – přirozeně – naprosto dokonalý servis. Obojího se jim zatím každoročně dostalo – a netřeba pochybovat, že se jich dočkají i letos.

Dějiny sítě espace-art culinaire, nesoucí jméno věhlasného francouzského labužníka z 19. století, jsou samy o sobě nevšedním příběhem s puncem tajemna a dekadence. To ale na popularitě Brillat-Savarinu nijak neubíralo a neubírá, naopak, temné tóny v pozadí jeho existence jsou tou nejpřitažlivější a nejfunkčnější reklamou, jakou si jeho majitel může přát: návštěvníci se díky nim jen hrnou, zatímco zájem úředníků Intergalaktické celní a finanční správy přešlapuje v uctivém odstupu. Ty nejbizarnější momenty z historie restaurace (a ze životopisu jejího majitele) jsou často předmětem pochyb a odmítání, a to nejen ze strany Béových stoupenců, obdivovatelů a plagiátorů, což se samozřejmě dá čekat, ale i ze strany těch střízlivěji naladěných kritiků. Obecně vzalo, málokdo je ochoten uvěřit, že důvodem k Béovu tak úspěnému transplanetárnímu angažmá byla pouhopouhá geniální podnikatelská intuice či neodbytná kreativní potřeba vtisknout vlastní tvář nově se rozvíjejícímu space-gourmat byznysu, nicméně ne každý je zároveň ochoten akceptovat prosakující zvěsti, že za Béovými tehdejšími kroky vězela obyčejná nutnost outsourceovat zatímní podnikatelské aktivity ze zaostalého prostředí východní Evropy počátků tohoto století jak nejdál to půjde.
 
Každá návštěva relaxačně-restauračního komplexu na Bec fin je nejen cestovatelským a labužnickým bonbónkem, ale i manažerským zážitkem, který si vychutnáte s mnohaměsíčním předstihem. Je to gejzír podnikatelské invence, vnášející do naší sterilně dokonalé doby závan lidskosti „starých zlatých časů“. Kdo si chce cestu dopřát, musí mít předem zajištěno nejen financování (to je samozřejmost), ale i všechna úřední a zdravotní povolení, lustrační osvědčení, osvědčení o rasové, státní, národnostní, komunitní, jazykové, politické, náboženské a sexuální příslušnosti, musí dodat výpisy z kont a státních evidenčních rejstříků, doklad o ultimativním pojištění, certifikát beztrestnosti, bezúhonnosti, bezvadnosti a bezstarostnosti, důkaz o nulové uhlíkové stopě s platností minimálně patnáct let zpětně, potvrzení o řádném placení daní minimálně na pět let dopředu, výpis evidence volební účasti s přehledem volebních preferencí, vysvědčení od 1. třídy a doklad o povinném očkování sebe, své rodiny a svého psa. Kdo není majitelem psa, musí o tom dodat potvrzení místně příslušné správy.  Potvrzení se evidují u servisní organizace sítě Brillat-Savarin na exteritoriálním orbitálním úložišti Dossier. Není to levné (uložení, které je pro následujících patnáct let povinné, si zájemce musí zaplatit), výhodou však je, že většina potvrzení může být využita znovu při dalším případném letu na Bec fin či na jakoukoli jinou solaire-systeme základnu společnosti Brillat-Savarin, která přitom ovšem úzkostlivě dbá na dodržování zásad ochrany osobních údajů, takže jakákoli informace (potvrzení, osvědčení, certifikát apod.), evidovaná pro potřeby letu se společností Brillat-Savarin, nemůže být užita při transplanetárním letu s jakoukoli jinou společností, což je pro klienty Brillat-Savarinu nesporně uklidňující.

Časové a mentální nároky na pořízení žádané dokumentace jsou tak vysoké, že se společnost Brillat-Savarin rozhodla provozovat také síť podpůrných agentur, které zájemcům o let na Bec fin potřebné materiály zajistí a ověří. Ani to není levné, protože obstarání všech dokumentů vyžaduje vysokou profesionalitu a psychickou odolnost, je to však služba špičkové kvality, k níž klienti Brillat-Savarinu mohou sáhnout bez obav a s nejvyšší důvěrou. Koneckonců let na Bec fin je svobodným rozhodnutím náročných jedinců, jejichž sebeúcta by nabídkou levných služeb byla neomluvitelně poškozena.

Kompletací potřebné dokumentace ale cesta k vysněnému „Svatomartinskému týdnu“ na Bec fin nekončí, spíše začíná. Je nutné obstarat si potřebná povolení k průletu atmosférou a vstupní a výstupní víza do lunární oblasti Mare ingenii. Ty vydá každý místně příslušný check-point Intergalaktického úřadu pro exterestrický pohyb osob, zboží a služeb, je ale třeba prokázat se před tímto úřadem potvrzením, nikoli starším dvou let a s dobou platnosti ne menší než šest měsíců, že žadatel netrpí orbitálním komplexem.

Cestovatel si ale musí obstarat a zaplatit také speciální vybavení a oblečení, absolvovat trénink a sérii zdravotních vyšetření a několik sezení s psychologem. Vlastní cesta raketoplánem na základnu Bec fin a několikadenní pobyt ve zdejším hotelovém centru jsou pak jen třešničkou na dortu, upečeném z mnohaměsíčních náročných příprav. Vrcholem podzimní tour - La Semaine du Saint-Martin – je čtvrteční soirée, na němž se po escargot a fromage con truffe nemůže podávat nic jiného než nové lehké červené víno. Beaujolais nouveau est arrivé!  - i na Měsíci…

…

V bohaté historii espace-gourmat sítě Brillat-Savarin nalezneme momenty úspěchu i zklamání, nečekané výzvy i zasloužené pocty. Na počátku stálo smělé rozhodnutí Andrého Béa vsadit vše na jedinou kartu nově se rodícího odvětví exterestrického gastroprůmyslu, v jehož budoucnost v té chvíli věřil jen málokdo, dokonce ani sám Bé, který se právě potýkal s krachem své dotud jediné významnější gastrofirmy, malé francouzské navet-restaurace v Provenci, a byl co do podnikání v tomto oboru značně skeptický. Podle sporadických zpráv, které dnes máme k dispozici, stála za životním rozhodnutím budoucího kapitána espace-restauratérství jeho tehdejší choť Monique, která se touto cestou snažila vzpružit otřeseného obchodního ducha svého muže. Jistý vliv ale mohly mít i potíže, již začaly pociťovat i další firmy Andrého Béa a které jej nutily odklonit jeho podnikatelské aktivity jiným směrem.

Světlo světa tak spatřila první, relativně ještě skromná provozovna, pramáti budoucí sítě Brillat-Savarin. André Bé ji otevřel po pouhých třech letech příprav v roce 2022 na první stálé lunární základně při úpatí Montes Pyrenaeus nad Mare Nectaris. Šlo spíše o kosmické bistro, které nabízelo osádce základny kávu z automatu a balené avokádové tousty, náklady na provoz byly vysoké a obrat nízký. Bé založil na podporu svého nového podnikání řadu vlivových agentur a najal množství výkonných lobbistů, jejichž prostřednictvím chtěl u právě zřízené Globální vesmírné agentury (GASA) docílit toho, aby byly do standardizované výbavy lunárních základen, které začaly být zřizovány na měsíčním povrchu, povinně přidávány také kávové automaty a sady avokádových toustů, produkované jeho espace-gastrofirmou Brillat-Savarin, která by na dodávky těchto produktů měla na příštích 500 let u GASA monopol. Tento postup se Béovi v jeho podnikatelských aktivitách již dříve osvědčil. Zdlouhavá jednání a byrokratické překážky ze strany GASA přivedly nicméně Béa k rozhodnutí zapojit do hry také soukromý kapitál, nikoli samozřejmě jeho vlastní, nýbrž třetích osob. Vyměnil své neúspěšné lobbisty za PR manažery, jejichž prostřednictvím vyvolal nadšený zájem movitých celebrit o lunární gastro-turistiku. Následovala masivní crowdfundingová vlna, v níž se matadoři světového bankovnictví a byznysu s vidinou osobní spoluúčasti na formování moderní exterestricity doslova předháněli v poskytování darů a dotací na rozjezd a další rozvoj Béovy sílící solaire-system firmy. Za jejich peníze byla síť transplanetárních restaurací a hotelů Brillat-Savarin na světě raz dva. A zatímco její gastro divize, vedená Béovou manželkou Monique, se věnovala deklarovanému předmětu činnosti, espace-gastronomii, espace-sommelierství a hoteliérství, Bé sám se začal s úspěchem zabývat mnohem zajímavějšími vedlejšími aktivitami, k nimž jej přivedla dlouhodobá spolupráce s předními světovými lídry. Tak vznikla informační a servisní divize společnosti – Dossier, skutečná základna dnešní moci a úspěchu André Béa, umně skrytá za šneky a beaujolais
* Poznámky

[fn:1] Za název je zodpovědná paní Lenka Pálkovská - viz Rozhovor.

[fn:2] Arénská smečka je skupina kantorů na patnáctém a vyšším místě žebříčku. Po posledním kole veřejných voleb budou kantoři na těchto postech puštěni do arény, kde se rozhodne o osudu všeho učitelstva na dalších pět až devět tisíciletí.

[fn:3] Oficiální spojenecké jméno paní Dagmar Kolářové a pana Gustava Havella.

[fn:4] Nezapomeňme, že paní Záchelová byla velkou pětkou brutálně zrazena a opuštěna pro neskutečnou neschopnost a, promiňte mou francouzštinu, debilitu.

[fn:5] Nebo alespoň pusy k těmto mozkům přivěšené. /Monte Karlos Někdeník/ v žádném případě netvrdí, že má vnitřní informace o skutečných postojích těchto mozků.

[fn:6] Však je znáte. Ta města. V Iráku. A co, že nevíte, jak se jmenují. Jsou to města. V Iráku.

[fn:7] Ano, je to tak. Když se naleznete v Iráku mimo ulici těch největších měst, je velká šance, že jste se nalezli na poušti. A pardon, ale nikdo nemůže čekat, že se bude protestovat na poušti.

[fn:8] Však víte. Současný politický vůdce. V Iráku. Co jiného o něm potřebujete vědět? Stačí to, že vede Irák už... nějakou dobu, pod svou politickou... stranou? NE, agendou. Tak. Politický vůdce Iráku s politickou agendou, který už tam je nějakou dobu. Toho přesně myslíme.

[fn:9] Někteří by řekli odhaleno.

[fn:10] Tazatel byl následně zatčen za podezření z terorismu, neboť na veřejné půdě prohlašoval, že má střelnou munici doslova po ruce. I přesto mu současný vůdce Iráku odpověděl: „Taková situace nemůže vůbec nastat. Kdyby mohla, měli bychom pro popsání tohoto hypotetického množství nějaké pojmenování a jelikož ho nemáme, prostě to nejde.“ Zároveň tazatele upozornil, že po skončení pětidenní lhůty bude pouhé vyřčení trestáno dle zákona, tedy tak, jak praví ústa-... zákon. Ano, přesně ten. Ten zákon, kterým se lidé v Iráku řídí. Tazatel byl poli-... vojen-... příslušníky výkonné mo-... Tazatel by držen pod zámkem dva týdny, kdy byl předveden před soud a pořádán, aby přednesl svůj protiargument. Vzhledem k tomu, že v té chvíli již přešla doba pro debatu ohledně osmičky, za přednesení svých argumentů byl tazatel potrestán podle zákona.

[fn:11] Podle školské reformy sedm.

[fn:12] Ano, té nej... Víte co? Hledejte si to na mapě sami. Mě tu nikdo neplatí od toho, abych vás vodil po glóbu a ukazoval vám prstíčkem, kde je jaká řeka a kdo vládne kde s jakou státní strukturou. Děkuju mnohokrát.

[fn:13] Víte co? Jako byste poznali, kdyby to bylo blbě. Kašlu na vás. Stejně to po mně Ašelová nikdy nečte.

[fn:14] Ha. A teď nevíte. Mají v Iráku jiné měsíce, než u nás? Kolik jich je v roce? A je islám v Iráku to náboženství, které prohlašuje, že Země je pět tisíc let stará? Když o tom tak přemýšlíte, je v Iráku hlavní náboženství islám? A když tak přemýšlíte o /tom/, je islám vlastně náboženství? A je měsíc slovo, nebo číslo? A není Země náhodou 2019 let stará? Kdo ví? Kdo ví? (Vy ne.)

[fn:15] Já vím, já vím. Istanbul je v Turecku. Ale /je/ Istanbul skutečně v Turecku? A není Turecko náhodou v Iráku? A není... dál už to zvládnete sami. Ale když už jsme u toho, až se vám podaří naprosto se zmást otázkami, zda je Istanbul vůbec město (nebyl to náhodou typ vonné svíčky?), zeptejte se sami sebe, zda tam je burza...

[fn:16] Džin, vodka, armaňak, sherry a trochu parmazánu.

[fn:17] Velká pětka, které byla paní Záchelová součástí, ji po jejím rapidním pádu nepomohla a vyřadila ji ze svých řad. Jméno Velká pětka stále přetrvává, protože paní Horáková, vůdkyně tohoto sdružení, už za něj zaplatila patentní poplatek.

