# -*-eval: (setq-local org-footnote-section "Poznámky"); eval: (set-input-method "czech-qwerty"); eval: (set-register ?\' "“"); eval: (set-register ?\" "„");eval: (set-register ? "M.Ú.Ú.A.S.S.S.M.Z.Ú.S.M.O.V.S."); eval: (set-register ? "■"); eval: (ispell-change-dictionary "czech"); eval: (flyspell-mode 1);-*-
:stuff:
<style:style style:name="InterviewSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="3" fo:column-gap="0.497cm">
<style:column style:rel-width="21845*" fo:start-indent="0cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0.249cm"/>
<style:column style:rel-width="21845*" fo:start-indent="0.249cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style style:name="NormalSect" style:family="section">
<style:section-properties text:dont-balance-text-columns="false" style:editable="false">
<style:columns fo:column-count="2" fo:column-gap="0.998cm">
<style:column style:rel-width="32767*" fo:start-indent="0cm" fo:end-indent="0.499cm"/>
<style:column style:rel-width="32768*" fo:start-indent="0.499cm" fo:end-indent="0cm"/>
</style:columns>
</style:section-properties>
</style:style>

<style:style          style:name="EditorialSect"         style:family="section">
<style:section-properties                  text:dont-balance-text-columns="true"
style:editable="false">   <style:columns    fo:column-count="2">   <style:column
style:rel-width="3401*"      fo:start-indent="0cm"     fo:end-indent="0.499cm"/>
<style:column          style:rel-width="6237*"         fo:start-indent="0.499cm"
fo:end-indent="0cm"/>        </style:columns>        </style:section-properties><
/style:style>

# ' Toggle smart quotes
# \n		newline = new paragraph
# f			Enable footnotes
# date		Doesn't include date
# timestamp Doesn't include any time/date active/inactive stamps
# |			Includes tables.
# <			Toggle inclusion of the creation time in the exported file
# H:3		Exports 3 leavels of headings. 4th and on are treated as lists.
# toc		Doesn't include table of contents.
# num:1		Includes numbers of headings only, if they are or the 1st order.
# d			Doesn't include drawers.
# ^			Toggle TeX-like syntax for sub- and superscripts. If you write ‘^:{}’, ‘a_{b}’ is interpreted, but the simple ‘a_b’ is left as it is.
#+OPTIONS: ':t \n:t f:t date:nil <:nil |:t timestamp:nil H:nil toc:nil num:nil d:nil ^:t tags:nil
---------------------------------------------------------------------------------------------------------------------------------------
#+STARTUP: fnadjust
# Sort and renumber footnotes as they are being made.
---------------------------------------------------------------------------------------------------------------------------------------
#+OPTIONS: author:nil creator:nil
# Doesn't include author's name
# Doesn't include creator (= firm)
:END:
#+TITLE: MONTE KARLOS NĚKDENÍK
#+SUBTITLE: 

* _/2020
Ročník XXVV

*Adresa redakce:* Karlosova 77, 000 03 Monte Carlo 4

*E-mail:* EmailNoReply@server.mok

*Zákaznická linka:* 0004 892 223 03E

*Šéfredaktor:* Alžběta Ašelová

*Manažer redakce:* Jiří b'Ačkora

*Zástupce šéfredaktora:* Hobbo Habán

*Fotograf:* Alexandra Dimitrij von Dieseldorf

*Grafická úprava:* Tara Kočí

*Obrazová redakce:* Honza Kůň

*Rozhovor:* Karlos Žebatý, Lubomír Lečko

*Móda:* Šlapeboso Elle'Gante

*Závodní ekonomie:* Financier Kovva-Lečný

*Kaňonskop:* 

*Editoři:* 

*:* 

*Vydavatel:* Monte Karlos Inc. a. s.r.o. a spol©

*Brand manager:* Karlos Žebatý

*Sociální poradce:* Lightningh Danger

*Sociální podpora:* Anna Oleš

*Inzerce:* Many Hrabal

*E-shop:* nakupsisam.cz

*Tiskne:* individuálně

*Korespondent:* 

*Špeh:* nevíme

*Seniorní bankomat:* Tera Mažetková

*Cestopis:* Áron Ponurý a Emanuel Bebeš

*Rozšiřují:* google.com
* Editorial                                                             :250:


Alžběta Ašelová, šéfredaktor
* Závodní ekonomie - Spolková bankovní federace II
Mí věrní čtenáři, moji drazí přátelé, mí milí kolegové - i ty, Jakube -, dnešek skýtá poslední příležitost k vašemu světovému vzdělání, neboť má práce zde je dokonána. Po dnešním vydání mého profesionálního výkladu /závodní/ ekonomie už nebude nic, co bych vám mohl vysvětlil, aniž byste potřebovali pětadvacet let pilného studia matematiky, ekonomie a hudby. Závěrem svého vypravování vám dávám sbohem detailnějším popisem Spolkové bankovní federace. Toto je konec konců ekonomická rubrika.

Někteří mí čtenáři - hlavně Bob - stále nechápou, jak může Federace kontrolovat životy učitelů, voličů, sponzorů i úřadníků[fn:1]. Inu, jejich vliv je velmi silně zakořeněn ve strachu. Úřad vybral spolkové banky jako místo pro úschovu hlasů, protože nenašel lepší variantu, které by lidé široko daleko věřili. Toto vytvořilo jistou závislost na bankách, které jestli mohlo být předejito, mělo se tak stát velmi brzy. Lidé mají strach, že jiný systém nemůže fungovat, protože žádný jiný nikdy nefungoval. To, že jiný fungovat nemohl, protože se žádný jiný nezkusil, je velmi intelektuální krok, kterého není většina lidstva schopná.

Spolkové banky teď mají neomezenou možnost dělat si, co chtějí, a Úřad musí poslechnout, jinak o něj přijde. Banky samotné tedy řídí průběh a pravidla /závodu/, i když se všichni - hlavně Bob - tvář, že tomu tak není. Před pár měsíci se jim podařilo znovu zprovoznit celý /závod/ jen poukázáním na to, že se jim nelíbí, že stagnuje.

Nad učiteli má Federace možná ještě větší moc. S nedávnou změnou v systému uschovávání hlasů jsou všichni učitelé závislí na slovu paní Lajdové, která kontroluje všechnu hlasovou složku /závodu/, a skrze ní banky velí všem uchazečům o post nejvyššího vůdce všeho učitelstva. Chrání si ji a našeptávají jí, mají vlastní obranné složky, které má stále po ruce, a jelikož si mezi učiteli zajistila jakýs takýs monopol na realitu, mají banky téměř neomezenou možnost její osoby využívat. Komu se to nelíbí, může ze závodu odejít.

Odejít mohli i před tím, než paní Lajdová převzala kontrolu. Tehdy si Federace zajišťovala jejich přítomnost pouhým faktem, že jinde schraňovat hlasy nebylo povoleno pravidly závodu. A tak, i když jim to trvalo déle a museli se víc snažit, co řekli, to se stalo.

Banky samotné se řídí nepsaným pravidlem, že nebudou hrát roli sponzorů. Jelikož je ale nepsané, všichni ho ignorují. V poslední době všechny fandy směřují do kapsy paní Lajdové, která prakticky /závod/ už vyhrála. Kdo sází proti ní, ztrácí peníze. Kdyby se ale banky rozhodly, že už ji nebudou podporovat (oni se nerozhodnou, přišli by o svého jediného zákazníka v branži), a místo ní poskytly své zdroje jinému učiteli, všichni sponzoři je musí následovat, jinak znovu ztrácí peníze, nemluvě o těch, které již vrazili do Lajdové. Je to křehká bilance, ale opět zde platí, že jak Federace řekne, tak bude.

No a voliči? Kdy měli ti co dělat s výsledkem /závodu/?

** Rozdělení
Jak vidíte, spolkové banky jsou všude. Pojďme si nyní na závěr říct, jak fungují.

Každá banka musí být součástí Bankovní unie. Kdo nechce, je automaticky součástí Unie neunijních. Unií je dvacet devět a pro přidání další, Spolek Spolkové bankovní federace se musí shodnout na jejím založení.

Spolek Spolkové bankovní federace je nejvyšší orgán ve Federaci. Nejedná se ani tak o mozek společnosti, jako o žaludek. Všechny unie, nikoli banky, mají své představitele v tomto Spolku, protože jinak by se museli sházet v místnosti tak velké, že by zakřivovala časoprostor a lidé veprostřed by strávili více času na jednání kvůli efektům obecné teorie relativity[fn:2].

Chcete-li se stát součástí Federace, podepište se vlastní krví na internetový formulář na jejích oficiálních stránkách. Každý zaměstnanec dostává bankovní kartičku, která v civilizovaných zemích zastupuje občanský průkaz. Na ní je napsáno jejich jméno (číselný pětaosmdesátimístný kód, který banka používá místo zastaralých "jmen"), jméno jejich banky a unie, pracovní role a kredit, ke kterému se nebudu vyjadřovat, protože vím, že někteří by to nemuseli akceptovat s klidným žaludkem. Hlavně Bob.
* Zprávy                                                                :350:
* Cestopis
* Závod
** Vývoj                                                                :400:
   
#+begin_src emacs-lisp
  (progn (backward-kill-paragraph 1)
		 (insert-file (expand-file-name "~/Documents/Monte-Karlos/postupove centrum.org")))
#+end_src
** Rozhovor
* Korespondent
* Lifestyle
** Karlos-čepice
** Kaňonskop
* Šeiner
** Špeh
** Lekce bankomata

* Poznámky

[fn:1] Zaměstnanci Úřadu.

[fn:2] Jisté pokusy byly provedeny s rotačními rozvrhy, kdy se zástupci banek uprostřed střídají, ale experiment byl zastaven, když se uvnitř sálu shromáždilo přílišné množství částic a ze schůze zbyla jen černá díra.
